package com.connectivity.vikray.model;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AccountAddress generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT_ADDRESS", catalog = "namcrm")
public class AccountAddress implements java.io.Serializable {

	private long id;
	private AccountDetail accountDetail;
	private String addressLine1;
	private String addressLine2;
	private String addressType;
	private String city;
	private String country;
	private boolean isDefault;
	private String state;
	private String zipCode;
	private Integer addrdetailsIntegerIdx;
	private boolean isDisabled;
	private Set<DeliveryChallan> deliveryChallansForBillingFk = new HashSet<DeliveryChallan>(0);
	private Set<DeliveryChallan> deliveryChallansForShippingFk = new HashSet<DeliveryChallan>(0);
	private Set<InvoiceHeader> invoiceHeadersForBillingFk = new HashSet<InvoiceHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForShippingFk = new HashSet<SalesOrderHeader>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders = new HashSet<PurchaseOrderHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForBillingFk = new HashSet<SalesOrderHeader>(0);
	private Set<InvoiceHeader> invoiceHeadersForBillingFk_1 = new HashSet<InvoiceHeader>(0);
	private Set<PurchaseEntry> purchaseEntries = new HashSet<PurchaseEntry>(0);
	private Set<InvoiceHeader> invoiceHeadersForShippingFk = new HashSet<InvoiceHeader>(0);
	private Set<PurchaseEntry> purchaseEntries_1 = new HashSet<PurchaseEntry>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders_1 = new HashSet<PurchaseOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForBillingFk_1 = new HashSet<DeliveryChallan>(0);
	private Set<InvoiceHeader> invoiceHeadersForShippingFk_1 = new HashSet<InvoiceHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForShippingFk_1 = new HashSet<SalesOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForShippingFk_1 = new HashSet<DeliveryChallan>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForBillingFk_1 = new HashSet<SalesOrderHeader>(0);

	public AccountAddress() {
	}

	public AccountAddress(long id, boolean isDefault, boolean isDisabled) {
		this.id = id;
		this.isDefault = isDefault;
		this.isDisabled = isDisabled;
	}

	public AccountAddress(long id, AccountDetail accountDetail, String addressLine1, String addressLine2,
			String addressType, String city, String country, boolean isDefault, String state, String zipCode,
			Integer addrdetailsIntegerIdx, boolean isDisabled, Set<DeliveryChallan> deliveryChallansForBillingFk,
			Set<DeliveryChallan> deliveryChallansForShippingFk, Set<InvoiceHeader> invoiceHeadersForBillingFk,
			Set<SalesOrderHeader> salesOrderHeadersForShippingFk, Set<PurchaseOrderHeader> purchaseOrderHeaders,
			Set<SalesOrderHeader> salesOrderHeadersForBillingFk, Set<InvoiceHeader> invoiceHeadersForBillingFk_1,
			Set<PurchaseEntry> purchaseEntries, Set<InvoiceHeader> invoiceHeadersForShippingFk,
			Set<PurchaseEntry> purchaseEntries_1, Set<PurchaseOrderHeader> purchaseOrderHeaders_1,
			Set<DeliveryChallan> deliveryChallansForBillingFk_1, Set<InvoiceHeader> invoiceHeadersForShippingFk_1,
			Set<SalesOrderHeader> salesOrderHeadersForShippingFk_1,
			Set<DeliveryChallan> deliveryChallansForShippingFk_1,
			Set<SalesOrderHeader> salesOrderHeadersForBillingFk_1) {
		this.id = id;
		this.accountDetail = accountDetail;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressType = addressType;
		this.city = city;
		this.country = country;
		this.isDefault = isDefault;
		this.state = state;
		this.zipCode = zipCode;
		this.addrdetailsIntegerIdx = addrdetailsIntegerIdx;
		this.isDisabled = isDisabled;
		this.deliveryChallansForBillingFk = deliveryChallansForBillingFk;
		this.deliveryChallansForShippingFk = deliveryChallansForShippingFk;
		this.invoiceHeadersForBillingFk = invoiceHeadersForBillingFk;
		this.salesOrderHeadersForShippingFk = salesOrderHeadersForShippingFk;
		this.purchaseOrderHeaders = purchaseOrderHeaders;
		this.salesOrderHeadersForBillingFk = salesOrderHeadersForBillingFk;
		this.invoiceHeadersForBillingFk_1 = invoiceHeadersForBillingFk_1;
		this.purchaseEntries = purchaseEntries;
		this.invoiceHeadersForShippingFk = invoiceHeadersForShippingFk;
		this.purchaseEntries_1 = purchaseEntries_1;
		this.purchaseOrderHeaders_1 = purchaseOrderHeaders_1;
		this.deliveryChallansForBillingFk_1 = deliveryChallansForBillingFk_1;
		this.invoiceHeadersForShippingFk_1 = invoiceHeadersForShippingFk_1;
		this.salesOrderHeadersForShippingFk_1 = salesOrderHeadersForShippingFk_1;
		this.deliveryChallansForShippingFk_1 = deliveryChallansForShippingFk_1;
		this.salesOrderHeadersForBillingFk_1 = salesOrderHeadersForBillingFk_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_FK")
	public AccountDetail getAccountDetail() {
		return this.accountDetail;
	}

	public void setAccountDetail(AccountDetail accountDetail) {
		this.accountDetail = accountDetail;
	}

	@Column(name = "ADDRESS_LINE1")
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE2")
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "ADDRESS_TYPE")
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "CITY")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "COUNTRY")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "IS_DEFAULT", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "STATE")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP_CODE")
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "ADDRDETAILS_INTEGER_IDX")
	public Integer getAddrdetailsIntegerIdx() {
		return this.addrdetailsIntegerIdx;
	}

	public void setAddrdetailsIntegerIdx(Integer addrdetailsIntegerIdx) {
		this.addrdetailsIntegerIdx = addrdetailsIntegerIdx;
	}

	@Column(name = "IS_DISABLED", nullable = false)
	public boolean isIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByBillingFk")
	public Set<DeliveryChallan> getDeliveryChallansForBillingFk() {
		return this.deliveryChallansForBillingFk;
	}

	public void setDeliveryChallansForBillingFk(Set<DeliveryChallan> deliveryChallansForBillingFk) {
		this.deliveryChallansForBillingFk = deliveryChallansForBillingFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByShippingFk")
	public Set<DeliveryChallan> getDeliveryChallansForShippingFk() {
		return this.deliveryChallansForShippingFk;
	}

	public void setDeliveryChallansForShippingFk(Set<DeliveryChallan> deliveryChallansForShippingFk) {
		this.deliveryChallansForShippingFk = deliveryChallansForShippingFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByBillingFk")
	public Set<InvoiceHeader> getInvoiceHeadersForBillingFk() {
		return this.invoiceHeadersForBillingFk;
	}

	public void setInvoiceHeadersForBillingFk(Set<InvoiceHeader> invoiceHeadersForBillingFk) {
		this.invoiceHeadersForBillingFk = invoiceHeadersForBillingFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByShippingFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForShippingFk() {
		return this.salesOrderHeadersForShippingFk;
	}

	public void setSalesOrderHeadersForShippingFk(Set<SalesOrderHeader> salesOrderHeadersForShippingFk) {
		this.salesOrderHeadersForShippingFk = salesOrderHeadersForShippingFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddress")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders() {
		return this.purchaseOrderHeaders;
	}

	public void setPurchaseOrderHeaders(Set<PurchaseOrderHeader> purchaseOrderHeaders) {
		this.purchaseOrderHeaders = purchaseOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByBillingFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForBillingFk() {
		return this.salesOrderHeadersForBillingFk;
	}

	public void setSalesOrderHeadersForBillingFk(Set<SalesOrderHeader> salesOrderHeadersForBillingFk) {
		this.salesOrderHeadersForBillingFk = salesOrderHeadersForBillingFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByBillingFk")
	public Set<InvoiceHeader> getInvoiceHeadersForBillingFk_1() {
		return this.invoiceHeadersForBillingFk_1;
	}

	public void setInvoiceHeadersForBillingFk_1(Set<InvoiceHeader> invoiceHeadersForBillingFk_1) {
		this.invoiceHeadersForBillingFk_1 = invoiceHeadersForBillingFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddress")
	public Set<PurchaseEntry> getPurchaseEntries() {
		return this.purchaseEntries;
	}

	public void setPurchaseEntries(Set<PurchaseEntry> purchaseEntries) {
		this.purchaseEntries = purchaseEntries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByShippingFk")
	public Set<InvoiceHeader> getInvoiceHeadersForShippingFk() {
		return this.invoiceHeadersForShippingFk;
	}

	public void setInvoiceHeadersForShippingFk(Set<InvoiceHeader> invoiceHeadersForShippingFk) {
		this.invoiceHeadersForShippingFk = invoiceHeadersForShippingFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddress")
	public Set<PurchaseEntry> getPurchaseEntries_1() {
		return this.purchaseEntries_1;
	}

	public void setPurchaseEntries_1(Set<PurchaseEntry> purchaseEntries_1) {
		this.purchaseEntries_1 = purchaseEntries_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddress")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders_1() {
		return this.purchaseOrderHeaders_1;
	}

	public void setPurchaseOrderHeaders_1(Set<PurchaseOrderHeader> purchaseOrderHeaders_1) {
		this.purchaseOrderHeaders_1 = purchaseOrderHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByBillingFk")
	public Set<DeliveryChallan> getDeliveryChallansForBillingFk_1() {
		return this.deliveryChallansForBillingFk_1;
	}

	public void setDeliveryChallansForBillingFk_1(Set<DeliveryChallan> deliveryChallansForBillingFk_1) {
		this.deliveryChallansForBillingFk_1 = deliveryChallansForBillingFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByShippingFk")
	public Set<InvoiceHeader> getInvoiceHeadersForShippingFk_1() {
		return this.invoiceHeadersForShippingFk_1;
	}

	public void setInvoiceHeadersForShippingFk_1(Set<InvoiceHeader> invoiceHeadersForShippingFk_1) {
		this.invoiceHeadersForShippingFk_1 = invoiceHeadersForShippingFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByShippingFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForShippingFk_1() {
		return this.salesOrderHeadersForShippingFk_1;
	}

	public void setSalesOrderHeadersForShippingFk_1(Set<SalesOrderHeader> salesOrderHeadersForShippingFk_1) {
		this.salesOrderHeadersForShippingFk_1 = salesOrderHeadersForShippingFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByShippingFk")
	public Set<DeliveryChallan> getDeliveryChallansForShippingFk_1() {
		return this.deliveryChallansForShippingFk_1;
	}

	public void setDeliveryChallansForShippingFk_1(Set<DeliveryChallan> deliveryChallansForShippingFk_1) {
		this.deliveryChallansForShippingFk_1 = deliveryChallansForShippingFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountAddressByBillingFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForBillingFk_1() {
		return this.salesOrderHeadersForBillingFk_1;
	}

	public void setSalesOrderHeadersForBillingFk_1(Set<SalesOrderHeader> salesOrderHeadersForBillingFk_1) {
		this.salesOrderHeadersForBillingFk_1 = salesOrderHeadersForBillingFk_1;
	}

}
