package com.connectivity.vikray.model;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CrmType generated by hbm2java
 */
@Entity
@Table(name = "CRM_TYPE", catalog = "namcrm")
public class CrmType implements java.io.Serializable {

	private long id;
	private String constByName;
	private String name;
	private String parentType;
	private Set<DeliveryChallan> deliveryChallansForDcPurposeTypeFk = new HashSet<DeliveryChallan>(0);
	private Set<InvoiceHeader> invoiceHeaders = new HashSet<InvoiceHeader>(0);
	private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders = new HashSet<PurchaseOrderHeader>(0);
	private Set<BusinessDeal> businessDealsForBuTypeFk = new HashSet<BusinessDeal>(0);
	private Set<InvoiceHeader> invoiceHeaders_1 = new HashSet<InvoiceHeader>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders_1 = new HashSet<PurchaseOrderHeader>(0);
	private Set<BusinessDeal> businessDealsForCrmTypeFk = new HashSet<BusinessDeal>(0);
	private Set<QuoteHeader> quoteHeadersForCrmTypeFk = new HashSet<QuoteHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeaders = new HashSet<SalesOrderHeader>(0);
	private Set<BusinessDeal> businessDealsForCrmTypeFk_1 = new HashSet<BusinessDeal>(0);
	private Set<GrnHeader> grnHeaders = new HashSet<GrnHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeaders_1 = new HashSet<SalesOrderHeader>(0);
	private Set<GrnHeader> grnHeaders_1 = new HashSet<GrnHeader>(0);
	private Set<QuoteHeader> quoteHeadersForFreightTypeCrmFk = new HashSet<QuoteHeader>(0);
	private Set<QuoteHeader> quoteHeadersForFreightTypeCrmFk_1 = new HashSet<QuoteHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForDcTypeFk = new HashSet<DeliveryChallan>(0);
	private Set<BusinessDeal> businessDealsForBuTypeFk_1 = new HashSet<BusinessDeal>(0);
	private Set<DeliveryChallan> deliveryChallansForDcTypeFk_1 = new HashSet<DeliveryChallan>(0);
	private Set<DeliveryChallan> deliveryChallansForDcPurposeTypeFk_1 = new HashSet<DeliveryChallan>(0);
	private Set<QuoteHeader> quoteHeadersForCrmTypeFk_1 = new HashSet<QuoteHeader>(0);
	private Set<UserDetails> userDetailses_1 = new HashSet<UserDetails>(0);

	public CrmType() {
	}

	public CrmType(long id) {
		this.id = id;
	}

	public CrmType(long id, String constByName, String name, String parentType,
			Set<DeliveryChallan> deliveryChallansForDcPurposeTypeFk, Set<InvoiceHeader> invoiceHeaders,
			Set<UserDetails> userDetailses, Set<PurchaseOrderHeader> purchaseOrderHeaders,
			Set<BusinessDeal> businessDealsForBuTypeFk, Set<InvoiceHeader> invoiceHeaders_1,
			Set<PurchaseOrderHeader> purchaseOrderHeaders_1, Set<BusinessDeal> businessDealsForCrmTypeFk,
			Set<QuoteHeader> quoteHeadersForCrmTypeFk, Set<SalesOrderHeader> salesOrderHeaders,
			Set<BusinessDeal> businessDealsForCrmTypeFk_1, Set<GrnHeader> grnHeaders,
			Set<SalesOrderHeader> salesOrderHeaders_1, Set<GrnHeader> grnHeaders_1,
			Set<QuoteHeader> quoteHeadersForFreightTypeCrmFk, Set<QuoteHeader> quoteHeadersForFreightTypeCrmFk_1,
			Set<DeliveryChallan> deliveryChallansForDcTypeFk, Set<BusinessDeal> businessDealsForBuTypeFk_1,
			Set<DeliveryChallan> deliveryChallansForDcTypeFk_1,
			Set<DeliveryChallan> deliveryChallansForDcPurposeTypeFk_1, Set<QuoteHeader> quoteHeadersForCrmTypeFk_1,
			Set<UserDetails> userDetailses_1) {
		this.id = id;
		this.constByName = constByName;
		this.name = name;
		this.parentType = parentType;
		this.deliveryChallansForDcPurposeTypeFk = deliveryChallansForDcPurposeTypeFk;
		this.invoiceHeaders = invoiceHeaders;
		this.userDetailses = userDetailses;
		this.purchaseOrderHeaders = purchaseOrderHeaders;
		this.businessDealsForBuTypeFk = businessDealsForBuTypeFk;
		this.invoiceHeaders_1 = invoiceHeaders_1;
		this.purchaseOrderHeaders_1 = purchaseOrderHeaders_1;
		this.businessDealsForCrmTypeFk = businessDealsForCrmTypeFk;
		this.quoteHeadersForCrmTypeFk = quoteHeadersForCrmTypeFk;
		this.salesOrderHeaders = salesOrderHeaders;
		this.businessDealsForCrmTypeFk_1 = businessDealsForCrmTypeFk_1;
		this.grnHeaders = grnHeaders;
		this.salesOrderHeaders_1 = salesOrderHeaders_1;
		this.grnHeaders_1 = grnHeaders_1;
		this.quoteHeadersForFreightTypeCrmFk = quoteHeadersForFreightTypeCrmFk;
		this.quoteHeadersForFreightTypeCrmFk_1 = quoteHeadersForFreightTypeCrmFk_1;
		this.deliveryChallansForDcTypeFk = deliveryChallansForDcTypeFk;
		this.businessDealsForBuTypeFk_1 = businessDealsForBuTypeFk_1;
		this.deliveryChallansForDcTypeFk_1 = deliveryChallansForDcTypeFk_1;
		this.deliveryChallansForDcPurposeTypeFk_1 = deliveryChallansForDcPurposeTypeFk_1;
		this.quoteHeadersForCrmTypeFk_1 = quoteHeadersForCrmTypeFk_1;
		this.userDetailses_1 = userDetailses_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CONST_BY_NAME")
	public String getConstByName() {
		return this.constByName;
	}

	public void setConstByName(String constByName) {
		this.constByName = constByName;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PARENT_TYPE")
	public String getParentType() {
		return this.parentType;
	}

	public void setParentType(String parentType) {
		this.parentType = parentType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByDcPurposeTypeFk")
	public Set<DeliveryChallan> getDeliveryChallansForDcPurposeTypeFk() {
		return this.deliveryChallansForDcPurposeTypeFk;
	}

	public void setDeliveryChallansForDcPurposeTypeFk(Set<DeliveryChallan> deliveryChallansForDcPurposeTypeFk) {
		this.deliveryChallansForDcPurposeTypeFk = deliveryChallansForDcPurposeTypeFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<InvoiceHeader> getInvoiceHeaders() {
		return this.invoiceHeaders;
	}

	public void setInvoiceHeaders(Set<InvoiceHeader> invoiceHeaders) {
		this.invoiceHeaders = invoiceHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<UserDetails> getUserDetailses() {
		return this.userDetailses;
	}

	public void setUserDetailses(Set<UserDetails> userDetailses) {
		this.userDetailses = userDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders() {
		return this.purchaseOrderHeaders;
	}

	public void setPurchaseOrderHeaders(Set<PurchaseOrderHeader> purchaseOrderHeaders) {
		this.purchaseOrderHeaders = purchaseOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByBuTypeFk")
	public Set<BusinessDeal> getBusinessDealsForBuTypeFk() {
		return this.businessDealsForBuTypeFk;
	}

	public void setBusinessDealsForBuTypeFk(Set<BusinessDeal> businessDealsForBuTypeFk) {
		this.businessDealsForBuTypeFk = businessDealsForBuTypeFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<InvoiceHeader> getInvoiceHeaders_1() {
		return this.invoiceHeaders_1;
	}

	public void setInvoiceHeaders_1(Set<InvoiceHeader> invoiceHeaders_1) {
		this.invoiceHeaders_1 = invoiceHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders_1() {
		return this.purchaseOrderHeaders_1;
	}

	public void setPurchaseOrderHeaders_1(Set<PurchaseOrderHeader> purchaseOrderHeaders_1) {
		this.purchaseOrderHeaders_1 = purchaseOrderHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByCrmTypeFk")
	public Set<BusinessDeal> getBusinessDealsForCrmTypeFk() {
		return this.businessDealsForCrmTypeFk;
	}

	public void setBusinessDealsForCrmTypeFk(Set<BusinessDeal> businessDealsForCrmTypeFk) {
		this.businessDealsForCrmTypeFk = businessDealsForCrmTypeFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByCrmTypeFk")
	public Set<QuoteHeader> getQuoteHeadersForCrmTypeFk() {
		return this.quoteHeadersForCrmTypeFk;
	}

	public void setQuoteHeadersForCrmTypeFk(Set<QuoteHeader> quoteHeadersForCrmTypeFk) {
		this.quoteHeadersForCrmTypeFk = quoteHeadersForCrmTypeFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<SalesOrderHeader> getSalesOrderHeaders() {
		return this.salesOrderHeaders;
	}

	public void setSalesOrderHeaders(Set<SalesOrderHeader> salesOrderHeaders) {
		this.salesOrderHeaders = salesOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByCrmTypeFk")
	public Set<BusinessDeal> getBusinessDealsForCrmTypeFk_1() {
		return this.businessDealsForCrmTypeFk_1;
	}

	public void setBusinessDealsForCrmTypeFk_1(Set<BusinessDeal> businessDealsForCrmTypeFk_1) {
		this.businessDealsForCrmTypeFk_1 = businessDealsForCrmTypeFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<GrnHeader> getGrnHeaders() {
		return this.grnHeaders;
	}

	public void setGrnHeaders(Set<GrnHeader> grnHeaders) {
		this.grnHeaders = grnHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<SalesOrderHeader> getSalesOrderHeaders_1() {
		return this.salesOrderHeaders_1;
	}

	public void setSalesOrderHeaders_1(Set<SalesOrderHeader> salesOrderHeaders_1) {
		this.salesOrderHeaders_1 = salesOrderHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<GrnHeader> getGrnHeaders_1() {
		return this.grnHeaders_1;
	}

	public void setGrnHeaders_1(Set<GrnHeader> grnHeaders_1) {
		this.grnHeaders_1 = grnHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByFreightTypeCrmFk")
	public Set<QuoteHeader> getQuoteHeadersForFreightTypeCrmFk() {
		return this.quoteHeadersForFreightTypeCrmFk;
	}

	public void setQuoteHeadersForFreightTypeCrmFk(Set<QuoteHeader> quoteHeadersForFreightTypeCrmFk) {
		this.quoteHeadersForFreightTypeCrmFk = quoteHeadersForFreightTypeCrmFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByFreightTypeCrmFk")
	public Set<QuoteHeader> getQuoteHeadersForFreightTypeCrmFk_1() {
		return this.quoteHeadersForFreightTypeCrmFk_1;
	}

	public void setQuoteHeadersForFreightTypeCrmFk_1(Set<QuoteHeader> quoteHeadersForFreightTypeCrmFk_1) {
		this.quoteHeadersForFreightTypeCrmFk_1 = quoteHeadersForFreightTypeCrmFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByDcTypeFk")
	public Set<DeliveryChallan> getDeliveryChallansForDcTypeFk() {
		return this.deliveryChallansForDcTypeFk;
	}

	public void setDeliveryChallansForDcTypeFk(Set<DeliveryChallan> deliveryChallansForDcTypeFk) {
		this.deliveryChallansForDcTypeFk = deliveryChallansForDcTypeFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByBuTypeFk")
	public Set<BusinessDeal> getBusinessDealsForBuTypeFk_1() {
		return this.businessDealsForBuTypeFk_1;
	}

	public void setBusinessDealsForBuTypeFk_1(Set<BusinessDeal> businessDealsForBuTypeFk_1) {
		this.businessDealsForBuTypeFk_1 = businessDealsForBuTypeFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByDcTypeFk")
	public Set<DeliveryChallan> getDeliveryChallansForDcTypeFk_1() {
		return this.deliveryChallansForDcTypeFk_1;
	}

	public void setDeliveryChallansForDcTypeFk_1(Set<DeliveryChallan> deliveryChallansForDcTypeFk_1) {
		this.deliveryChallansForDcTypeFk_1 = deliveryChallansForDcTypeFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByDcPurposeTypeFk")
	public Set<DeliveryChallan> getDeliveryChallansForDcPurposeTypeFk_1() {
		return this.deliveryChallansForDcPurposeTypeFk_1;
	}

	public void setDeliveryChallansForDcPurposeTypeFk_1(Set<DeliveryChallan> deliveryChallansForDcPurposeTypeFk_1) {
		this.deliveryChallansForDcPurposeTypeFk_1 = deliveryChallansForDcPurposeTypeFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByCrmTypeFk")
	public Set<QuoteHeader> getQuoteHeadersForCrmTypeFk_1() {
		return this.quoteHeadersForCrmTypeFk_1;
	}

	public void setQuoteHeadersForCrmTypeFk_1(Set<QuoteHeader> quoteHeadersForCrmTypeFk_1) {
		this.quoteHeadersForCrmTypeFk_1 = quoteHeadersForCrmTypeFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<UserDetails> getUserDetailses_1() {
		return this.userDetailses_1;
	}

	public void setUserDetailses_1(Set<UserDetails> userDetailses_1) {
		this.userDetailses_1 = userDetailses_1;
	}

}
