package com.connectivity.vikray.model;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FinancialReport generated by hbm2java
 */
@Entity
@Table(name = "FINANCIAL_REPORT", catalog = "namcrm")
public class FinancialReport implements java.io.Serializable {

	private long id;
	private Domain domain;
	private Organisation organisation;
	private SalesOrderHeader salesOrderHeader;
	private UserDetails userDetails;
	private String accManager;
	private String customerName;
	private String org;
	private String sosName;
	private String guid;
	private Date createdDate;
	private Set<Payable> payables = new HashSet<Payable>(0);
	private Set<Payable> payables_1 = new HashSet<Payable>(0);
	private Set<Recievable> recievables = new HashSet<Recievable>(0);
	private Set<Recievable> recievables_1 = new HashSet<Recievable>(0);

	public FinancialReport() {
	}

	public FinancialReport(long id) {
		this.id = id;
	}

	public FinancialReport(long id, Domain domain, Organisation organisation, SalesOrderHeader salesOrderHeader,
			UserDetails userDetails, String accManager, String customerName, String org, String sosName, String guid,
			Date createdDate, Set<Payable> payables, Set<Payable> payables_1, Set<Recievable> recievables,
			Set<Recievable> recievables_1) {
		this.id = id;
		this.domain = domain;
		this.organisation = organisation;
		this.salesOrderHeader = salesOrderHeader;
		this.userDetails = userDetails;
		this.accManager = accManager;
		this.customerName = customerName;
		this.org = org;
		this.sosName = sosName;
		this.guid = guid;
		this.createdDate = createdDate;
		this.payables = payables;
		this.payables_1 = payables_1;
		this.recievables = recievables;
		this.recievables_1 = recievables_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN_FK")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORGANISATION_FK")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SALES_ORDER_FK")
	public SalesOrderHeader getSalesOrderHeader() {
		return this.salesOrderHeader;
	}

	public void setSalesOrderHeader(SalesOrderHeader salesOrderHeader) {
		this.salesOrderHeader = salesOrderHeader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACC_MGR_FK")
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "ACC_MANAGER")
	public String getAccManager() {
		return this.accManager;
	}

	public void setAccManager(String accManager) {
		this.accManager = accManager;
	}

	@Column(name = "CUSTOMER_NAME")
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "ORG")
	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	@Column(name = "SOS_NAME")
	public String getSosName() {
		return this.sosName;
	}

	public void setSosName(String sosName) {
		this.sosName = sosName;
	}

	@Column(name = "GUID")
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialReport")
	public Set<Payable> getPayables() {
		return this.payables;
	}

	public void setPayables(Set<Payable> payables) {
		this.payables = payables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialReport")
	public Set<Payable> getPayables_1() {
		return this.payables_1;
	}

	public void setPayables_1(Set<Payable> payables_1) {
		this.payables_1 = payables_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialReport")
	public Set<Recievable> getRecievables() {
		return this.recievables;
	}

	public void setRecievables(Set<Recievable> recievables) {
		this.recievables = recievables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialReport")
	public Set<Recievable> getRecievables_1() {
		return this.recievables_1;
	}

	public void setRecievables_1(Set<Recievable> recievables_1) {
		this.recievables_1 = recievables_1;
	}

}
