package com.connectivity.vikray.model;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GrnItem generated by hbm2java
 */
@Entity
@Table(name = "GRN_ITEM", catalog = "namcrm")
public class GrnItem implements java.io.Serializable {

	private long id;
	private GrnHeader grnHeader;
	private InventoryItem inventoryItem;
	private OrderItem orderItem;
	private PurchaseEntry purchaseEntry;
	private Warehouse warehouse;
	private int acceptedQuantity;
	private String amount;
	private String itemDescription;
	private String itemName;
	private double priceWithTax;
	private int recievedQuantity;
	private int rejectedQuantity;
	private double taxAmount;
	private double taxPercentage;
	private double unitPrice;
	private String uom;
	private String slNo;
	private String productSerialNo;
	private double sgstRate;
	private double igstRate;
	private double cgstRate;
	private double cgstAmount;
	private double igstAmount;
	private double sgstAmount;
	private boolean isServiceItem;

	public GrnItem() {
	}

	public GrnItem(long id, int acceptedQuantity, double priceWithTax, int recievedQuantity, int rejectedQuantity,
			double taxAmount, double taxPercentage, double unitPrice, double sgstRate, double igstRate, double cgstRate,
			double cgstAmount, double igstAmount, double sgstAmount, boolean isServiceItem) {
		this.id = id;
		this.acceptedQuantity = acceptedQuantity;
		this.priceWithTax = priceWithTax;
		this.recievedQuantity = recievedQuantity;
		this.rejectedQuantity = rejectedQuantity;
		this.taxAmount = taxAmount;
		this.taxPercentage = taxPercentage;
		this.unitPrice = unitPrice;
		this.sgstRate = sgstRate;
		this.igstRate = igstRate;
		this.cgstRate = cgstRate;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.sgstAmount = sgstAmount;
		this.isServiceItem = isServiceItem;
	}

	public GrnItem(long id, GrnHeader grnHeader, InventoryItem inventoryItem, OrderItem orderItem,
			PurchaseEntry purchaseEntry, Warehouse warehouse, int acceptedQuantity, String amount,
			String itemDescription, String itemName, double priceWithTax, int recievedQuantity, int rejectedQuantity,
			double taxAmount, double taxPercentage, double unitPrice, String uom, String slNo, String productSerialNo,
			double sgstRate, double igstRate, double cgstRate, double cgstAmount, double igstAmount, double sgstAmount,
			boolean isServiceItem) {
		this.id = id;
		this.grnHeader = grnHeader;
		this.inventoryItem = inventoryItem;
		this.orderItem = orderItem;
		this.purchaseEntry = purchaseEntry;
		this.warehouse = warehouse;
		this.acceptedQuantity = acceptedQuantity;
		this.amount = amount;
		this.itemDescription = itemDescription;
		this.itemName = itemName;
		this.priceWithTax = priceWithTax;
		this.recievedQuantity = recievedQuantity;
		this.rejectedQuantity = rejectedQuantity;
		this.taxAmount = taxAmount;
		this.taxPercentage = taxPercentage;
		this.unitPrice = unitPrice;
		this.uom = uom;
		this.slNo = slNo;
		this.productSerialNo = productSerialNo;
		this.sgstRate = sgstRate;
		this.igstRate = igstRate;
		this.cgstRate = cgstRate;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.sgstAmount = sgstAmount;
		this.isServiceItem = isServiceItem;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GOODS_RECEIPT_NOTE_HEADER_FK")
	public GrnHeader getGrnHeader() {
		return this.grnHeader;
	}

	public void setGrnHeader(GrnHeader grnHeader) {
		this.grnHeader = grnHeader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVENTORY_ITEM_FK")
	public InventoryItem getInventoryItem() {
		return this.inventoryItem;
	}

	public void setInventoryItem(InventoryItem inventoryItem) {
		this.inventoryItem = inventoryItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ITEM_FK")
	public OrderItem getOrderItem() {
		return this.orderItem;
	}

	public void setOrderItem(OrderItem orderItem) {
		this.orderItem = orderItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PURCHASE_ENTRY_FK")
	public PurchaseEntry getPurchaseEntry() {
		return this.purchaseEntry;
	}

	public void setPurchaseEntry(PurchaseEntry purchaseEntry) {
		this.purchaseEntry = purchaseEntry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WAREHOUSE_ID_OID")
	public Warehouse getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	@Column(name = "ACCEPTED_QUANTITY", nullable = false)
	public int getAcceptedQuantity() {
		return this.acceptedQuantity;
	}

	public void setAcceptedQuantity(int acceptedQuantity) {
		this.acceptedQuantity = acceptedQuantity;
	}

	@Column(name = "AMOUNT")
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Column(name = "ITEM_DESCRIPTION", length = 16777215)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "ITEM_NAME")
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "PRICE_WITH_TAX", nullable = false, precision = 22, scale = 0)
	public double getPriceWithTax() {
		return this.priceWithTax;
	}

	public void setPriceWithTax(double priceWithTax) {
		this.priceWithTax = priceWithTax;
	}

	@Column(name = "RECIEVED_QUANTITY", nullable = false)
	public int getRecievedQuantity() {
		return this.recievedQuantity;
	}

	public void setRecievedQuantity(int recievedQuantity) {
		this.recievedQuantity = recievedQuantity;
	}

	@Column(name = "REJECTED_QUANTITY", nullable = false)
	public int getRejectedQuantity() {
		return this.rejectedQuantity;
	}

	public void setRejectedQuantity(int rejectedQuantity) {
		this.rejectedQuantity = rejectedQuantity;
	}

	@Column(name = "TAX_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(double taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "TAX_PERCENTAGE", nullable = false, precision = 22, scale = 0)
	public double getTaxPercentage() {
		return this.taxPercentage;
	}

	public void setTaxPercentage(double taxPercentage) {
		this.taxPercentage = taxPercentage;
	}

	@Column(name = "UNIT_PRICE", nullable = false, precision = 22, scale = 0)
	public double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(double unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "UOM")
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	@Column(name = "SL_NO")
	public String getSlNo() {
		return this.slNo;
	}

	public void setSlNo(String slNo) {
		this.slNo = slNo;
	}

	@Column(name = "PRODUCT_SERIAL_NO")
	public String getProductSerialNo() {
		return this.productSerialNo;
	}

	public void setProductSerialNo(String productSerialNo) {
		this.productSerialNo = productSerialNo;
	}

	@Column(name = "SGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getSgstRate() {
		return this.sgstRate;
	}

	public void setSgstRate(double sgstRate) {
		this.sgstRate = sgstRate;
	}

	@Column(name = "IGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getIgstRate() {
		return this.igstRate;
	}

	public void setIgstRate(double igstRate) {
		this.igstRate = igstRate;
	}

	@Column(name = "CGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getCgstRate() {
		return this.cgstRate;
	}

	public void setCgstRate(double cgstRate) {
		this.cgstRate = cgstRate;
	}

	@Column(name = "CGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getCgstAmount() {
		return this.cgstAmount;
	}

	public void setCgstAmount(double cgstAmount) {
		this.cgstAmount = cgstAmount;
	}

	@Column(name = "IGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getIgstAmount() {
		return this.igstAmount;
	}

	public void setIgstAmount(double igstAmount) {
		this.igstAmount = igstAmount;
	}

	@Column(name = "SGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getSgstAmount() {
		return this.sgstAmount;
	}

	public void setSgstAmount(double sgstAmount) {
		this.sgstAmount = sgstAmount;
	}

	@Column(name = "IS_SERVICE_ITEM", nullable = false)
	public boolean isIsServiceItem() {
		return this.isServiceItem;
	}

	public void setIsServiceItem(boolean isServiceItem) {
		this.isServiceItem = isServiceItem;
	}

}
