package com.connectivity.vikray.model;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InvoiceItem generated by hbm2java
 */
@Entity
@Table(name = "INVOICE_ITEM", catalog = "namcrm")
public class InvoiceItem implements java.io.Serializable {

	private long id;
	private InventoryItem inventoryItem;
	private InvoiceHeader invoiceHeader;
	private QuoteItem quoteItem;
	private double extendedPrice;
	private boolean isServiceItem;
	private String itemDescription;
	private String itemName;
	private double outGoingUnitPrice;
	private double priceWithTax;
	private int quantity;
	private double taxAmount;
	private double taxPercentage;
	private String taxType;
	private String uom;
	private String slNo;
	private String productSerialNo;
	private double sgstRate;
	private double igstRate;
	private double cgstRate;
	private String hsnCode;
	private double cgstAmount;
	private double igstAmount;
	private double sgstAmount;
	private byte[] listofitem;
	private double discount;
	private Integer recievedQty;
	private Set<QuoteItem> quoteItems = new HashSet<QuoteItem>(0);
	private Set<QuoteItem> quoteItems_1 = new HashSet<QuoteItem>(0);

	public InvoiceItem() {
	}

	public InvoiceItem(long id, double extendedPrice, boolean isServiceItem, double outGoingUnitPrice,
			double priceWithTax, int quantity, double taxAmount, double taxPercentage, double sgstRate, double igstRate,
			double cgstRate, double cgstAmount, double igstAmount, double sgstAmount, double discount) {
		this.id = id;
		this.extendedPrice = extendedPrice;
		this.isServiceItem = isServiceItem;
		this.outGoingUnitPrice = outGoingUnitPrice;
		this.priceWithTax = priceWithTax;
		this.quantity = quantity;
		this.taxAmount = taxAmount;
		this.taxPercentage = taxPercentage;
		this.sgstRate = sgstRate;
		this.igstRate = igstRate;
		this.cgstRate = cgstRate;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.sgstAmount = sgstAmount;
		this.discount = discount;
	}

	public InvoiceItem(long id, InventoryItem inventoryItem, InvoiceHeader invoiceHeader, QuoteItem quoteItem,
			double extendedPrice, boolean isServiceItem, String itemDescription, String itemName,
			double outGoingUnitPrice, double priceWithTax, int quantity, double taxAmount, double taxPercentage,
			String taxType, String uom, String slNo, String productSerialNo, double sgstRate, double igstRate,
			double cgstRate, String hsnCode, double cgstAmount, double igstAmount, double sgstAmount, byte[] listofitem,
			double discount, Integer recievedQty, Set<QuoteItem> quoteItems, Set<QuoteItem> quoteItems_1) {
		this.id = id;
		this.inventoryItem = inventoryItem;
		this.invoiceHeader = invoiceHeader;
		this.quoteItem = quoteItem;
		this.extendedPrice = extendedPrice;
		this.isServiceItem = isServiceItem;
		this.itemDescription = itemDescription;
		this.itemName = itemName;
		this.outGoingUnitPrice = outGoingUnitPrice;
		this.priceWithTax = priceWithTax;
		this.quantity = quantity;
		this.taxAmount = taxAmount;
		this.taxPercentage = taxPercentage;
		this.taxType = taxType;
		this.uom = uom;
		this.slNo = slNo;
		this.productSerialNo = productSerialNo;
		this.sgstRate = sgstRate;
		this.igstRate = igstRate;
		this.cgstRate = cgstRate;
		this.hsnCode = hsnCode;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.sgstAmount = sgstAmount;
		this.listofitem = listofitem;
		this.discount = discount;
		this.recievedQty = recievedQty;
		this.quoteItems = quoteItems;
		this.quoteItems_1 = quoteItems_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVENTORY_ITEM_FK")
	public InventoryItem getInventoryItem() {
		return this.inventoryItem;
	}

	public void setInventoryItem(InventoryItem inventoryItem) {
		this.inventoryItem = inventoryItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVOICE_FK")
	public InvoiceHeader getInvoiceHeader() {
		return this.invoiceHeader;
	}

	public void setInvoiceHeader(InvoiceHeader invoiceHeader) {
		this.invoiceHeader = invoiceHeader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUOTE_ITEM_FK")
	public QuoteItem getQuoteItem() {
		return this.quoteItem;
	}

	public void setQuoteItem(QuoteItem quoteItem) {
		this.quoteItem = quoteItem;
	}

	@Column(name = "EXTENDED_PRICE", nullable = false, precision = 22, scale = 0)
	public double getExtendedPrice() {
		return this.extendedPrice;
	}

	public void setExtendedPrice(double extendedPrice) {
		this.extendedPrice = extendedPrice;
	}

	@Column(name = "IS_SERVICE_ITEM", nullable = false)
	public boolean isIsServiceItem() {
		return this.isServiceItem;
	}

	public void setIsServiceItem(boolean isServiceItem) {
		this.isServiceItem = isServiceItem;
	}

	@Column(name = "ITEM_DESCRIPTION", length = 16777215)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "ITEM_NAME")
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "OUT_GOING_UNIT_PRICE", nullable = false, precision = 22, scale = 0)
	public double getOutGoingUnitPrice() {
		return this.outGoingUnitPrice;
	}

	public void setOutGoingUnitPrice(double outGoingUnitPrice) {
		this.outGoingUnitPrice = outGoingUnitPrice;
	}

	@Column(name = "PRICE_WITH_TAX", nullable = false, precision = 22, scale = 0)
	public double getPriceWithTax() {
		return this.priceWithTax;
	}

	public void setPriceWithTax(double priceWithTax) {
		this.priceWithTax = priceWithTax;
	}

	@Column(name = "QUANTITY", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "TAX_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(double taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "TAX_PERCENTAGE", nullable = false, precision = 22, scale = 0)
	public double getTaxPercentage() {
		return this.taxPercentage;
	}

	public void setTaxPercentage(double taxPercentage) {
		this.taxPercentage = taxPercentage;
	}

	@Column(name = "TAX_TYPE")
	public String getTaxType() {
		return this.taxType;
	}

	public void setTaxType(String taxType) {
		this.taxType = taxType;
	}

	@Column(name = "UOM")
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	@Column(name = "SL_NO")
	public String getSlNo() {
		return this.slNo;
	}

	public void setSlNo(String slNo) {
		this.slNo = slNo;
	}

	@Column(name = "PRODUCT_SERIAL_NO", length = 16777215)
	public String getProductSerialNo() {
		return this.productSerialNo;
	}

	public void setProductSerialNo(String productSerialNo) {
		this.productSerialNo = productSerialNo;
	}

	@Column(name = "SGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getSgstRate() {
		return this.sgstRate;
	}

	public void setSgstRate(double sgstRate) {
		this.sgstRate = sgstRate;
	}

	@Column(name = "IGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getIgstRate() {
		return this.igstRate;
	}

	public void setIgstRate(double igstRate) {
		this.igstRate = igstRate;
	}

	@Column(name = "CGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getCgstRate() {
		return this.cgstRate;
	}

	public void setCgstRate(double cgstRate) {
		this.cgstRate = cgstRate;
	}

	@Column(name = "HSN_CODE")
	public String getHsnCode() {
		return this.hsnCode;
	}

	public void setHsnCode(String hsnCode) {
		this.hsnCode = hsnCode;
	}

	@Column(name = "CGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getCgstAmount() {
		return this.cgstAmount;
	}

	public void setCgstAmount(double cgstAmount) {
		this.cgstAmount = cgstAmount;
	}

	@Column(name = "IGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getIgstAmount() {
		return this.igstAmount;
	}

	public void setIgstAmount(double igstAmount) {
		this.igstAmount = igstAmount;
	}

	@Column(name = "SGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getSgstAmount() {
		return this.sgstAmount;
	}

	public void setSgstAmount(double sgstAmount) {
		this.sgstAmount = sgstAmount;
	}

	@Column(name = "LISTOFITEM")
	public byte[] getListofitem() {
		return this.listofitem;
	}

	public void setListofitem(byte[] listofitem) {
		this.listofitem = listofitem;
	}

	@Column(name = "DISCOUNT", nullable = false, precision = 22, scale = 0)
	public double getDiscount() {
		return this.discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	@Column(name = "RECIEVED_QTY")
	public Integer getRecievedQty() {
		return this.recievedQty;
	}

	public void setRecievedQty(Integer recievedQty) {
		this.recievedQty = recievedQty;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoiceItem")
	public Set<QuoteItem> getQuoteItems() {
		return this.quoteItems;
	}

	public void setQuoteItems(Set<QuoteItem> quoteItems) {
		this.quoteItems = quoteItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoiceItem")
	public Set<QuoteItem> getQuoteItems_1() {
		return this.quoteItems_1;
	}

	public void setQuoteItems_1(Set<QuoteItem> quoteItems_1) {
		this.quoteItems_1 = quoteItems_1;
	}

}
