package com.connectivity.vikray.model;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrganisationAddress generated by hbm2java
 */
@Entity
@Table(name = "ORGANISATION_ADDRESS", catalog = "namcrm")
public class OrganisationAddress implements java.io.Serializable {

	private long id;
	private Organisation organisation;
	private OrgLocation orgLocation;
	private String addressLine1;
	private String addressLine2;
	private String addressType;
	private String city;
	private String country;
	private boolean isDefault;
	private String locationId;
	private String state;
	private String zipcode;
	private Set<PurchaseOrderHeader> purchaseOrderHeaders = new HashSet<PurchaseOrderHeader>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders_1 = new HashSet<PurchaseOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallans = new HashSet<DeliveryChallan>(0);
	private Set<DeliveryChallan> deliveryChallans_1 = new HashSet<DeliveryChallan>(0);
	private Set<PurchaseEntry> purchaseEntries = new HashSet<PurchaseEntry>(0);
	private Set<PurchaseEntry> purchaseEntries_1 = new HashSet<PurchaseEntry>(0);

	public OrganisationAddress() {
	}

	public OrganisationAddress(long id, boolean isDefault) {
		this.id = id;
		this.isDefault = isDefault;
	}

	public OrganisationAddress(long id, Organisation organisation, OrgLocation orgLocation, String addressLine1,
			String addressLine2, String addressType, String city, String country, boolean isDefault, String locationId,
			String state, String zipcode, Set<PurchaseOrderHeader> purchaseOrderHeaders,
			Set<PurchaseOrderHeader> purchaseOrderHeaders_1, Set<DeliveryChallan> deliveryChallans,
			Set<DeliveryChallan> deliveryChallans_1, Set<PurchaseEntry> purchaseEntries,
			Set<PurchaseEntry> purchaseEntries_1) {
		this.id = id;
		this.organisation = organisation;
		this.orgLocation = orgLocation;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressType = addressType;
		this.city = city;
		this.country = country;
		this.isDefault = isDefault;
		this.locationId = locationId;
		this.state = state;
		this.zipcode = zipcode;
		this.purchaseOrderHeaders = purchaseOrderHeaders;
		this.purchaseOrderHeaders_1 = purchaseOrderHeaders_1;
		this.deliveryChallans = deliveryChallans;
		this.deliveryChallans_1 = deliveryChallans_1;
		this.purchaseEntries = purchaseEntries;
		this.purchaseEntries_1 = purchaseEntries_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORGANISATION_FK")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORG_LOCATION_FK")
	public OrgLocation getOrgLocation() {
		return this.orgLocation;
	}

	public void setOrgLocation(OrgLocation orgLocation) {
		this.orgLocation = orgLocation;
	}

	@Column(name = "ADDRESS_LINE1")
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE2")
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "ADDRESS_TYPE")
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "CITY")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "COUNTRY")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "IS_DEFAULT", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "LOCATION_ID")
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	@Column(name = "STATE")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIPCODE")
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisationAddress")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders() {
		return this.purchaseOrderHeaders;
	}

	public void setPurchaseOrderHeaders(Set<PurchaseOrderHeader> purchaseOrderHeaders) {
		this.purchaseOrderHeaders = purchaseOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisationAddress")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders_1() {
		return this.purchaseOrderHeaders_1;
	}

	public void setPurchaseOrderHeaders_1(Set<PurchaseOrderHeader> purchaseOrderHeaders_1) {
		this.purchaseOrderHeaders_1 = purchaseOrderHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisationAddress")
	public Set<DeliveryChallan> getDeliveryChallans() {
		return this.deliveryChallans;
	}

	public void setDeliveryChallans(Set<DeliveryChallan> deliveryChallans) {
		this.deliveryChallans = deliveryChallans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisationAddress")
	public Set<DeliveryChallan> getDeliveryChallans_1() {
		return this.deliveryChallans_1;
	}

	public void setDeliveryChallans_1(Set<DeliveryChallan> deliveryChallans_1) {
		this.deliveryChallans_1 = deliveryChallans_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisationAddress")
	public Set<PurchaseEntry> getPurchaseEntries() {
		return this.purchaseEntries;
	}

	public void setPurchaseEntries(Set<PurchaseEntry> purchaseEntries) {
		this.purchaseEntries = purchaseEntries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisationAddress")
	public Set<PurchaseEntry> getPurchaseEntries_1() {
		return this.purchaseEntries_1;
	}

	public void setPurchaseEntries_1(Set<PurchaseEntry> purchaseEntries_1) {
		this.purchaseEntries_1 = purchaseEntries_1;
	}

}
