package com.connectivity.vikray.model;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "USER_DETAILS", catalog = "namcrm")
public class UserDetails implements java.io.Serializable {

	private long id;
	private CrmType crmType;
	private Domain domain;
	private Organisation organisation;
	private OrgLocation orgLocation;
	private UserDetails userDetails;
	private String dotPath;
	private String firstName;
	private String forgotPassGuid;
	private String guid;
	private String inviteGuid;
	private String lastName;
	private String userLoginId;
	private String password;
	private String sessionId;
	private String userEmail;
	private String userPhone;
	private long userRole;
	private double salesTarget;
	private boolean isInactive;
	private long expertise;
	private String accessToken;
	private Set<QuoteHeader> quoteHeadersForCreatedByUserFk = new HashSet<QuoteHeader>(0);
	private Set<QuoteHeader> quoteHeadersForLastModifiedUserFk = new HashSet<QuoteHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForLastModifiedByUserFk = new HashSet<DeliveryChallan>(0);
	private Set<GrnHeader> grnHeadersForCreatedByUserFk = new HashSet<GrnHeader>(0);
	private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);
	private Set<BusinessDeal> businessDealsForCreatedBy = new HashSet<BusinessDeal>(0);
	private Set<Warehouse> warehouses = new HashSet<Warehouse>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeadersForCreatedBy = new HashSet<PurchaseOrderHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForCreatedByUserFk = new HashSet<SalesOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForCreatedByUserFk = new HashSet<DeliveryChallan>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeadersForLastModifiedBy = new HashSet<PurchaseOrderHeader>(0);
	private Set<GrnHeader> grnHeadersForLastModifiedByUserFk = new HashSet<GrnHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForCreatedByUserFk_1 = new HashSet<DeliveryChallan>(0);
	private Set<Task> tasksForCreatorUserFk = new HashSet<Task>(0);
	private Set<InvoiceHeader> invoiceHeadersForCreatedBy = new HashSet<InvoiceHeader>(0);
	private Set<Task> tasksForAssigneeUserFk = new HashSet<Task>(0);
	private Set<Task> tasksForCreatorUserFk_1 = new HashSet<Task>(0);
	private Set<AccountDetail> accountDetails = new HashSet<AccountDetail>(0);
	private Set<BusinessDeal> businessDealsForLastModifiedBy = new HashSet<BusinessDeal>(0);
	private Set<FinancialReport> financialReports = new HashSet<FinancialReport>(0);
	private Set<BusinessDeal> businessDealsForSponsorUserFk = new HashSet<BusinessDeal>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForCreatedByUserFk_1 = new HashSet<SalesOrderHeader>(0);
	private Set<QuoteHeader> quoteHeadersForLastModifiedUserFk_1 = new HashSet<QuoteHeader>(0);
	private Set<AccountActivity> accountActivities = new HashSet<AccountActivity>(0);
	private Set<FinancialReport> financialReports_1 = new HashSet<FinancialReport>(0);
	private Set<DealActivity> dealActivities = new HashSet<DealActivity>(0);
	private Set<QuoteHeader> quoteHeadersForCreatedByUserFk_1 = new HashSet<QuoteHeader>(0);
	private Set<Warehouse> warehouses_1 = new HashSet<Warehouse>(0);
	private Set<BusinessDeal> businessDealsForLastModifiedBy_1 = new HashSet<BusinessDeal>(0);
	private Set<BusinessDeal> businessDealsForSponsorUserFk_1 = new HashSet<BusinessDeal>(0);
	private Set<BusinessDeal> businessDealsForCreatedBy_1 = new HashSet<BusinessDeal>(0);
	private Set<PurchaseEntry> purchaseEntriesForLastModifiedByUserFk = new HashSet<PurchaseEntry>(0);
	private Set<PurchaseEntry> purchaseEntriesForCreatedBy = new HashSet<PurchaseEntry>(0);
	private Set<Product> productsForLastModifiedByUserFk = new HashSet<Product>(0);
	private Set<AccountDetail> accountDetails_1 = new HashSet<AccountDetail>(0);
	private Set<GrnHeader> grnHeadersForLastModifiedByUserFk_1 = new HashSet<GrnHeader>(0);
	private Set<BusinessDeal> businessDealsForOwnerFk = new HashSet<BusinessDeal>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForOwnerFk = new HashSet<SalesOrderHeader>(0);
	private Set<PurchaseEntry> purchaseEntriesForCreatedBy_1 = new HashSet<PurchaseEntry>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeadersForCreatedBy_1 = new HashSet<PurchaseOrderHeader>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeadersForLastModifiedBy_1 = new HashSet<PurchaseOrderHeader>(0);
	private Set<InventoryItem> inventoryItemsForCreatedByUserFk = new HashSet<InventoryItem>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForLastModifiedByUserFk = new HashSet<SalesOrderHeader>(0);
	private Set<Product> productsForCreatedByUserFk = new HashSet<Product>(0);
	private Set<InventoryItem> inventoryItemsForLastModifiedByUserFk = new HashSet<InventoryItem>(0);
	private Set<InvoiceHeader> invoiceHeadersForLastModifiedBy = new HashSet<InvoiceHeader>(0);
	private Set<Product> productsForLastModifiedByUserFk_1 = new HashSet<Product>(0);
	private Set<Task> tasksForAssigneeUserFk_1 = new HashSet<Task>(0);
	private Set<DeliveryChallan> deliveryChallansForLastModifiedByUserFk_1 = new HashSet<DeliveryChallan>(0);
	private Set<BusinessDeal> businessDealsForOwnerFk_1 = new HashSet<BusinessDeal>(0);
	private Set<Product> productsForCreatedByUserFk_1 = new HashSet<Product>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForOwnerFk_1 = new HashSet<SalesOrderHeader>(0);
	private Set<AccountActivity> accountActivities_1 = new HashSet<AccountActivity>(0);
	private Set<GrnHeader> grnHeadersForCreatedByUserFk_1 = new HashSet<GrnHeader>(0);
	private Set<InventoryItem> inventoryItemsForCreatedByUserFk_1 = new HashSet<InventoryItem>(0);
	private Set<PurchaseEntry> purchaseEntriesForLastModifiedByUserFk_1 = new HashSet<PurchaseEntry>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForLastModifiedByUserFk_1 = new HashSet<SalesOrderHeader>(0);
	private Set<InvoiceHeader> invoiceHeadersForLastModifiedBy_1 = new HashSet<InvoiceHeader>(0);
	private Set<InvoiceHeader> invoiceHeadersForCreatedBy_1 = new HashSet<InvoiceHeader>(0);
	private Set<DealActivity> dealActivities_1 = new HashSet<DealActivity>(0);
	private Set<UserDetails> userDetailses_1 = new HashSet<UserDetails>(0);
	private Set<InventoryItem> inventoryItemsForLastModifiedByUserFk_1 = new HashSet<InventoryItem>(0);

	public UserDetails() {
	}

	public UserDetails(long id, long userRole, double salesTarget, boolean isInactive, long expertise) {
		this.id = id;
		this.userRole = userRole;
		this.salesTarget = salesTarget;
		this.isInactive = isInactive;
		this.expertise = expertise;
	}

	public UserDetails(long id, CrmType crmType, Domain domain, Organisation organisation, OrgLocation orgLocation,
			UserDetails userDetails, String dotPath, String firstName, String forgotPassGuid, String guid,
			String inviteGuid, String lastName, String userLoginId, String password, String sessionId, String userEmail,
			String userPhone, long userRole, double salesTarget, boolean isInactive, long expertise, String accessToken,
			Set<QuoteHeader> quoteHeadersForCreatedByUserFk, Set<QuoteHeader> quoteHeadersForLastModifiedUserFk,
			Set<DeliveryChallan> deliveryChallansForLastModifiedByUserFk, Set<GrnHeader> grnHeadersForCreatedByUserFk,
			Set<UserDetails> userDetailses, Set<BusinessDeal> businessDealsForCreatedBy, Set<Warehouse> warehouses,
			Set<PurchaseOrderHeader> purchaseOrderHeadersForCreatedBy,
			Set<SalesOrderHeader> salesOrderHeadersForCreatedByUserFk,
			Set<DeliveryChallan> deliveryChallansForCreatedByUserFk,
			Set<PurchaseOrderHeader> purchaseOrderHeadersForLastModifiedBy,
			Set<GrnHeader> grnHeadersForLastModifiedByUserFk, Set<DeliveryChallan> deliveryChallansForCreatedByUserFk_1,
			Set<Task> tasksForCreatorUserFk, Set<InvoiceHeader> invoiceHeadersForCreatedBy,
			Set<Task> tasksForAssigneeUserFk, Set<Task> tasksForCreatorUserFk_1, Set<AccountDetail> accountDetails,
			Set<BusinessDeal> businessDealsForLastModifiedBy, Set<FinancialReport> financialReports,
			Set<BusinessDeal> businessDealsForSponsorUserFk,
			Set<SalesOrderHeader> salesOrderHeadersForCreatedByUserFk_1,
			Set<QuoteHeader> quoteHeadersForLastModifiedUserFk_1, Set<AccountActivity> accountActivities,
			Set<FinancialReport> financialReports_1, Set<DealActivity> dealActivities,
			Set<QuoteHeader> quoteHeadersForCreatedByUserFk_1, Set<Warehouse> warehouses_1,
			Set<BusinessDeal> businessDealsForLastModifiedBy_1, Set<BusinessDeal> businessDealsForSponsorUserFk_1,
			Set<BusinessDeal> businessDealsForCreatedBy_1, Set<PurchaseEntry> purchaseEntriesForLastModifiedByUserFk,
			Set<PurchaseEntry> purchaseEntriesForCreatedBy, Set<Product> productsForLastModifiedByUserFk,
			Set<AccountDetail> accountDetails_1, Set<GrnHeader> grnHeadersForLastModifiedByUserFk_1,
			Set<BusinessDeal> businessDealsForOwnerFk, Set<SalesOrderHeader> salesOrderHeadersForOwnerFk,
			Set<PurchaseEntry> purchaseEntriesForCreatedBy_1,
			Set<PurchaseOrderHeader> purchaseOrderHeadersForCreatedBy_1,
			Set<PurchaseOrderHeader> purchaseOrderHeadersForLastModifiedBy_1,
			Set<InventoryItem> inventoryItemsForCreatedByUserFk,
			Set<SalesOrderHeader> salesOrderHeadersForLastModifiedByUserFk, Set<Product> productsForCreatedByUserFk,
			Set<InventoryItem> inventoryItemsForLastModifiedByUserFk,
			Set<InvoiceHeader> invoiceHeadersForLastModifiedBy, Set<Product> productsForLastModifiedByUserFk_1,
			Set<Task> tasksForAssigneeUserFk_1, Set<DeliveryChallan> deliveryChallansForLastModifiedByUserFk_1,
			Set<BusinessDeal> businessDealsForOwnerFk_1, Set<Product> productsForCreatedByUserFk_1,
			Set<SalesOrderHeader> salesOrderHeadersForOwnerFk_1, Set<AccountActivity> accountActivities_1,
			Set<GrnHeader> grnHeadersForCreatedByUserFk_1, Set<InventoryItem> inventoryItemsForCreatedByUserFk_1,
			Set<PurchaseEntry> purchaseEntriesForLastModifiedByUserFk_1,
			Set<SalesOrderHeader> salesOrderHeadersForLastModifiedByUserFk_1,
			Set<InvoiceHeader> invoiceHeadersForLastModifiedBy_1, Set<InvoiceHeader> invoiceHeadersForCreatedBy_1,
			Set<DealActivity> dealActivities_1, Set<UserDetails> userDetailses_1,
			Set<InventoryItem> inventoryItemsForLastModifiedByUserFk_1) {
		this.id = id;
		this.crmType = crmType;
		this.domain = domain;
		this.organisation = organisation;
		this.orgLocation = orgLocation;
		this.userDetails = userDetails;
		this.dotPath = dotPath;
		this.firstName = firstName;
		this.forgotPassGuid = forgotPassGuid;
		this.guid = guid;
		this.inviteGuid = inviteGuid;
		this.lastName = lastName;
		this.userLoginId = userLoginId;
		this.password = password;
		this.sessionId = sessionId;
		this.userEmail = userEmail;
		this.userPhone = userPhone;
		this.userRole = userRole;
		this.salesTarget = salesTarget;
		this.isInactive = isInactive;
		this.expertise = expertise;
		this.accessToken = accessToken;
		this.quoteHeadersForCreatedByUserFk = quoteHeadersForCreatedByUserFk;
		this.quoteHeadersForLastModifiedUserFk = quoteHeadersForLastModifiedUserFk;
		this.deliveryChallansForLastModifiedByUserFk = deliveryChallansForLastModifiedByUserFk;
		this.grnHeadersForCreatedByUserFk = grnHeadersForCreatedByUserFk;
		this.userDetailses = userDetailses;
		this.businessDealsForCreatedBy = businessDealsForCreatedBy;
		this.warehouses = warehouses;
		this.purchaseOrderHeadersForCreatedBy = purchaseOrderHeadersForCreatedBy;
		this.salesOrderHeadersForCreatedByUserFk = salesOrderHeadersForCreatedByUserFk;
		this.deliveryChallansForCreatedByUserFk = deliveryChallansForCreatedByUserFk;
		this.purchaseOrderHeadersForLastModifiedBy = purchaseOrderHeadersForLastModifiedBy;
		this.grnHeadersForLastModifiedByUserFk = grnHeadersForLastModifiedByUserFk;
		this.deliveryChallansForCreatedByUserFk_1 = deliveryChallansForCreatedByUserFk_1;
		this.tasksForCreatorUserFk = tasksForCreatorUserFk;
		this.invoiceHeadersForCreatedBy = invoiceHeadersForCreatedBy;
		this.tasksForAssigneeUserFk = tasksForAssigneeUserFk;
		this.tasksForCreatorUserFk_1 = tasksForCreatorUserFk_1;
		this.accountDetails = accountDetails;
		this.businessDealsForLastModifiedBy = businessDealsForLastModifiedBy;
		this.financialReports = financialReports;
		this.businessDealsForSponsorUserFk = businessDealsForSponsorUserFk;
		this.salesOrderHeadersForCreatedByUserFk_1 = salesOrderHeadersForCreatedByUserFk_1;
		this.quoteHeadersForLastModifiedUserFk_1 = quoteHeadersForLastModifiedUserFk_1;
		this.accountActivities = accountActivities;
		this.financialReports_1 = financialReports_1;
		this.dealActivities = dealActivities;
		this.quoteHeadersForCreatedByUserFk_1 = quoteHeadersForCreatedByUserFk_1;
		this.warehouses_1 = warehouses_1;
		this.businessDealsForLastModifiedBy_1 = businessDealsForLastModifiedBy_1;
		this.businessDealsForSponsorUserFk_1 = businessDealsForSponsorUserFk_1;
		this.businessDealsForCreatedBy_1 = businessDealsForCreatedBy_1;
		this.purchaseEntriesForLastModifiedByUserFk = purchaseEntriesForLastModifiedByUserFk;
		this.purchaseEntriesForCreatedBy = purchaseEntriesForCreatedBy;
		this.productsForLastModifiedByUserFk = productsForLastModifiedByUserFk;
		this.accountDetails_1 = accountDetails_1;
		this.grnHeadersForLastModifiedByUserFk_1 = grnHeadersForLastModifiedByUserFk_1;
		this.businessDealsForOwnerFk = businessDealsForOwnerFk;
		this.salesOrderHeadersForOwnerFk = salesOrderHeadersForOwnerFk;
		this.purchaseEntriesForCreatedBy_1 = purchaseEntriesForCreatedBy_1;
		this.purchaseOrderHeadersForCreatedBy_1 = purchaseOrderHeadersForCreatedBy_1;
		this.purchaseOrderHeadersForLastModifiedBy_1 = purchaseOrderHeadersForLastModifiedBy_1;
		this.inventoryItemsForCreatedByUserFk = inventoryItemsForCreatedByUserFk;
		this.salesOrderHeadersForLastModifiedByUserFk = salesOrderHeadersForLastModifiedByUserFk;
		this.productsForCreatedByUserFk = productsForCreatedByUserFk;
		this.inventoryItemsForLastModifiedByUserFk = inventoryItemsForLastModifiedByUserFk;
		this.invoiceHeadersForLastModifiedBy = invoiceHeadersForLastModifiedBy;
		this.productsForLastModifiedByUserFk_1 = productsForLastModifiedByUserFk_1;
		this.tasksForAssigneeUserFk_1 = tasksForAssigneeUserFk_1;
		this.deliveryChallansForLastModifiedByUserFk_1 = deliveryChallansForLastModifiedByUserFk_1;
		this.businessDealsForOwnerFk_1 = businessDealsForOwnerFk_1;
		this.productsForCreatedByUserFk_1 = productsForCreatedByUserFk_1;
		this.salesOrderHeadersForOwnerFk_1 = salesOrderHeadersForOwnerFk_1;
		this.accountActivities_1 = accountActivities_1;
		this.grnHeadersForCreatedByUserFk_1 = grnHeadersForCreatedByUserFk_1;
		this.inventoryItemsForCreatedByUserFk_1 = inventoryItemsForCreatedByUserFk_1;
		this.purchaseEntriesForLastModifiedByUserFk_1 = purchaseEntriesForLastModifiedByUserFk_1;
		this.salesOrderHeadersForLastModifiedByUserFk_1 = salesOrderHeadersForLastModifiedByUserFk_1;
		this.invoiceHeadersForLastModifiedBy_1 = invoiceHeadersForLastModifiedBy_1;
		this.invoiceHeadersForCreatedBy_1 = invoiceHeadersForCreatedBy_1;
		this.dealActivities_1 = dealActivities_1;
		this.userDetailses_1 = userDetailses_1;
		this.inventoryItemsForLastModifiedByUserFk_1 = inventoryItemsForLastModifiedByUserFk_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRMTYPE_FK")
	public CrmType getCrmType() {
		return this.crmType;
	}

	public void setCrmType(CrmType crmType) {
		this.crmType = crmType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN_FK")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORGANIZATION_FK")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORGLOCATION_FK")
	public OrgLocation getOrgLocation() {
		return this.orgLocation;
	}

	public void setOrgLocation(OrgLocation orgLocation) {
		this.orgLocation = orgLocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANAGER_FK")
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "DOT_PATH")
	public String getDotPath() {
		return this.dotPath;
	}

	public void setDotPath(String dotPath) {
		this.dotPath = dotPath;
	}

	@Column(name = "FIRST_NAME")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "FORGOT_PASS_GUID")
	public String getForgotPassGuid() {
		return this.forgotPassGuid;
	}

	public void setForgotPassGuid(String forgotPassGuid) {
		this.forgotPassGuid = forgotPassGuid;
	}

	@Column(name = "GUID")
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "INVITE_GUID")
	public String getInviteGuid() {
		return this.inviteGuid;
	}

	public void setInviteGuid(String inviteGuid) {
		this.inviteGuid = inviteGuid;
	}

	@Column(name = "LAST_NAME")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "USER_LOGIN_ID")
	public String getUserLoginId() {
		return this.userLoginId;
	}

	public void setUserLoginId(String userLoginId) {
		this.userLoginId = userLoginId;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "SESSION_ID")
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "USER_EMAIL")
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "USER_PHONE")
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "USER_ROLE", nullable = false)
	public long getUserRole() {
		return this.userRole;
	}

	public void setUserRole(long userRole) {
		this.userRole = userRole;
	}

	@Column(name = "SALES_TARGET", nullable = false, precision = 22, scale = 0)
	public double getSalesTarget() {
		return this.salesTarget;
	}

	public void setSalesTarget(double salesTarget) {
		this.salesTarget = salesTarget;
	}

	@Column(name = "IS_INACTIVE", nullable = false)
	public boolean isIsInactive() {
		return this.isInactive;
	}

	public void setIsInactive(boolean isInactive) {
		this.isInactive = isInactive;
	}

	@Column(name = "EXPERTISE", nullable = false)
	public long getExpertise() {
		return this.expertise;
	}

	public void setExpertise(long expertise) {
		this.expertise = expertise;
	}

	@Column(name = "ACCESS_TOKEN")
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<QuoteHeader> getQuoteHeadersForCreatedByUserFk() {
		return this.quoteHeadersForCreatedByUserFk;
	}

	public void setQuoteHeadersForCreatedByUserFk(Set<QuoteHeader> quoteHeadersForCreatedByUserFk) {
		this.quoteHeadersForCreatedByUserFk = quoteHeadersForCreatedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedUserFk")
	public Set<QuoteHeader> getQuoteHeadersForLastModifiedUserFk() {
		return this.quoteHeadersForLastModifiedUserFk;
	}

	public void setQuoteHeadersForLastModifiedUserFk(Set<QuoteHeader> quoteHeadersForLastModifiedUserFk) {
		this.quoteHeadersForLastModifiedUserFk = quoteHeadersForLastModifiedUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<DeliveryChallan> getDeliveryChallansForLastModifiedByUserFk() {
		return this.deliveryChallansForLastModifiedByUserFk;
	}

	public void setDeliveryChallansForLastModifiedByUserFk(
			Set<DeliveryChallan> deliveryChallansForLastModifiedByUserFk) {
		this.deliveryChallansForLastModifiedByUserFk = deliveryChallansForLastModifiedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<GrnHeader> getGrnHeadersForCreatedByUserFk() {
		return this.grnHeadersForCreatedByUserFk;
	}

	public void setGrnHeadersForCreatedByUserFk(Set<GrnHeader> grnHeadersForCreatedByUserFk) {
		this.grnHeadersForCreatedByUserFk = grnHeadersForCreatedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<UserDetails> getUserDetailses() {
		return this.userDetailses;
	}

	public void setUserDetailses(Set<UserDetails> userDetailses) {
		this.userDetailses = userDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedBy")
	public Set<BusinessDeal> getBusinessDealsForCreatedBy() {
		return this.businessDealsForCreatedBy;
	}

	public void setBusinessDealsForCreatedBy(Set<BusinessDeal> businessDealsForCreatedBy) {
		this.businessDealsForCreatedBy = businessDealsForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<Warehouse> getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Set<Warehouse> warehouses) {
		this.warehouses = warehouses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedBy")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeadersForCreatedBy() {
		return this.purchaseOrderHeadersForCreatedBy;
	}

	public void setPurchaseOrderHeadersForCreatedBy(Set<PurchaseOrderHeader> purchaseOrderHeadersForCreatedBy) {
		this.purchaseOrderHeadersForCreatedBy = purchaseOrderHeadersForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForCreatedByUserFk() {
		return this.salesOrderHeadersForCreatedByUserFk;
	}

	public void setSalesOrderHeadersForCreatedByUserFk(Set<SalesOrderHeader> salesOrderHeadersForCreatedByUserFk) {
		this.salesOrderHeadersForCreatedByUserFk = salesOrderHeadersForCreatedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<DeliveryChallan> getDeliveryChallansForCreatedByUserFk() {
		return this.deliveryChallansForCreatedByUserFk;
	}

	public void setDeliveryChallansForCreatedByUserFk(Set<DeliveryChallan> deliveryChallansForCreatedByUserFk) {
		this.deliveryChallansForCreatedByUserFk = deliveryChallansForCreatedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedBy")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeadersForLastModifiedBy() {
		return this.purchaseOrderHeadersForLastModifiedBy;
	}

	public void setPurchaseOrderHeadersForLastModifiedBy(
			Set<PurchaseOrderHeader> purchaseOrderHeadersForLastModifiedBy) {
		this.purchaseOrderHeadersForLastModifiedBy = purchaseOrderHeadersForLastModifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<GrnHeader> getGrnHeadersForLastModifiedByUserFk() {
		return this.grnHeadersForLastModifiedByUserFk;
	}

	public void setGrnHeadersForLastModifiedByUserFk(Set<GrnHeader> grnHeadersForLastModifiedByUserFk) {
		this.grnHeadersForLastModifiedByUserFk = grnHeadersForLastModifiedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<DeliveryChallan> getDeliveryChallansForCreatedByUserFk_1() {
		return this.deliveryChallansForCreatedByUserFk_1;
	}

	public void setDeliveryChallansForCreatedByUserFk_1(Set<DeliveryChallan> deliveryChallansForCreatedByUserFk_1) {
		this.deliveryChallansForCreatedByUserFk_1 = deliveryChallansForCreatedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatorUserFk")
	public Set<Task> getTasksForCreatorUserFk() {
		return this.tasksForCreatorUserFk;
	}

	public void setTasksForCreatorUserFk(Set<Task> tasksForCreatorUserFk) {
		this.tasksForCreatorUserFk = tasksForCreatorUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedBy")
	public Set<InvoiceHeader> getInvoiceHeadersForCreatedBy() {
		return this.invoiceHeadersForCreatedBy;
	}

	public void setInvoiceHeadersForCreatedBy(Set<InvoiceHeader> invoiceHeadersForCreatedBy) {
		this.invoiceHeadersForCreatedBy = invoiceHeadersForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByAssigneeUserFk")
	public Set<Task> getTasksForAssigneeUserFk() {
		return this.tasksForAssigneeUserFk;
	}

	public void setTasksForAssigneeUserFk(Set<Task> tasksForAssigneeUserFk) {
		this.tasksForAssigneeUserFk = tasksForAssigneeUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatorUserFk")
	public Set<Task> getTasksForCreatorUserFk_1() {
		return this.tasksForCreatorUserFk_1;
	}

	public void setTasksForCreatorUserFk_1(Set<Task> tasksForCreatorUserFk_1) {
		this.tasksForCreatorUserFk_1 = tasksForCreatorUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<AccountDetail> getAccountDetails() {
		return this.accountDetails;
	}

	public void setAccountDetails(Set<AccountDetail> accountDetails) {
		this.accountDetails = accountDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedBy")
	public Set<BusinessDeal> getBusinessDealsForLastModifiedBy() {
		return this.businessDealsForLastModifiedBy;
	}

	public void setBusinessDealsForLastModifiedBy(Set<BusinessDeal> businessDealsForLastModifiedBy) {
		this.businessDealsForLastModifiedBy = businessDealsForLastModifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<FinancialReport> getFinancialReports() {
		return this.financialReports;
	}

	public void setFinancialReports(Set<FinancialReport> financialReports) {
		this.financialReports = financialReports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsBySponsorUserFk")
	public Set<BusinessDeal> getBusinessDealsForSponsorUserFk() {
		return this.businessDealsForSponsorUserFk;
	}

	public void setBusinessDealsForSponsorUserFk(Set<BusinessDeal> businessDealsForSponsorUserFk) {
		this.businessDealsForSponsorUserFk = businessDealsForSponsorUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForCreatedByUserFk_1() {
		return this.salesOrderHeadersForCreatedByUserFk_1;
	}

	public void setSalesOrderHeadersForCreatedByUserFk_1(Set<SalesOrderHeader> salesOrderHeadersForCreatedByUserFk_1) {
		this.salesOrderHeadersForCreatedByUserFk_1 = salesOrderHeadersForCreatedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedUserFk")
	public Set<QuoteHeader> getQuoteHeadersForLastModifiedUserFk_1() {
		return this.quoteHeadersForLastModifiedUserFk_1;
	}

	public void setQuoteHeadersForLastModifiedUserFk_1(Set<QuoteHeader> quoteHeadersForLastModifiedUserFk_1) {
		this.quoteHeadersForLastModifiedUserFk_1 = quoteHeadersForLastModifiedUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<AccountActivity> getAccountActivities() {
		return this.accountActivities;
	}

	public void setAccountActivities(Set<AccountActivity> accountActivities) {
		this.accountActivities = accountActivities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<FinancialReport> getFinancialReports_1() {
		return this.financialReports_1;
	}

	public void setFinancialReports_1(Set<FinancialReport> financialReports_1) {
		this.financialReports_1 = financialReports_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<DealActivity> getDealActivities() {
		return this.dealActivities;
	}

	public void setDealActivities(Set<DealActivity> dealActivities) {
		this.dealActivities = dealActivities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<QuoteHeader> getQuoteHeadersForCreatedByUserFk_1() {
		return this.quoteHeadersForCreatedByUserFk_1;
	}

	public void setQuoteHeadersForCreatedByUserFk_1(Set<QuoteHeader> quoteHeadersForCreatedByUserFk_1) {
		this.quoteHeadersForCreatedByUserFk_1 = quoteHeadersForCreatedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<Warehouse> getWarehouses_1() {
		return this.warehouses_1;
	}

	public void setWarehouses_1(Set<Warehouse> warehouses_1) {
		this.warehouses_1 = warehouses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedBy")
	public Set<BusinessDeal> getBusinessDealsForLastModifiedBy_1() {
		return this.businessDealsForLastModifiedBy_1;
	}

	public void setBusinessDealsForLastModifiedBy_1(Set<BusinessDeal> businessDealsForLastModifiedBy_1) {
		this.businessDealsForLastModifiedBy_1 = businessDealsForLastModifiedBy_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsBySponsorUserFk")
	public Set<BusinessDeal> getBusinessDealsForSponsorUserFk_1() {
		return this.businessDealsForSponsorUserFk_1;
	}

	public void setBusinessDealsForSponsorUserFk_1(Set<BusinessDeal> businessDealsForSponsorUserFk_1) {
		this.businessDealsForSponsorUserFk_1 = businessDealsForSponsorUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedBy")
	public Set<BusinessDeal> getBusinessDealsForCreatedBy_1() {
		return this.businessDealsForCreatedBy_1;
	}

	public void setBusinessDealsForCreatedBy_1(Set<BusinessDeal> businessDealsForCreatedBy_1) {
		this.businessDealsForCreatedBy_1 = businessDealsForCreatedBy_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<PurchaseEntry> getPurchaseEntriesForLastModifiedByUserFk() {
		return this.purchaseEntriesForLastModifiedByUserFk;
	}

	public void setPurchaseEntriesForLastModifiedByUserFk(Set<PurchaseEntry> purchaseEntriesForLastModifiedByUserFk) {
		this.purchaseEntriesForLastModifiedByUserFk = purchaseEntriesForLastModifiedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedBy")
	public Set<PurchaseEntry> getPurchaseEntriesForCreatedBy() {
		return this.purchaseEntriesForCreatedBy;
	}

	public void setPurchaseEntriesForCreatedBy(Set<PurchaseEntry> purchaseEntriesForCreatedBy) {
		this.purchaseEntriesForCreatedBy = purchaseEntriesForCreatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<Product> getProductsForLastModifiedByUserFk() {
		return this.productsForLastModifiedByUserFk;
	}

	public void setProductsForLastModifiedByUserFk(Set<Product> productsForLastModifiedByUserFk) {
		this.productsForLastModifiedByUserFk = productsForLastModifiedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<AccountDetail> getAccountDetails_1() {
		return this.accountDetails_1;
	}

	public void setAccountDetails_1(Set<AccountDetail> accountDetails_1) {
		this.accountDetails_1 = accountDetails_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<GrnHeader> getGrnHeadersForLastModifiedByUserFk_1() {
		return this.grnHeadersForLastModifiedByUserFk_1;
	}

	public void setGrnHeadersForLastModifiedByUserFk_1(Set<GrnHeader> grnHeadersForLastModifiedByUserFk_1) {
		this.grnHeadersForLastModifiedByUserFk_1 = grnHeadersForLastModifiedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByOwnerFk")
	public Set<BusinessDeal> getBusinessDealsForOwnerFk() {
		return this.businessDealsForOwnerFk;
	}

	public void setBusinessDealsForOwnerFk(Set<BusinessDeal> businessDealsForOwnerFk) {
		this.businessDealsForOwnerFk = businessDealsForOwnerFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByOwnerFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForOwnerFk() {
		return this.salesOrderHeadersForOwnerFk;
	}

	public void setSalesOrderHeadersForOwnerFk(Set<SalesOrderHeader> salesOrderHeadersForOwnerFk) {
		this.salesOrderHeadersForOwnerFk = salesOrderHeadersForOwnerFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedBy")
	public Set<PurchaseEntry> getPurchaseEntriesForCreatedBy_1() {
		return this.purchaseEntriesForCreatedBy_1;
	}

	public void setPurchaseEntriesForCreatedBy_1(Set<PurchaseEntry> purchaseEntriesForCreatedBy_1) {
		this.purchaseEntriesForCreatedBy_1 = purchaseEntriesForCreatedBy_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedBy")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeadersForCreatedBy_1() {
		return this.purchaseOrderHeadersForCreatedBy_1;
	}

	public void setPurchaseOrderHeadersForCreatedBy_1(Set<PurchaseOrderHeader> purchaseOrderHeadersForCreatedBy_1) {
		this.purchaseOrderHeadersForCreatedBy_1 = purchaseOrderHeadersForCreatedBy_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedBy")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeadersForLastModifiedBy_1() {
		return this.purchaseOrderHeadersForLastModifiedBy_1;
	}

	public void setPurchaseOrderHeadersForLastModifiedBy_1(
			Set<PurchaseOrderHeader> purchaseOrderHeadersForLastModifiedBy_1) {
		this.purchaseOrderHeadersForLastModifiedBy_1 = purchaseOrderHeadersForLastModifiedBy_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<InventoryItem> getInventoryItemsForCreatedByUserFk() {
		return this.inventoryItemsForCreatedByUserFk;
	}

	public void setInventoryItemsForCreatedByUserFk(Set<InventoryItem> inventoryItemsForCreatedByUserFk) {
		this.inventoryItemsForCreatedByUserFk = inventoryItemsForCreatedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForLastModifiedByUserFk() {
		return this.salesOrderHeadersForLastModifiedByUserFk;
	}

	public void setSalesOrderHeadersForLastModifiedByUserFk(
			Set<SalesOrderHeader> salesOrderHeadersForLastModifiedByUserFk) {
		this.salesOrderHeadersForLastModifiedByUserFk = salesOrderHeadersForLastModifiedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<Product> getProductsForCreatedByUserFk() {
		return this.productsForCreatedByUserFk;
	}

	public void setProductsForCreatedByUserFk(Set<Product> productsForCreatedByUserFk) {
		this.productsForCreatedByUserFk = productsForCreatedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<InventoryItem> getInventoryItemsForLastModifiedByUserFk() {
		return this.inventoryItemsForLastModifiedByUserFk;
	}

	public void setInventoryItemsForLastModifiedByUserFk(Set<InventoryItem> inventoryItemsForLastModifiedByUserFk) {
		this.inventoryItemsForLastModifiedByUserFk = inventoryItemsForLastModifiedByUserFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedBy")
	public Set<InvoiceHeader> getInvoiceHeadersForLastModifiedBy() {
		return this.invoiceHeadersForLastModifiedBy;
	}

	public void setInvoiceHeadersForLastModifiedBy(Set<InvoiceHeader> invoiceHeadersForLastModifiedBy) {
		this.invoiceHeadersForLastModifiedBy = invoiceHeadersForLastModifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<Product> getProductsForLastModifiedByUserFk_1() {
		return this.productsForLastModifiedByUserFk_1;
	}

	public void setProductsForLastModifiedByUserFk_1(Set<Product> productsForLastModifiedByUserFk_1) {
		this.productsForLastModifiedByUserFk_1 = productsForLastModifiedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByAssigneeUserFk")
	public Set<Task> getTasksForAssigneeUserFk_1() {
		return this.tasksForAssigneeUserFk_1;
	}

	public void setTasksForAssigneeUserFk_1(Set<Task> tasksForAssigneeUserFk_1) {
		this.tasksForAssigneeUserFk_1 = tasksForAssigneeUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<DeliveryChallan> getDeliveryChallansForLastModifiedByUserFk_1() {
		return this.deliveryChallansForLastModifiedByUserFk_1;
	}

	public void setDeliveryChallansForLastModifiedByUserFk_1(
			Set<DeliveryChallan> deliveryChallansForLastModifiedByUserFk_1) {
		this.deliveryChallansForLastModifiedByUserFk_1 = deliveryChallansForLastModifiedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByOwnerFk")
	public Set<BusinessDeal> getBusinessDealsForOwnerFk_1() {
		return this.businessDealsForOwnerFk_1;
	}

	public void setBusinessDealsForOwnerFk_1(Set<BusinessDeal> businessDealsForOwnerFk_1) {
		this.businessDealsForOwnerFk_1 = businessDealsForOwnerFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<Product> getProductsForCreatedByUserFk_1() {
		return this.productsForCreatedByUserFk_1;
	}

	public void setProductsForCreatedByUserFk_1(Set<Product> productsForCreatedByUserFk_1) {
		this.productsForCreatedByUserFk_1 = productsForCreatedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByOwnerFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForOwnerFk_1() {
		return this.salesOrderHeadersForOwnerFk_1;
	}

	public void setSalesOrderHeadersForOwnerFk_1(Set<SalesOrderHeader> salesOrderHeadersForOwnerFk_1) {
		this.salesOrderHeadersForOwnerFk_1 = salesOrderHeadersForOwnerFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<AccountActivity> getAccountActivities_1() {
		return this.accountActivities_1;
	}

	public void setAccountActivities_1(Set<AccountActivity> accountActivities_1) {
		this.accountActivities_1 = accountActivities_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<GrnHeader> getGrnHeadersForCreatedByUserFk_1() {
		return this.grnHeadersForCreatedByUserFk_1;
	}

	public void setGrnHeadersForCreatedByUserFk_1(Set<GrnHeader> grnHeadersForCreatedByUserFk_1) {
		this.grnHeadersForCreatedByUserFk_1 = grnHeadersForCreatedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedByUserFk")
	public Set<InventoryItem> getInventoryItemsForCreatedByUserFk_1() {
		return this.inventoryItemsForCreatedByUserFk_1;
	}

	public void setInventoryItemsForCreatedByUserFk_1(Set<InventoryItem> inventoryItemsForCreatedByUserFk_1) {
		this.inventoryItemsForCreatedByUserFk_1 = inventoryItemsForCreatedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<PurchaseEntry> getPurchaseEntriesForLastModifiedByUserFk_1() {
		return this.purchaseEntriesForLastModifiedByUserFk_1;
	}

	public void setPurchaseEntriesForLastModifiedByUserFk_1(
			Set<PurchaseEntry> purchaseEntriesForLastModifiedByUserFk_1) {
		this.purchaseEntriesForLastModifiedByUserFk_1 = purchaseEntriesForLastModifiedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForLastModifiedByUserFk_1() {
		return this.salesOrderHeadersForLastModifiedByUserFk_1;
	}

	public void setSalesOrderHeadersForLastModifiedByUserFk_1(
			Set<SalesOrderHeader> salesOrderHeadersForLastModifiedByUserFk_1) {
		this.salesOrderHeadersForLastModifiedByUserFk_1 = salesOrderHeadersForLastModifiedByUserFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedBy")
	public Set<InvoiceHeader> getInvoiceHeadersForLastModifiedBy_1() {
		return this.invoiceHeadersForLastModifiedBy_1;
	}

	public void setInvoiceHeadersForLastModifiedBy_1(Set<InvoiceHeader> invoiceHeadersForLastModifiedBy_1) {
		this.invoiceHeadersForLastModifiedBy_1 = invoiceHeadersForLastModifiedBy_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByCreatedBy")
	public Set<InvoiceHeader> getInvoiceHeadersForCreatedBy_1() {
		return this.invoiceHeadersForCreatedBy_1;
	}

	public void setInvoiceHeadersForCreatedBy_1(Set<InvoiceHeader> invoiceHeadersForCreatedBy_1) {
		this.invoiceHeadersForCreatedBy_1 = invoiceHeadersForCreatedBy_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<DealActivity> getDealActivities_1() {
		return this.dealActivities_1;
	}

	public void setDealActivities_1(Set<DealActivity> dealActivities_1) {
		this.dealActivities_1 = dealActivities_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<UserDetails> getUserDetailses_1() {
		return this.userDetailses_1;
	}

	public void setUserDetailses_1(Set<UserDetails> userDetailses_1) {
		this.userDetailses_1 = userDetailses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetailsByLastModifiedByUserFk")
	public Set<InventoryItem> getInventoryItemsForLastModifiedByUserFk_1() {
		return this.inventoryItemsForLastModifiedByUserFk_1;
	}

	public void setInventoryItemsForLastModifiedByUserFk_1(Set<InventoryItem> inventoryItemsForLastModifiedByUserFk_1) {
		this.inventoryItemsForLastModifiedByUserFk_1 = inventoryItemsForLastModifiedByUserFk_1;
	}

}
