package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AccountDetail generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT_DETAIL", catalog = "namcrm")
public class AccountDetail implements java.io.Serializable {

	private long id;
	private AccountActivity accountActivity;
	private AccountDetail accountDetail;
	private Domain domain;
	private IndustryType industryType;
	private RoleType roleType;
	private UserDetails userDetails;
	private String accountName;
	private String cstNo;
	private String guid;
	private int noOfEmployees;
	private String parentAccount;
	private String vatNo;
	private String webUrl;
	private String panNumber;
	private String bankAccountNo;
	private String bankName;
	private String ifscCode;
	private String gstNo;
	private String stateCode;
	private boolean isDisabled;
	private String state;
	private String country;
	private boolean isOrganisation;
	private Set<InvoiceHeader> invoiceHeadersForToShipAccountFk = new HashSet<InvoiceHeader>(0);
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForToShipAccountFk = new HashSet<SalesOrderHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForAccountFk = new HashSet<SalesOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForToShipAccountFk = new HashSet<DeliveryChallan>(0);
	private Set<Warehouse> warehouses = new HashSet<Warehouse>(0);
	private Set<AccountTelephone> accountTelephones = new HashSet<AccountTelephone>(0);
	private Set<AccountDetail> accountDetails = new HashSet<AccountDetail>(0);
	private Set<DeliveryChallan> deliveryChallansForAccountFk = new HashSet<DeliveryChallan>(0);
	private Set<GrnHeader> grnHeadersForVendorFk = new HashSet<GrnHeader>(0);
	private Set<GrnHeader> grnHeadersForCustomerFk = new HashSet<GrnHeader>(0);
	private Set<Payable> payables = new HashSet<Payable>(0);
	private Set<InvoiceHeader> invoiceHeadersForAccountFk = new HashSet<InvoiceHeader>(0);
	private Set<QuoteHeader> quoteHeaders = new HashSet<QuoteHeader>(0);
	private Set<AccountActivity> accountActivities = new HashSet<AccountActivity>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeadersForAccountId = new HashSet<PurchaseOrderHeader>(0);
	private Set<BusinessDeal> businessDeals = new HashSet<BusinessDeal>(0);
	private Set<PersonDetail> personDetails = new HashSet<PersonDetail>(0);
	private Set<PurchaseEntry> purchaseEntries = new HashSet<PurchaseEntry>(0);
	private Set<Recievable> recievables = new HashSet<Recievable>(0);
	private Set<AccountAddress> accountAddresses = new HashSet<AccountAddress>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeadersForToShipAccountFk = new HashSet<PurchaseOrderHeader>(0);
	private Set<AccountEmail> accountEmails = new HashSet<AccountEmail>(0);

	public AccountDetail() {
	}

	public AccountDetail(long id, int noOfEmployees, boolean isDisabled, boolean isOrganisation) {
		this.id = id;
		this.noOfEmployees = noOfEmployees;
		this.isDisabled = isDisabled;
		this.isOrganisation = isOrganisation;
	}

	public AccountDetail(long id, AccountActivity accountActivity, AccountDetail accountDetail, Domain domain,
			IndustryType industryType, RoleType roleType, UserDetails userDetails, String accountName, String cstNo,
			String guid, int noOfEmployees, String parentAccount, String vatNo, String webUrl, String panNumber,
			String bankAccountNo, String bankName, String ifscCode, String gstNo, String stateCode, boolean isDisabled,
			String state, String country, boolean isOrganisation, Set<InvoiceHeader> invoiceHeadersForToShipAccountFk,
			Set<OrderItem> orderItems, Set<SalesOrderHeader> salesOrderHeadersForToShipAccountFk,
			Set<SalesOrderHeader> salesOrderHeadersForAccountFk,
			Set<DeliveryChallan> deliveryChallansForToShipAccountFk, Set<Warehouse> warehouses,
			Set<AccountTelephone> accountTelephones, Set<AccountDetail> accountDetails,
			Set<DeliveryChallan> deliveryChallansForAccountFk, Set<GrnHeader> grnHeadersForVendorFk,
			Set<GrnHeader> grnHeadersForCustomerFk, Set<Payable> payables,
			Set<InvoiceHeader> invoiceHeadersForAccountFk, Set<QuoteHeader> quoteHeaders,
			Set<AccountActivity> accountActivities, Set<PurchaseOrderHeader> purchaseOrderHeadersForAccountId,
			Set<BusinessDeal> businessDeals, Set<PersonDetail> personDetails, Set<PurchaseEntry> purchaseEntries,
			Set<Recievable> recievables, Set<AccountAddress> accountAddresses,
			Set<PurchaseOrderHeader> purchaseOrderHeadersForToShipAccountFk, Set<AccountEmail> accountEmails) {
		this.id = id;
		this.accountActivity = accountActivity;
		this.accountDetail = accountDetail;
		this.domain = domain;
		this.industryType = industryType;
		this.roleType = roleType;
		this.userDetails = userDetails;
		this.accountName = accountName;
		this.cstNo = cstNo;
		this.guid = guid;
		this.noOfEmployees = noOfEmployees;
		this.parentAccount = parentAccount;
		this.vatNo = vatNo;
		this.webUrl = webUrl;
		this.panNumber = panNumber;
		this.bankAccountNo = bankAccountNo;
		this.bankName = bankName;
		this.ifscCode = ifscCode;
		this.gstNo = gstNo;
		this.stateCode = stateCode;
		this.isDisabled = isDisabled;
		this.state = state;
		this.country = country;
		this.isOrganisation = isOrganisation;
		this.invoiceHeadersForToShipAccountFk = invoiceHeadersForToShipAccountFk;
		this.orderItems = orderItems;
		this.salesOrderHeadersForToShipAccountFk = salesOrderHeadersForToShipAccountFk;
		this.salesOrderHeadersForAccountFk = salesOrderHeadersForAccountFk;
		this.deliveryChallansForToShipAccountFk = deliveryChallansForToShipAccountFk;
		this.warehouses = warehouses;
		this.accountTelephones = accountTelephones;
		this.accountDetails = accountDetails;
		this.deliveryChallansForAccountFk = deliveryChallansForAccountFk;
		this.grnHeadersForVendorFk = grnHeadersForVendorFk;
		this.grnHeadersForCustomerFk = grnHeadersForCustomerFk;
		this.payables = payables;
		this.invoiceHeadersForAccountFk = invoiceHeadersForAccountFk;
		this.quoteHeaders = quoteHeaders;
		this.accountActivities = accountActivities;
		this.purchaseOrderHeadersForAccountId = purchaseOrderHeadersForAccountId;
		this.businessDeals = businessDeals;
		this.personDetails = personDetails;
		this.purchaseEntries = purchaseEntries;
		this.recievables = recievables;
		this.accountAddresses = accountAddresses;
		this.purchaseOrderHeadersForToShipAccountFk = purchaseOrderHeadersForToShipAccountFk;
		this.accountEmails = accountEmails;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ACTIVITY_FK")
	public AccountActivity getAccountActivity() {
		return this.accountActivity;
	}

	public void setAccountActivity(AccountActivity accountActivity) {
		this.accountActivity = accountActivity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_ACCOUNT_FK")
	public AccountDetail getAccountDetail() {
		return this.accountDetail;
	}

	public void setAccountDetail(AccountDetail accountDetail) {
		this.accountDetail = accountDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN_FK")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INDUSRTY_TYPE_FK")
	public IndustryType getIndustryType() {
		return this.industryType;
	}

	public void setIndustryType(IndustryType industryType) {
		this.industryType = industryType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_TYPE_FK")
	public RoleType getRoleType() {
		return this.roleType;
	}

	public void setRoleType(RoleType roleType) {
		this.roleType = roleType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_MGR_FK")
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "ACCOUNT_NAME")
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "CST_NO")
	public String getCstNo() {
		return this.cstNo;
	}

	public void setCstNo(String cstNo) {
		this.cstNo = cstNo;
	}

	@Column(name = "GUID")
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "NO_OF_EMPLOYEES", nullable = false)
	public int getNoOfEmployees() {
		return this.noOfEmployees;
	}

	public void setNoOfEmployees(int noOfEmployees) {
		this.noOfEmployees = noOfEmployees;
	}

	@Column(name = "PARENT_ACCOUNT")
	public String getParentAccount() {
		return this.parentAccount;
	}

	public void setParentAccount(String parentAccount) {
		this.parentAccount = parentAccount;
	}

	@Column(name = "VAT_NO")
	public String getVatNo() {
		return this.vatNo;
	}

	public void setVatNo(String vatNo) {
		this.vatNo = vatNo;
	}

	@Column(name = "WEB_URL")
	public String getWebUrl() {
		return this.webUrl;
	}

	public void setWebUrl(String webUrl) {
		this.webUrl = webUrl;
	}

	@Column(name = "PAN_NUMBER", length = 45)
	public String getPanNumber() {
		return this.panNumber;
	}

	public void setPanNumber(String panNumber) {
		this.panNumber = panNumber;
	}

	@Column(name = "BANK_ACCOUNT_NO")
	public String getBankAccountNo() {
		return this.bankAccountNo;
	}

	public void setBankAccountNo(String bankAccountNo) {
		this.bankAccountNo = bankAccountNo;
	}

	@Column(name = "BANK_NAME")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "IFSC_CODE", length = 45)
	public String getIfscCode() {
		return this.ifscCode;
	}

	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}

	@Column(name = "GST_NO")
	public String getGstNo() {
		return this.gstNo;
	}

	public void setGstNo(String gstNo) {
		this.gstNo = gstNo;
	}

	@Column(name = "STATE_CODE")
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "IS_DISABLED", nullable = false)
	public boolean isIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	@Column(name = "STATE")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "IS_ORGANISATION", nullable = false)
	public boolean isIsOrganisation() {
		return this.isOrganisation;
	}

	public void setIsOrganisation(boolean isOrganisation) {
		this.isOrganisation = isOrganisation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetailByToShipAccountFk")
	public Set<InvoiceHeader> getInvoiceHeadersForToShipAccountFk() {
		return this.invoiceHeadersForToShipAccountFk;
	}

	public void setInvoiceHeadersForToShipAccountFk(Set<InvoiceHeader> invoiceHeadersForToShipAccountFk) {
		this.invoiceHeadersForToShipAccountFk = invoiceHeadersForToShipAccountFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetailByToShipAccountFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForToShipAccountFk() {
		return this.salesOrderHeadersForToShipAccountFk;
	}

	public void setSalesOrderHeadersForToShipAccountFk(Set<SalesOrderHeader> salesOrderHeadersForToShipAccountFk) {
		this.salesOrderHeadersForToShipAccountFk = salesOrderHeadersForToShipAccountFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetailByAccountFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForAccountFk() {
		return this.salesOrderHeadersForAccountFk;
	}

	public void setSalesOrderHeadersForAccountFk(Set<SalesOrderHeader> salesOrderHeadersForAccountFk) {
		this.salesOrderHeadersForAccountFk = salesOrderHeadersForAccountFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetailByToShipAccountFk")
	public Set<DeliveryChallan> getDeliveryChallansForToShipAccountFk() {
		return this.deliveryChallansForToShipAccountFk;
	}

	public void setDeliveryChallansForToShipAccountFk(Set<DeliveryChallan> deliveryChallansForToShipAccountFk) {
		this.deliveryChallansForToShipAccountFk = deliveryChallansForToShipAccountFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<Warehouse> getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Set<Warehouse> warehouses) {
		this.warehouses = warehouses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<AccountTelephone> getAccountTelephones() {
		return this.accountTelephones;
	}

	public void setAccountTelephones(Set<AccountTelephone> accountTelephones) {
		this.accountTelephones = accountTelephones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<AccountDetail> getAccountDetails() {
		return this.accountDetails;
	}

	public void setAccountDetails(Set<AccountDetail> accountDetails) {
		this.accountDetails = accountDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetailByAccountFk")
	public Set<DeliveryChallan> getDeliveryChallansForAccountFk() {
		return this.deliveryChallansForAccountFk;
	}

	public void setDeliveryChallansForAccountFk(Set<DeliveryChallan> deliveryChallansForAccountFk) {
		this.deliveryChallansForAccountFk = deliveryChallansForAccountFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetailByVendorFk")
	public Set<GrnHeader> getGrnHeadersForVendorFk() {
		return this.grnHeadersForVendorFk;
	}

	public void setGrnHeadersForVendorFk(Set<GrnHeader> grnHeadersForVendorFk) {
		this.grnHeadersForVendorFk = grnHeadersForVendorFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetailByCustomerFk")
	public Set<GrnHeader> getGrnHeadersForCustomerFk() {
		return this.grnHeadersForCustomerFk;
	}

	public void setGrnHeadersForCustomerFk(Set<GrnHeader> grnHeadersForCustomerFk) {
		this.grnHeadersForCustomerFk = grnHeadersForCustomerFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<Payable> getPayables() {
		return this.payables;
	}

	public void setPayables(Set<Payable> payables) {
		this.payables = payables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetailByAccountFk")
	public Set<InvoiceHeader> getInvoiceHeadersForAccountFk() {
		return this.invoiceHeadersForAccountFk;
	}

	public void setInvoiceHeadersForAccountFk(Set<InvoiceHeader> invoiceHeadersForAccountFk) {
		this.invoiceHeadersForAccountFk = invoiceHeadersForAccountFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<QuoteHeader> getQuoteHeaders() {
		return this.quoteHeaders;
	}

	public void setQuoteHeaders(Set<QuoteHeader> quoteHeaders) {
		this.quoteHeaders = quoteHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<AccountActivity> getAccountActivities() {
		return this.accountActivities;
	}

	public void setAccountActivities(Set<AccountActivity> accountActivities) {
		this.accountActivities = accountActivities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetailByAccountId")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeadersForAccountId() {
		return this.purchaseOrderHeadersForAccountId;
	}

	public void setPurchaseOrderHeadersForAccountId(Set<PurchaseOrderHeader> purchaseOrderHeadersForAccountId) {
		this.purchaseOrderHeadersForAccountId = purchaseOrderHeadersForAccountId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<BusinessDeal> getBusinessDeals() {
		return this.businessDeals;
	}

	public void setBusinessDeals(Set<BusinessDeal> businessDeals) {
		this.businessDeals = businessDeals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<PersonDetail> getPersonDetails() {
		return this.personDetails;
	}

	public void setPersonDetails(Set<PersonDetail> personDetails) {
		this.personDetails = personDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<PurchaseEntry> getPurchaseEntries() {
		return this.purchaseEntries;
	}

	public void setPurchaseEntries(Set<PurchaseEntry> purchaseEntries) {
		this.purchaseEntries = purchaseEntries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<Recievable> getRecievables() {
		return this.recievables;
	}

	public void setRecievables(Set<Recievable> recievables) {
		this.recievables = recievables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<AccountAddress> getAccountAddresses() {
		return this.accountAddresses;
	}

	public void setAccountAddresses(Set<AccountAddress> accountAddresses) {
		this.accountAddresses = accountAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetailByToShipAccountFk")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeadersForToShipAccountFk() {
		return this.purchaseOrderHeadersForToShipAccountFk;
	}

	public void setPurchaseOrderHeadersForToShipAccountFk(
			Set<PurchaseOrderHeader> purchaseOrderHeadersForToShipAccountFk) {
		this.purchaseOrderHeadersForToShipAccountFk = purchaseOrderHeadersForToShipAccountFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountDetail")
	public Set<AccountEmail> getAccountEmails() {
		return this.accountEmails;
	}

	public void setAccountEmails(Set<AccountEmail> accountEmails) {
		this.accountEmails = accountEmails;
	}

}
