package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountEmail generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT_EMAIL", catalog = "namcrm")
public class AccountEmail implements java.io.Serializable {

	private long id;
	private AccountDetail accountDetail;
	private String email;
	private boolean isDefault;
	private Integer acctemailsIntegerIdx;

	public AccountEmail() {
	}

	public AccountEmail(long id, boolean isDefault) {
		this.id = id;
		this.isDefault = isDefault;
	}

	public AccountEmail(long id, AccountDetail accountDetail, String email, boolean isDefault,
			Integer acctemailsIntegerIdx) {
		this.id = id;
		this.accountDetail = accountDetail;
		this.email = email;
		this.isDefault = isDefault;
		this.acctemailsIntegerIdx = acctemailsIntegerIdx;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_FK")
	public AccountDetail getAccountDetail() {
		return this.accountDetail;
	}

	public void setAccountDetail(AccountDetail accountDetail) {
		this.accountDetail = accountDetail;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "IS_DEFAULT", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "ACCTEMAILS_INTEGER_IDX")
	public Integer getAcctemailsIntegerIdx() {
		return this.acctemailsIntegerIdx;
	}

	public void setAcctemailsIntegerIdx(Integer acctemailsIntegerIdx) {
		this.acctemailsIntegerIdx = acctemailsIntegerIdx;
	}

}
