package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountTelephone generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT_TELEPHONE", catalog = "namcrm")
public class AccountTelephone implements java.io.Serializable {

	private long id;
	private AccountDetail accountDetail;
	private boolean isDefault;
	private String number;
	private String phoneType;
	private Integer accttelephonesIntegerIdx;

	public AccountTelephone() {
	}

	public AccountTelephone(long id, boolean isDefault) {
		this.id = id;
		this.isDefault = isDefault;
	}

	public AccountTelephone(long id, AccountDetail accountDetail, boolean isDefault, String number, String phoneType,
			Integer accttelephonesIntegerIdx) {
		this.id = id;
		this.accountDetail = accountDetail;
		this.isDefault = isDefault;
		this.number = number;
		this.phoneType = phoneType;
		this.accttelephonesIntegerIdx = accttelephonesIntegerIdx;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_FK")
	public AccountDetail getAccountDetail() {
		return this.accountDetail;
	}

	public void setAccountDetail(AccountDetail accountDetail) {
		this.accountDetail = accountDetail;
	}

	@Column(name = "IS_DEFAULT", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "NUMBER")
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "PHONE_TYPE")
	public String getPhoneType() {
		return this.phoneType;
	}

	public void setPhoneType(String phoneType) {
		this.phoneType = phoneType;
	}

	@Column(name = "ACCTTELEPHONES_INTEGER_IDX")
	public Integer getAccttelephonesIntegerIdx() {
		return this.accttelephonesIntegerIdx;
	}

	public void setAccttelephonesIntegerIdx(Integer accttelephonesIntegerIdx) {
		this.accttelephonesIntegerIdx = accttelephonesIntegerIdx;
	}

}
