package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusinessDealHistory generated by hbm2java
 */
@Entity
@Table(name = "BUSINESS_DEAL_HISTORY", catalog = "namcrm")
public class BusinessDealHistory implements java.io.Serializable {

	private long id;
	private BusinessDeal businessDeal;
	private StatusItem statusItem;
	private UserDetails userDetails;
	private Date on;

	public BusinessDealHistory() {
	}

	public BusinessDealHistory(long id) {
		this.id = id;
	}

	public BusinessDealHistory(long id, BusinessDeal businessDeal, StatusItem statusItem, UserDetails userDetails,
			Date on) {
		this.id = id;
		this.businessDeal = businessDeal;
		this.statusItem = statusItem;
		this.userDetails = userDetails;
		this.on = on;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEAL_FK")
	public BusinessDeal getBusinessDeal() {
		return this.businessDeal;
	}

	public void setBusinessDeal(BusinessDeal businessDeal) {
		this.businessDeal = businessDeal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TOSTATUS_ID_OID")
	public StatusItem getStatusItem() {
		return this.statusItem;
	}

	public void setStatusItem(StatusItem statusItem) {
		this.statusItem = statusItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY")
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ON", length = 19)
	public Date getOn() {
		return this.on;
	}

	public void setOn(Date on) {
		this.on = on;
	}

}
