package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "CITIES", catalog = "namcrm")
public class Cities implements java.io.Serializable {

	private Long id;
	private String name;
	private long stateId;

	public Cities() {
	}

	public Cities(long stateId) {
		this.stateId = stateId;
	}

	public Cities(String name, long stateId) {
		this.name = name;
		this.stateId = stateId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "STATE_ID", nullable = false)
	public long getStateId() {
		return this.stateId;
	}

	public void setStateId(long stateId) {
		this.stateId = stateId;
	}

}
