package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CollabRoom generated by hbm2java
 */
@Entity
@Table(name = "COLLAB_ROOM", catalog = "namcrm")
public class CollabRoom implements java.io.Serializable {

	private long id;
	private String roomName;
	private String sparkRoomId;
	private String teamName;
	private Set<CollabRoomMember> collabRoomMembers = new HashSet<CollabRoomMember>(0);

	public CollabRoom() {
	}

	public CollabRoom(long id) {
		this.id = id;
	}

	public CollabRoom(long id, String roomName, String sparkRoomId, String teamName,
			Set<CollabRoomMember> collabRoomMembers) {
		this.id = id;
		this.roomName = roomName;
		this.sparkRoomId = sparkRoomId;
		this.teamName = teamName;
		this.collabRoomMembers = collabRoomMembers;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ROOM_NAME")
	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	@Column(name = "SPARK_ROOM_ID")
	public String getSparkRoomId() {
		return this.sparkRoomId;
	}

	public void setSparkRoomId(String sparkRoomId) {
		this.sparkRoomId = sparkRoomId;
	}

	@Column(name = "TEAM_NAME")
	public String getTeamName() {
		return this.teamName;
	}

	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collabRoom")
	public Set<CollabRoomMember> getCollabRoomMembers() {
		return this.collabRoomMembers;
	}

	public void setCollabRoomMembers(Set<CollabRoomMember> collabRoomMembers) {
		this.collabRoomMembers = collabRoomMembers;
	}

}
