package com.connectivity.vikray.entity;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CollabRoom generated by hbm2java
 */
@Entity
@Table(name = "COLLAB_ROOM", catalog = "namcrm")
public class CollabRoom implements java.io.Serializable {

	private long id;
	private String roomName;
	private String sparkRoomId;
	private String teamName;

	public CollabRoom() {
	}

	public CollabRoom(long id) {
		this.id = id;
	}

	public CollabRoom(long id, String roomName, String sparkRoomId, String teamName) {
		this.id = id;
		this.roomName = roomName;
		this.sparkRoomId = sparkRoomId;
		this.teamName = teamName;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ROOM_NAME")
	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	@Column(name = "SPARK_ROOM_ID")
	public String getSparkRoomId() {
		return this.sparkRoomId;
	}

	public void setSparkRoomId(String sparkRoomId) {
		this.sparkRoomId = sparkRoomId;
	}

	@Column(name = "TEAM_NAME")
	public String getTeamName() {
		return this.teamName;
	}

	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

}
