package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CollabTeamMember generated by hbm2java
 */
@Entity
@Table(name = "COLLAB_TEAM_MEMBER", catalog = "namcrm")
public class CollabTeamMember implements java.io.Serializable {

	private long id;
	private long domainFk;
	private String sparkTeamMembershipId;
	private long userFk;

	public CollabTeamMember() {
	}

	public CollabTeamMember(long id, long domainFk, long userFk) {
		this.id = id;
		this.domainFk = domainFk;
		this.userFk = userFk;
	}

	public CollabTeamMember(long id, long domainFk, String sparkTeamMembershipId, long userFk) {
		this.id = id;
		this.domainFk = domainFk;
		this.sparkTeamMembershipId = sparkTeamMembershipId;
		this.userFk = userFk;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "DOMAIN_FK", nullable = false)
	public long getDomainFk() {
		return this.domainFk;
	}

	public void setDomainFk(long domainFk) {
		this.domainFk = domainFk;
	}

	@Column(name = "SPARK_TEAM_MEMBERSHIP_ID")
	public String getSparkTeamMembershipId() {
		return this.sparkTeamMembershipId;
	}

	public void setSparkTeamMembershipId(String sparkTeamMembershipId) {
		this.sparkTeamMembershipId = sparkTeamMembershipId;
	}

	@Column(name = "USER_FK", nullable = false)
	public long getUserFk() {
		return this.userFk;
	}

	public void setUserFk(long userFk) {
		this.userFk = userFk;
	}

}
