package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Constant generated by hbm2java
 */
@Entity
@Table(name = "CONSTANT", catalog = "namcrm")
public class Constant implements java.io.Serializable {

	private long id;
	private String json;

	public Constant() {
	}

	public Constant(long id) {
		this.id = id;
	}

	public Constant(long id, String json) {
		this.id = id;
		this.json = json;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "JSON")
	public String getJson() {
		return this.json;
	}

	public void setJson(String json) {
		this.json = json;
	}

}
