package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ContactType generated by hbm2java
 */
@Entity
@Table(name = "CONTACT_TYPE", catalog = "namcrm")
public class ContactType implements java.io.Serializable {

	private long id;
	private String contactType;
	private String description;
	private String parentType;

	public ContactType() {
	}

	public ContactType(long id) {
		this.id = id;
	}

	public ContactType(long id, String contactType, String description, String parentType) {
		this.id = id;
		this.contactType = contactType;
		this.description = description;
		this.parentType = parentType;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CONTACT_TYPE")
	public String getContactType() {
		return this.contactType;
	}

	public void setContactType(String contactType) {
		this.contactType = contactType;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PARENT_TYPE")
	public String getParentType() {
		return this.parentType;
	}

	public void setParentType(String parentType) {
		this.parentType = parentType;
	}

}
