package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "COUNTRIES", catalog = "namcrm")
public class Countries implements java.io.Serializable {

	private long id;
	private String name;
	private String sortname;

	public Countries() {
	}

	public Countries(long id) {
		this.id = id;
	}

	public Countries(long id, String name, String sortname) {
		this.id = id;
		this.name = name;
		this.sortname = sortname;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SORTNAME")
	public String getSortname() {
		return this.sortname;
	}

	public void setSortname(String sortname) {
		this.sortname = sortname;
	}

}
