package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CrmType generated by hbm2java
 */
@Entity
@Table(name = "CRM_TYPE", catalog = "namcrm")
public class CrmType implements java.io.Serializable {

	private long id;
	private String constByName;
	private String name;
	private String parentType;
	private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders = new HashSet<PurchaseOrderHeader>(0);
	private Set<BusinessDeal> businessDealsForBuTypeFk = new HashSet<BusinessDeal>(0);
	private Set<InvoiceHeader> invoiceHeaders = new HashSet<InvoiceHeader>(0);
	private Set<QuoteHeader> quoteHeadersForCrmTypeFk = new HashSet<QuoteHeader>(0);
	private Set<BusinessDeal> businessDealsForCrmTypeFk = new HashSet<BusinessDeal>(0);
	private Set<GrnHeader> grnHeaders = new HashSet<GrnHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForDcTypeFk = new HashSet<DeliveryChallan>(0);
	private Set<SalesOrderHeader> salesOrderHeaders = new HashSet<SalesOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForDcPurposeTypeFk = new HashSet<DeliveryChallan>(0);
	private Set<QuoteHeader> quoteHeadersForFreightTypeCrmFk = new HashSet<QuoteHeader>(0);

	public CrmType() {
	}

	public CrmType(long id) {
		this.id = id;
	}

	public CrmType(long id, String constByName, String name, String parentType, Set<UserDetails> userDetailses,
			Set<PurchaseOrderHeader> purchaseOrderHeaders, Set<BusinessDeal> businessDealsForBuTypeFk,
			Set<InvoiceHeader> invoiceHeaders, Set<QuoteHeader> quoteHeadersForCrmTypeFk,
			Set<BusinessDeal> businessDealsForCrmTypeFk, Set<GrnHeader> grnHeaders,
			Set<DeliveryChallan> deliveryChallansForDcTypeFk, Set<SalesOrderHeader> salesOrderHeaders,
			Set<DeliveryChallan> deliveryChallansForDcPurposeTypeFk, Set<QuoteHeader> quoteHeadersForFreightTypeCrmFk) {
		this.id = id;
		this.constByName = constByName;
		this.name = name;
		this.parentType = parentType;
		this.userDetailses = userDetailses;
		this.purchaseOrderHeaders = purchaseOrderHeaders;
		this.businessDealsForBuTypeFk = businessDealsForBuTypeFk;
		this.invoiceHeaders = invoiceHeaders;
		this.quoteHeadersForCrmTypeFk = quoteHeadersForCrmTypeFk;
		this.businessDealsForCrmTypeFk = businessDealsForCrmTypeFk;
		this.grnHeaders = grnHeaders;
		this.deliveryChallansForDcTypeFk = deliveryChallansForDcTypeFk;
		this.salesOrderHeaders = salesOrderHeaders;
		this.deliveryChallansForDcPurposeTypeFk = deliveryChallansForDcPurposeTypeFk;
		this.quoteHeadersForFreightTypeCrmFk = quoteHeadersForFreightTypeCrmFk;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CONST_BY_NAME")
	public String getConstByName() {
		return this.constByName;
	}

	public void setConstByName(String constByName) {
		this.constByName = constByName;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PARENT_TYPE")
	public String getParentType() {
		return this.parentType;
	}

	public void setParentType(String parentType) {
		this.parentType = parentType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<UserDetails> getUserDetailses() {
		return this.userDetailses;
	}

	public void setUserDetailses(Set<UserDetails> userDetailses) {
		this.userDetailses = userDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders() {
		return this.purchaseOrderHeaders;
	}

	public void setPurchaseOrderHeaders(Set<PurchaseOrderHeader> purchaseOrderHeaders) {
		this.purchaseOrderHeaders = purchaseOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByBuTypeFk")
	public Set<BusinessDeal> getBusinessDealsForBuTypeFk() {
		return this.businessDealsForBuTypeFk;
	}

	public void setBusinessDealsForBuTypeFk(Set<BusinessDeal> businessDealsForBuTypeFk) {
		this.businessDealsForBuTypeFk = businessDealsForBuTypeFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<InvoiceHeader> getInvoiceHeaders() {
		return this.invoiceHeaders;
	}

	public void setInvoiceHeaders(Set<InvoiceHeader> invoiceHeaders) {
		this.invoiceHeaders = invoiceHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByCrmTypeFk")
	public Set<QuoteHeader> getQuoteHeadersForCrmTypeFk() {
		return this.quoteHeadersForCrmTypeFk;
	}

	public void setQuoteHeadersForCrmTypeFk(Set<QuoteHeader> quoteHeadersForCrmTypeFk) {
		this.quoteHeadersForCrmTypeFk = quoteHeadersForCrmTypeFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByCrmTypeFk")
	public Set<BusinessDeal> getBusinessDealsForCrmTypeFk() {
		return this.businessDealsForCrmTypeFk;
	}

	public void setBusinessDealsForCrmTypeFk(Set<BusinessDeal> businessDealsForCrmTypeFk) {
		this.businessDealsForCrmTypeFk = businessDealsForCrmTypeFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<GrnHeader> getGrnHeaders() {
		return this.grnHeaders;
	}

	public void setGrnHeaders(Set<GrnHeader> grnHeaders) {
		this.grnHeaders = grnHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByDcTypeFk")
	public Set<DeliveryChallan> getDeliveryChallansForDcTypeFk() {
		return this.deliveryChallansForDcTypeFk;
	}

	public void setDeliveryChallansForDcTypeFk(Set<DeliveryChallan> deliveryChallansForDcTypeFk) {
		this.deliveryChallansForDcTypeFk = deliveryChallansForDcTypeFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmType")
	public Set<SalesOrderHeader> getSalesOrderHeaders() {
		return this.salesOrderHeaders;
	}

	public void setSalesOrderHeaders(Set<SalesOrderHeader> salesOrderHeaders) {
		this.salesOrderHeaders = salesOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByDcPurposeTypeFk")
	public Set<DeliveryChallan> getDeliveryChallansForDcPurposeTypeFk() {
		return this.deliveryChallansForDcPurposeTypeFk;
	}

	public void setDeliveryChallansForDcPurposeTypeFk(Set<DeliveryChallan> deliveryChallansForDcPurposeTypeFk) {
		this.deliveryChallansForDcPurposeTypeFk = deliveryChallansForDcPurposeTypeFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crmTypeByFreightTypeCrmFk")
	public Set<QuoteHeader> getQuoteHeadersForFreightTypeCrmFk() {
		return this.quoteHeadersForFreightTypeCrmFk;
	}

	public void setQuoteHeadersForFreightTypeCrmFk(Set<QuoteHeader> quoteHeadersForFreightTypeCrmFk) {
		this.quoteHeadersForFreightTypeCrmFk = quoteHeadersForFreightTypeCrmFk;
	}

}
