package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customisation generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMISATION", catalog = "namcrm")
public class Customisation implements java.io.Serializable {

	private long id;
	private String values;

	public Customisation() {
	}

	public Customisation(long id) {
		this.id = id;
	}

	public Customisation(long id, String values) {
		this.id = id;
		this.values = values;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "VALUES", length = 16777215)
	public String getValues() {
		return this.values;
	}

	public void setValues(String values) {
		this.values = values;
	}

}
