package com.connectivity.vikray.entity;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DealSource generated by hbm2java
 */
@Entity
@Table(name = "DEAL_SOURCE", catalog = "namcrm")
public class DealSource implements java.io.Serializable {

	private long id;
	private String name;
	private Set<BusinessDeal> businessDeals = new HashSet<BusinessDeal>(0);
	private Set<BusinessDeal> businessDeals_1 = new HashSet<BusinessDeal>(0);

	public DealSource() {
	}

	public DealSource(long id) {
		this.id = id;
	}

	public DealSource(long id, String name, Set<BusinessDeal> businessDeals, Set<BusinessDeal> businessDeals_1) {
		this.id = id;
		this.name = name;
		this.businessDeals = businessDeals;
		this.businessDeals_1 = businessDeals_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealSource")
	public Set<BusinessDeal> getBusinessDeals() {
		return this.businessDeals;
	}

	public void setBusinessDeals(Set<BusinessDeal> businessDeals) {
		this.businessDeals = businessDeals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealSource")
	public Set<BusinessDeal> getBusinessDeals_1() {
		return this.businessDeals_1;
	}

	public void setBusinessDeals_1(Set<BusinessDeal> businessDeals_1) {
		this.businessDeals_1 = businessDeals_1;
	}

}
