package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DealActivity generated by hbm2java
 */
@Entity
@Table(name = "DEAL_ACTIVITY", catalog = "namcrm")
public class DealActivity implements java.io.Serializable {

	private long id;
	private BusinessDeal businessDeal;
	private UserDetails userDetails;
	private Date activityOn;
	private String comment;
	private String medium;
	private String sincedays;
	private Set<BusinessDeal> businessDeals = new HashSet<BusinessDeal>(0);

	public DealActivity() {
	}

	public DealActivity(long id) {
		this.id = id;
	}

	public DealActivity(long id, BusinessDeal businessDeal, UserDetails userDetails, Date activityOn, String comment,
			String medium, String sincedays, Set<BusinessDeal> businessDeals) {
		this.id = id;
		this.businessDeal = businessDeal;
		this.userDetails = userDetails;
		this.activityOn = activityOn;
		this.comment = comment;
		this.medium = medium;
		this.sincedays = sincedays;
		this.businessDeals = businessDeals;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEAL_FK")
	public BusinessDeal getBusinessDeal() {
		return this.businessDeal;
	}

	public void setBusinessDeal(BusinessDeal businessDeal) {
		this.businessDeal = businessDeal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER")
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTIVITY_ON", length = 19)
	public Date getActivityOn() {
		return this.activityOn;
	}

	public void setActivityOn(Date activityOn) {
		this.activityOn = activityOn;
	}

	@Column(name = "COMMENT")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "MEDIUM")
	public String getMedium() {
		return this.medium;
	}

	public void setMedium(String medium) {
		this.medium = medium;
	}

	@Column(name = "SINCEDAYS")
	public String getSincedays() {
		return this.sincedays;
	}

	public void setSincedays(String sincedays) {
		this.sincedays = sincedays;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealActivity")
	public Set<BusinessDeal> getBusinessDeals() {
		return this.businessDeals;
	}

	public void setBusinessDeals(Set<BusinessDeal> businessDeals) {
		this.businessDeals = businessDeals;
	}

}
