package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DealFollower generated by hbm2java
 */
@Entity
@Table(name = "DEAL_FOLLOWER", catalog = "namcrm")
public class DealFollower implements java.io.Serializable {

	private long id;
	private BusinessDeal businessDeal;
	private UserDetails userDetails;

	public DealFollower() {
	}

	public DealFollower(long id) {
		this.id = id;
	}

	public DealFollower(long id, BusinessDeal businessDeal, UserDetails userDetails) {
		this.id = id;
		this.businessDeal = businessDeal;
		this.userDetails = userDetails;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEAL_FK")
	public BusinessDeal getBusinessDeal() {
		return this.businessDeal;
	}

	public void setBusinessDeal(BusinessDeal businessDeal) {
		this.businessDeal = businessDeal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_FK")
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

}
