package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DealDoc generated by hbm2java
 */
@Entity
@Table(name = "DEAL_DOC", catalog = "namcrm")
public class DealDoc implements java.io.Serializable {

	private long id;
	private BusinessDeal businessDeal;
	private long dateUploaded;
	private String url;

	public DealDoc() {
	}

	public DealDoc(long id, long dateUploaded) {
		this.id = id;
		this.dateUploaded = dateUploaded;
	}

	public DealDoc(long id, BusinessDeal businessDeal, long dateUploaded, String url) {
		this.id = id;
		this.businessDeal = businessDeal;
		this.dateUploaded = dateUploaded;
		this.url = url;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEAL_FK")
	public BusinessDeal getBusinessDeal() {
		return this.businessDeal;
	}

	public void setBusinessDeal(BusinessDeal businessDeal) {
		this.businessDeal = businessDeal;
	}

	@Column(name = "DATE_UPLOADED", nullable = false)
	public long getDateUploaded() {
		return this.dateUploaded;
	}

	public void setDateUploaded(long dateUploaded) {
		this.dateUploaded = dateUploaded;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
