package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Deleteme1493810137718 generated by hbm2java
 */
@Entity
@Table(name = "DELETEME1493810137718", catalog = "namcrm")
public class Deleteme1493810137718 implements java.io.Serializable {

	private int unused;

	public Deleteme1493810137718() {
	}

	public Deleteme1493810137718(int unused) {
		this.unused = unused;
	}

	@Id

	@Column(name = "UNUSED", nullable = false)
	public int getUnused() {
		return this.unused;
	}

	public void setUnused(int unused) {
		this.unused = unused;
	}

}
