package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DeliveryChallanItem generated by hbm2java
 */
@Entity
@Table(name = "DELIVERY_CHALLAN_ITEM", catalog = "namcrm")
public class DeliveryChallanItem implements java.io.Serializable {

	private long id;
	private DeliveryChallan deliveryChallan;
	private InventoryItem inventoryItem;
	private QuoteItem quoteItem;
	private int deliveredQuantity;
	private double extendedPrice;
	private String itemDescription;
	private String itemName;
	private double outGoingUnitPrice;
	private double priceWithTax;
	private double taxAmount;
	private double taxPercentage;
	private String taxType;
	private String uom;
	private String slNo;
	private String productSerialNo;
	private double sgstRate;
	private double igstRate;
	private double cgstRate;
	private String hsnCode;
	private double cgstAmount;
	private double igstAmount;
	private double sgstAmount;
	private double amount;
	private int recievedQty;

	public DeliveryChallanItem() {
	}

	public DeliveryChallanItem(long id, int deliveredQuantity, double extendedPrice, double outGoingUnitPrice,
			double priceWithTax, double taxAmount, double taxPercentage, double sgstRate, double igstRate,
			double cgstRate, double cgstAmount, double igstAmount, double sgstAmount, double amount, int recievedQty) {
		this.id = id;
		this.deliveredQuantity = deliveredQuantity;
		this.extendedPrice = extendedPrice;
		this.outGoingUnitPrice = outGoingUnitPrice;
		this.priceWithTax = priceWithTax;
		this.taxAmount = taxAmount;
		this.taxPercentage = taxPercentage;
		this.sgstRate = sgstRate;
		this.igstRate = igstRate;
		this.cgstRate = cgstRate;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.sgstAmount = sgstAmount;
		this.amount = amount;
		this.recievedQty = recievedQty;
	}

	public DeliveryChallanItem(long id, DeliveryChallan deliveryChallan, InventoryItem inventoryItem,
			QuoteItem quoteItem, int deliveredQuantity, double extendedPrice, String itemDescription, String itemName,
			double outGoingUnitPrice, double priceWithTax, double taxAmount, double taxPercentage, String taxType,
			String uom, String slNo, String productSerialNo, double sgstRate, double igstRate, double cgstRate,
			String hsnCode, double cgstAmount, double igstAmount, double sgstAmount, double amount, int recievedQty) {
		this.id = id;
		this.deliveryChallan = deliveryChallan;
		this.inventoryItem = inventoryItem;
		this.quoteItem = quoteItem;
		this.deliveredQuantity = deliveredQuantity;
		this.extendedPrice = extendedPrice;
		this.itemDescription = itemDescription;
		this.itemName = itemName;
		this.outGoingUnitPrice = outGoingUnitPrice;
		this.priceWithTax = priceWithTax;
		this.taxAmount = taxAmount;
		this.taxPercentage = taxPercentage;
		this.taxType = taxType;
		this.uom = uom;
		this.slNo = slNo;
		this.productSerialNo = productSerialNo;
		this.sgstRate = sgstRate;
		this.igstRate = igstRate;
		this.cgstRate = cgstRate;
		this.hsnCode = hsnCode;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.sgstAmount = sgstAmount;
		this.amount = amount;
		this.recievedQty = recievedQty;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DELIVERY_CHALLAN_FK")
	public DeliveryChallan getDeliveryChallan() {
		return this.deliveryChallan;
	}

	public void setDeliveryChallan(DeliveryChallan deliveryChallan) {
		this.deliveryChallan = deliveryChallan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVENTORY_ITEM_FK")
	public InventoryItem getInventoryItem() {
		return this.inventoryItem;
	}

	public void setInventoryItem(InventoryItem inventoryItem) {
		this.inventoryItem = inventoryItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUOTE_ITEM_FK")
	public QuoteItem getQuoteItem() {
		return this.quoteItem;
	}

	public void setQuoteItem(QuoteItem quoteItem) {
		this.quoteItem = quoteItem;
	}

	@Column(name = "DELIVERED_QUANTITY", nullable = false)
	public int getDeliveredQuantity() {
		return this.deliveredQuantity;
	}

	public void setDeliveredQuantity(int deliveredQuantity) {
		this.deliveredQuantity = deliveredQuantity;
	}

	@Column(name = "EXTENDED_PRICE", nullable = false, precision = 22, scale = 0)
	public double getExtendedPrice() {
		return this.extendedPrice;
	}

	public void setExtendedPrice(double extendedPrice) {
		this.extendedPrice = extendedPrice;
	}

	@Column(name = "ITEM_DESCRIPTION", length = 16777215)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "ITEM_NAME")
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "OUT_GOING_UNIT_PRICE", nullable = false, precision = 22, scale = 0)
	public double getOutGoingUnitPrice() {
		return this.outGoingUnitPrice;
	}

	public void setOutGoingUnitPrice(double outGoingUnitPrice) {
		this.outGoingUnitPrice = outGoingUnitPrice;
	}

	@Column(name = "PRICE_WITH_TAX", nullable = false, precision = 22, scale = 0)
	public double getPriceWithTax() {
		return this.priceWithTax;
	}

	public void setPriceWithTax(double priceWithTax) {
		this.priceWithTax = priceWithTax;
	}

	@Column(name = "TAX_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(double taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "TAX_PERCENTAGE", nullable = false, precision = 22, scale = 0)
	public double getTaxPercentage() {
		return this.taxPercentage;
	}

	public void setTaxPercentage(double taxPercentage) {
		this.taxPercentage = taxPercentage;
	}

	@Column(name = "TAX_TYPE")
	public String getTaxType() {
		return this.taxType;
	}

	public void setTaxType(String taxType) {
		this.taxType = taxType;
	}

	@Column(name = "UOM")
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	@Column(name = "SL_NO")
	public String getSlNo() {
		return this.slNo;
	}

	public void setSlNo(String slNo) {
		this.slNo = slNo;
	}

	@Column(name = "PRODUCT_SERIAL_NO")
	public String getProductSerialNo() {
		return this.productSerialNo;
	}

	public void setProductSerialNo(String productSerialNo) {
		this.productSerialNo = productSerialNo;
	}

	@Column(name = "SGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getSgstRate() {
		return this.sgstRate;
	}

	public void setSgstRate(double sgstRate) {
		this.sgstRate = sgstRate;
	}

	@Column(name = "IGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getIgstRate() {
		return this.igstRate;
	}

	public void setIgstRate(double igstRate) {
		this.igstRate = igstRate;
	}

	@Column(name = "CGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getCgstRate() {
		return this.cgstRate;
	}

	public void setCgstRate(double cgstRate) {
		this.cgstRate = cgstRate;
	}

	@Column(name = "HSN_CODE")
	public String getHsnCode() {
		return this.hsnCode;
	}

	public void setHsnCode(String hsnCode) {
		this.hsnCode = hsnCode;
	}

	@Column(name = "CGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getCgstAmount() {
		return this.cgstAmount;
	}

	public void setCgstAmount(double cgstAmount) {
		this.cgstAmount = cgstAmount;
	}

	@Column(name = "IGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getIgstAmount() {
		return this.igstAmount;
	}

	public void setIgstAmount(double igstAmount) {
		this.igstAmount = igstAmount;
	}

	@Column(name = "SGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getSgstAmount() {
		return this.sgstAmount;
	}

	public void setSgstAmount(double sgstAmount) {
		this.sgstAmount = sgstAmount;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "RECIEVED_QTY", nullable = false)
	public int getRecievedQty() {
		return this.recievedQty;
	}

	public void setRecievedQty(int recievedQty) {
		this.recievedQty = recievedQty;
	}

}
