package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ErpAlerts generated by hbm2java
 */
@Entity
@Table(name = "ERP_ALERTS", catalog = "namcrm")
public class ErpAlerts implements java.io.Serializable {

	private long id;
	private String msg;
	private String urlLabel;
	private long days;
	private String url;

	public ErpAlerts() {
	}

	public ErpAlerts(long id, long days) {
		this.id = id;
		this.days = days;
	}

	public ErpAlerts(long id, String msg, String urlLabel, long days, String url) {
		this.id = id;
		this.msg = msg;
		this.urlLabel = urlLabel;
		this.days = days;
		this.url = url;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "MSG")
	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	@Column(name = "URL_LABEL")
	public String getUrlLabel() {
		return this.urlLabel;
	}

	public void setUrlLabel(String urlLabel) {
		this.urlLabel = urlLabel;
	}

	@Column(name = "DAYS", nullable = false)
	public long getDays() {
		return this.days;
	}

	public void setDays(long days) {
		this.days = days;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
