package com.connectivity.vikray.entity;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderItem generated by hbm2java
 */
@Entity
@Table(name = "ORDER_ITEM", catalog = "namcrm")
public class OrderItem implements java.io.Serializable {

	private long id;
	private AccountDetail accountDetail;
	private InventoryItem inventoryItem;
	private PersonDetail personDetail;
	private Product product;
	private PurchaseOrderHeader purchaseOrderHeader;
	private QuoteItem quoteItem;
	private SalesOrderHeader salesOrderHeader;
	private double extendedPrice;
	private double incomingUnitPrice;
	private boolean isServiceItem;
	private String itemDescription;
	private String itemName;
	private double marginAmount;
	private double outGoingUnitPrice;
	private int pendingReceivedQuantity;
	private double priceWithTax;
	private double purchaseAmount;
	private int quantity;
	private int receivedQuantity;
	private double taxAmount;
	private double taxPercentage;
	private String taxType;
	private String uom;
	private int vendorPaymentTermsDays;
	private String vendorQuoteNo;
	private String slNo;
	private double profit;
	private double sgstRate;
	private double igstRate;
	private int reservedquantity;
	private double cgstRate;
	private double cgstAmount;
	private String hsnCode;
	private double igstAmount;
	private double sgstAmount;
	private int poQuantiy;
	private int pendingPoQuantity;
	private Date serviceStartDate;
	private Date serviceEndDate;
	private Set<QuoteItem> quoteItems = new HashSet<QuoteItem>(0);
	private Set<QuoteItem> quoteItems_1 = new HashSet<QuoteItem>(0);
	private Set<GrnItem> grnItems = new HashSet<GrnItem>(0);
	private Set<GrnItem> grnItems_1 = new HashSet<GrnItem>(0);

	public OrderItem() {
	}

	public OrderItem(long id, double extendedPrice, double incomingUnitPrice, boolean isServiceItem,
			double marginAmount, double outGoingUnitPrice, int pendingReceivedQuantity, double priceWithTax,
			double purchaseAmount, int quantity, int receivedQuantity, double taxAmount, double taxPercentage,
			int vendorPaymentTermsDays, double profit, double sgstRate, double igstRate, int reservedquantity,
			double cgstRate, double cgstAmount, double igstAmount, double sgstAmount, int poQuantiy,
			int pendingPoQuantity) {
		this.id = id;
		this.extendedPrice = extendedPrice;
		this.incomingUnitPrice = incomingUnitPrice;
		this.isServiceItem = isServiceItem;
		this.marginAmount = marginAmount;
		this.outGoingUnitPrice = outGoingUnitPrice;
		this.pendingReceivedQuantity = pendingReceivedQuantity;
		this.priceWithTax = priceWithTax;
		this.purchaseAmount = purchaseAmount;
		this.quantity = quantity;
		this.receivedQuantity = receivedQuantity;
		this.taxAmount = taxAmount;
		this.taxPercentage = taxPercentage;
		this.vendorPaymentTermsDays = vendorPaymentTermsDays;
		this.profit = profit;
		this.sgstRate = sgstRate;
		this.igstRate = igstRate;
		this.reservedquantity = reservedquantity;
		this.cgstRate = cgstRate;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.sgstAmount = sgstAmount;
		this.poQuantiy = poQuantiy;
		this.pendingPoQuantity = pendingPoQuantity;
	}

	public OrderItem(long id, AccountDetail accountDetail, InventoryItem inventoryItem, PersonDetail personDetail,
			Product product, PurchaseOrderHeader purchaseOrderHeader, QuoteItem quoteItem,
			SalesOrderHeader salesOrderHeader, double extendedPrice, double incomingUnitPrice, boolean isServiceItem,
			String itemDescription, String itemName, double marginAmount, double outGoingUnitPrice,
			int pendingReceivedQuantity, double priceWithTax, double purchaseAmount, int quantity, int receivedQuantity,
			double taxAmount, double taxPercentage, String taxType, String uom, int vendorPaymentTermsDays,
			String vendorQuoteNo, String slNo, double profit, double sgstRate, double igstRate, int reservedquantity,
			double cgstRate, double cgstAmount, String hsnCode, double igstAmount, double sgstAmount, int poQuantiy,
			int pendingPoQuantity, Date serviceStartDate, Date serviceEndDate, Set<QuoteItem> quoteItems,
			Set<QuoteItem> quoteItems_1, Set<GrnItem> grnItems, Set<GrnItem> grnItems_1) {
		this.id = id;
		this.accountDetail = accountDetail;
		this.inventoryItem = inventoryItem;
		this.personDetail = personDetail;
		this.product = product;
		this.purchaseOrderHeader = purchaseOrderHeader;
		this.quoteItem = quoteItem;
		this.salesOrderHeader = salesOrderHeader;
		this.extendedPrice = extendedPrice;
		this.incomingUnitPrice = incomingUnitPrice;
		this.isServiceItem = isServiceItem;
		this.itemDescription = itemDescription;
		this.itemName = itemName;
		this.marginAmount = marginAmount;
		this.outGoingUnitPrice = outGoingUnitPrice;
		this.pendingReceivedQuantity = pendingReceivedQuantity;
		this.priceWithTax = priceWithTax;
		this.purchaseAmount = purchaseAmount;
		this.quantity = quantity;
		this.receivedQuantity = receivedQuantity;
		this.taxAmount = taxAmount;
		this.taxPercentage = taxPercentage;
		this.taxType = taxType;
		this.uom = uom;
		this.vendorPaymentTermsDays = vendorPaymentTermsDays;
		this.vendorQuoteNo = vendorQuoteNo;
		this.slNo = slNo;
		this.profit = profit;
		this.sgstRate = sgstRate;
		this.igstRate = igstRate;
		this.reservedquantity = reservedquantity;
		this.cgstRate = cgstRate;
		this.cgstAmount = cgstAmount;
		this.hsnCode = hsnCode;
		this.igstAmount = igstAmount;
		this.sgstAmount = sgstAmount;
		this.poQuantiy = poQuantiy;
		this.pendingPoQuantity = pendingPoQuantity;
		this.serviceStartDate = serviceStartDate;
		this.serviceEndDate = serviceEndDate;
		this.quoteItems = quoteItems;
		this.quoteItems_1 = quoteItems_1;
		this.grnItems = grnItems;
		this.grnItems_1 = grnItems_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VENDOR_ACCOUNT_FK")
	public AccountDetail getAccountDetail() {
		return this.accountDetail;
	}

	public void setAccountDetail(AccountDetail accountDetail) {
		this.accountDetail = accountDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVENTORY_ITEM_FK")
	public InventoryItem getInventoryItem() {
		return this.inventoryItem;
	}

	public void setInventoryItem(InventoryItem inventoryItem) {
		this.inventoryItem = inventoryItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VENDOR_CONTACT_PERSON_FK")
	public PersonDetail getPersonDetail() {
		return this.personDetail;
	}

	public void setPersonDetail(PersonDetail personDetail) {
		this.personDetail = personDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_FK")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PURCHASE_ORDER_FK")
	public PurchaseOrderHeader getPurchaseOrderHeader() {
		return this.purchaseOrderHeader;
	}

	public void setPurchaseOrderHeader(PurchaseOrderHeader purchaseOrderHeader) {
		this.purchaseOrderHeader = purchaseOrderHeader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUOTE_ITEM_FK")
	public QuoteItem getQuoteItem() {
		return this.quoteItem;
	}

	public void setQuoteItem(QuoteItem quoteItem) {
		this.quoteItem = quoteItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SALES_ORDER_FK")
	public SalesOrderHeader getSalesOrderHeader() {
		return this.salesOrderHeader;
	}

	public void setSalesOrderHeader(SalesOrderHeader salesOrderHeader) {
		this.salesOrderHeader = salesOrderHeader;
	}

	@Column(name = "EXTENDED_PRICE", nullable = false, precision = 22, scale = 0)
	public double getExtendedPrice() {
		return this.extendedPrice;
	}

	public void setExtendedPrice(double extendedPrice) {
		this.extendedPrice = extendedPrice;
	}

	@Column(name = "INCOMING_UNIT_PRICE", nullable = false, precision = 22, scale = 0)
	public double getIncomingUnitPrice() {
		return this.incomingUnitPrice;
	}

	public void setIncomingUnitPrice(double incomingUnitPrice) {
		this.incomingUnitPrice = incomingUnitPrice;
	}

	@Column(name = "IS_SERVICE_ITEM", nullable = false)
	public boolean isIsServiceItem() {
		return this.isServiceItem;
	}

	public void setIsServiceItem(boolean isServiceItem) {
		this.isServiceItem = isServiceItem;
	}

	@Column(name = "ITEM_DESCRIPTION", length = 16777215)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "ITEM_NAME")
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "MARGIN_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getMarginAmount() {
		return this.marginAmount;
	}

	public void setMarginAmount(double marginAmount) {
		this.marginAmount = marginAmount;
	}

	@Column(name = "OUT-GOING_UNIT_PRICE", nullable = false, precision = 22, scale = 0)
	public double getOutGoingUnitPrice() {
		return this.outGoingUnitPrice;
	}

	public void setOutGoingUnitPrice(double outGoingUnitPrice) {
		this.outGoingUnitPrice = outGoingUnitPrice;
	}

	@Column(name = "PENDING_RECEIVED_QUANTITY", nullable = false)
	public int getPendingReceivedQuantity() {
		return this.pendingReceivedQuantity;
	}

	public void setPendingReceivedQuantity(int pendingReceivedQuantity) {
		this.pendingReceivedQuantity = pendingReceivedQuantity;
	}

	@Column(name = "PRICE_WITH_TAX", nullable = false, precision = 22, scale = 0)
	public double getPriceWithTax() {
		return this.priceWithTax;
	}

	public void setPriceWithTax(double priceWithTax) {
		this.priceWithTax = priceWithTax;
	}

	@Column(name = "PURCHASE_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getPurchaseAmount() {
		return this.purchaseAmount;
	}

	public void setPurchaseAmount(double purchaseAmount) {
		this.purchaseAmount = purchaseAmount;
	}

	@Column(name = "QUANTITY", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "RECEIVED_QUANTITY", nullable = false)
	public int getReceivedQuantity() {
		return this.receivedQuantity;
	}

	public void setReceivedQuantity(int receivedQuantity) {
		this.receivedQuantity = receivedQuantity;
	}

	@Column(name = "TAX_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(double taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "TAX_PERCENTAGE", nullable = false, precision = 22, scale = 0)
	public double getTaxPercentage() {
		return this.taxPercentage;
	}

	public void setTaxPercentage(double taxPercentage) {
		this.taxPercentage = taxPercentage;
	}

	@Column(name = "TAX_TYPE")
	public String getTaxType() {
		return this.taxType;
	}

	public void setTaxType(String taxType) {
		this.taxType = taxType;
	}

	@Column(name = "UOM")
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	@Column(name = "VENDOR_PAYMENT_TERMS_DAYS", nullable = false)
	public int getVendorPaymentTermsDays() {
		return this.vendorPaymentTermsDays;
	}

	public void setVendorPaymentTermsDays(int vendorPaymentTermsDays) {
		this.vendorPaymentTermsDays = vendorPaymentTermsDays;
	}

	@Column(name = "VENDOR_QUOTE_NO")
	public String getVendorQuoteNo() {
		return this.vendorQuoteNo;
	}

	public void setVendorQuoteNo(String vendorQuoteNo) {
		this.vendorQuoteNo = vendorQuoteNo;
	}

	@Column(name = "SL_NO")
	public String getSlNo() {
		return this.slNo;
	}

	public void setSlNo(String slNo) {
		this.slNo = slNo;
	}

	@Column(name = "PROFIT", nullable = false, precision = 22, scale = 0)
	public double getProfit() {
		return this.profit;
	}

	public void setProfit(double profit) {
		this.profit = profit;
	}

	@Column(name = "SGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getSgstRate() {
		return this.sgstRate;
	}

	public void setSgstRate(double sgstRate) {
		this.sgstRate = sgstRate;
	}

	@Column(name = "IGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getIgstRate() {
		return this.igstRate;
	}

	public void setIgstRate(double igstRate) {
		this.igstRate = igstRate;
	}

	@Column(name = "RESERVEDQUANTITY", nullable = false)
	public int getReservedquantity() {
		return this.reservedquantity;
	}

	public void setReservedquantity(int reservedquantity) {
		this.reservedquantity = reservedquantity;
	}

	@Column(name = "CGST_RATE", nullable = false, precision = 22, scale = 0)
	public double getCgstRate() {
		return this.cgstRate;
	}

	public void setCgstRate(double cgstRate) {
		this.cgstRate = cgstRate;
	}

	@Column(name = "CGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getCgstAmount() {
		return this.cgstAmount;
	}

	public void setCgstAmount(double cgstAmount) {
		this.cgstAmount = cgstAmount;
	}

	@Column(name = "HSN_CODE")
	public String getHsnCode() {
		return this.hsnCode;
	}

	public void setHsnCode(String hsnCode) {
		this.hsnCode = hsnCode;
	}

	@Column(name = "IGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getIgstAmount() {
		return this.igstAmount;
	}

	public void setIgstAmount(double igstAmount) {
		this.igstAmount = igstAmount;
	}

	@Column(name = "SGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getSgstAmount() {
		return this.sgstAmount;
	}

	public void setSgstAmount(double sgstAmount) {
		this.sgstAmount = sgstAmount;
	}

	@Column(name = "PO_QUANTIY", nullable = false)
	public int getPoQuantiy() {
		return this.poQuantiy;
	}

	public void setPoQuantiy(int poQuantiy) {
		this.poQuantiy = poQuantiy;
	}

	@Column(name = "PENDING_PO_QUANTITY", nullable = false)
	public int getPendingPoQuantity() {
		return this.pendingPoQuantity;
	}

	public void setPendingPoQuantity(int pendingPoQuantity) {
		this.pendingPoQuantity = pendingPoQuantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SERVICE_START_DATE", length = 19)
	public Date getServiceStartDate() {
		return this.serviceStartDate;
	}

	public void setServiceStartDate(Date serviceStartDate) {
		this.serviceStartDate = serviceStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SERVICE_END_DATE", length = 19)
	public Date getServiceEndDate() {
		return this.serviceEndDate;
	}

	public void setServiceEndDate(Date serviceEndDate) {
		this.serviceEndDate = serviceEndDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderItem")
	public Set<QuoteItem> getQuoteItems() {
		return this.quoteItems;
	}

	public void setQuoteItems(Set<QuoteItem> quoteItems) {
		this.quoteItems = quoteItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderItem")
	public Set<QuoteItem> getQuoteItems_1() {
		return this.quoteItems_1;
	}

	public void setQuoteItems_1(Set<QuoteItem> quoteItems_1) {
		this.quoteItems_1 = quoteItems_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderItem")
	public Set<GrnItem> getGrnItems() {
		return this.grnItems;
	}

	public void setGrnItems(Set<GrnItem> grnItems) {
		this.grnItems = grnItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderItem")
	public Set<GrnItem> getGrnItems_1() {
		return this.grnItems_1;
	}

	public void setGrnItems_1(Set<GrnItem> grnItems_1) {
		this.grnItems_1 = grnItems_1;
	}

}
