package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrganisationPhone generated by hbm2java
 */
@Entity
@Table(name = "ORGANISATION_PHONE", catalog = "namcrm")
public class OrganisationPhone implements java.io.Serializable {

	private long id;
	private OrganisationAddress organisationAddress;
	private String number;

	public OrganisationPhone() {
	}

	public OrganisationPhone(long id) {
		this.id = id;
	}

	public OrganisationPhone(long id, OrganisationAddress organisationAddress, String number) {
		this.id = id;
		this.organisationAddress = organisationAddress;
		this.number = number;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORG_ADDRESS_FK")
	public OrganisationAddress getOrganisationAddress() {
		return this.organisationAddress;
	}

	public void setOrganisationAddress(OrganisationAddress organisationAddress) {
		this.organisationAddress = organisationAddress;
	}

	@Column(name = "NUMBER")
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

}
