package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Organisation generated by hbm2java
 */
@Entity
@Table(name = "ORGANISATION", catalog = "namcrm")
public class Organisation implements java.io.Serializable {

	private long id;
	private Domain domain;
	private String orgId;
	private String orgName;
	private boolean isdisabled;
	private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders = new HashSet<PurchaseOrderHeader>(0);
	private Set<QuoteHeader> quoteHeaders = new HashSet<QuoteHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeaders = new HashSet<SalesOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallans = new HashSet<DeliveryChallan>(0);
	private Set<FinancialReport> financialReports = new HashSet<FinancialReport>(0);
	private Set<OrganisationAddress> organisationAddresses = new HashSet<OrganisationAddress>(0);
	private Set<InvoiceHeader> invoiceHeaders = new HashSet<InvoiceHeader>(0);
	private Set<PurchaseEntry> purchaseEntries = new HashSet<PurchaseEntry>(0);
	private Set<OrgLocation> orgLocations = new HashSet<OrgLocation>(0);
	private Set<GrnHeader> grnHeaders = new HashSet<GrnHeader>(0);

	public Organisation() {
	}

	public Organisation(long id, boolean isdisabled) {
		this.id = id;
		this.isdisabled = isdisabled;
	}

	public Organisation(long id, Domain domain, String orgId, String orgName, boolean isdisabled,
			Set<UserDetails> userDetailses, Set<PurchaseOrderHeader> purchaseOrderHeaders,
			Set<QuoteHeader> quoteHeaders, Set<SalesOrderHeader> salesOrderHeaders,
			Set<DeliveryChallan> deliveryChallans, Set<FinancialReport> financialReports,
			Set<OrganisationAddress> organisationAddresses, Set<InvoiceHeader> invoiceHeaders,
			Set<PurchaseEntry> purchaseEntries, Set<OrgLocation> orgLocations, Set<GrnHeader> grnHeaders) {
		this.id = id;
		this.domain = domain;
		this.orgId = orgId;
		this.orgName = orgName;
		this.isdisabled = isdisabled;
		this.userDetailses = userDetailses;
		this.purchaseOrderHeaders = purchaseOrderHeaders;
		this.quoteHeaders = quoteHeaders;
		this.salesOrderHeaders = salesOrderHeaders;
		this.deliveryChallans = deliveryChallans;
		this.financialReports = financialReports;
		this.organisationAddresses = organisationAddresses;
		this.invoiceHeaders = invoiceHeaders;
		this.purchaseEntries = purchaseEntries;
		this.orgLocations = orgLocations;
		this.grnHeaders = grnHeaders;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN_FK")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@Column(name = "ORG_ID")
	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Column(name = "ORG_NAME")
	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	@Column(name = "ISDISABLED", nullable = false)
	public boolean isIsdisabled() {
		return this.isdisabled;
	}

	public void setIsdisabled(boolean isdisabled) {
		this.isdisabled = isdisabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<UserDetails> getUserDetailses() {
		return this.userDetailses;
	}

	public void setUserDetailses(Set<UserDetails> userDetailses) {
		this.userDetailses = userDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders() {
		return this.purchaseOrderHeaders;
	}

	public void setPurchaseOrderHeaders(Set<PurchaseOrderHeader> purchaseOrderHeaders) {
		this.purchaseOrderHeaders = purchaseOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<QuoteHeader> getQuoteHeaders() {
		return this.quoteHeaders;
	}

	public void setQuoteHeaders(Set<QuoteHeader> quoteHeaders) {
		this.quoteHeaders = quoteHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<SalesOrderHeader> getSalesOrderHeaders() {
		return this.salesOrderHeaders;
	}

	public void setSalesOrderHeaders(Set<SalesOrderHeader> salesOrderHeaders) {
		this.salesOrderHeaders = salesOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<DeliveryChallan> getDeliveryChallans() {
		return this.deliveryChallans;
	}

	public void setDeliveryChallans(Set<DeliveryChallan> deliveryChallans) {
		this.deliveryChallans = deliveryChallans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<FinancialReport> getFinancialReports() {
		return this.financialReports;
	}

	public void setFinancialReports(Set<FinancialReport> financialReports) {
		this.financialReports = financialReports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<OrganisationAddress> getOrganisationAddresses() {
		return this.organisationAddresses;
	}

	public void setOrganisationAddresses(Set<OrganisationAddress> organisationAddresses) {
		this.organisationAddresses = organisationAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<InvoiceHeader> getInvoiceHeaders() {
		return this.invoiceHeaders;
	}

	public void setInvoiceHeaders(Set<InvoiceHeader> invoiceHeaders) {
		this.invoiceHeaders = invoiceHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<PurchaseEntry> getPurchaseEntries() {
		return this.purchaseEntries;
	}

	public void setPurchaseEntries(Set<PurchaseEntry> purchaseEntries) {
		this.purchaseEntries = purchaseEntries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<OrgLocation> getOrgLocations() {
		return this.orgLocations;
	}

	public void setOrgLocations(Set<OrgLocation> orgLocations) {
		this.orgLocations = orgLocations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organisation")
	public Set<GrnHeader> getGrnHeaders() {
		return this.grnHeaders;
	}

	public void setGrnHeaders(Set<GrnHeader> grnHeaders) {
		this.grnHeaders = grnHeaders;
	}

}
