package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrganisationEmail generated by hbm2java
 */
@Entity
@Table(name = "ORGANISATION_EMAIL", catalog = "namcrm")
public class OrganisationEmail implements java.io.Serializable {

	private long id;
	private OrgLocation orgLocation;
	private String email;

	public OrganisationEmail() {
	}

	public OrganisationEmail(long id) {
		this.id = id;
	}

	public OrganisationEmail(long id, OrgLocation orgLocation, String email) {
		this.id = id;
		this.orgLocation = orgLocation;
		this.email = email;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORG_LOCATION_FK")
	public OrgLocation getOrgLocation() {
		return this.orgLocation;
	}

	public void setOrgLocation(OrgLocation orgLocation) {
		this.orgLocation = orgLocation;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
