package com.connectivity.vikray.entity;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrgBankDetail generated by hbm2java
 */
@Entity
@Table(name = "ORG_BANK_DETAIL", catalog = "namcrm")
public class OrgBankDetail implements java.io.Serializable {

	private long id;
	private OrgLocation orgLocation;
	private String accountNumber;
	private String accountType;
	private String bankAddress;
	private String bankBranch;
	private String bankName;
	private String ifscCode;
	private String micrCode;
	private String swiftCode;
	private String description;
	private Set<QuoteHeader> quoteHeaders = new HashSet<QuoteHeader>(0);
	private Set<InvoiceHeader> invoiceHeaders = new HashSet<InvoiceHeader>(0);
	private Set<QuoteHeader> quoteHeaders_1 = new HashSet<QuoteHeader>(0);
	private Set<InvoiceHeader> invoiceHeaders_1 = new HashSet<InvoiceHeader>(0);

	public OrgBankDetail() {
	}

	public OrgBankDetail(long id) {
		this.id = id;
	}

	public OrgBankDetail(long id, OrgLocation orgLocation, String accountNumber, String accountType, String bankAddress,
			String bankBranch, String bankName, String ifscCode, String micrCode, String swiftCode, String description,
			Set<QuoteHeader> quoteHeaders, Set<InvoiceHeader> invoiceHeaders, Set<QuoteHeader> quoteHeaders_1,
			Set<InvoiceHeader> invoiceHeaders_1) {
		this.id = id;
		this.orgLocation = orgLocation;
		this.accountNumber = accountNumber;
		this.accountType = accountType;
		this.bankAddress = bankAddress;
		this.bankBranch = bankBranch;
		this.bankName = bankName;
		this.ifscCode = ifscCode;
		this.micrCode = micrCode;
		this.swiftCode = swiftCode;
		this.description = description;
		this.quoteHeaders = quoteHeaders;
		this.invoiceHeaders = invoiceHeaders;
		this.quoteHeaders_1 = quoteHeaders_1;
		this.invoiceHeaders_1 = invoiceHeaders_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORG_LOCATION_FK")
	public OrgLocation getOrgLocation() {
		return this.orgLocation;
	}

	public void setOrgLocation(OrgLocation orgLocation) {
		this.orgLocation = orgLocation;
	}

	@Column(name = "ACCOUNT_NUMBER")
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "ACCOUNT_TYPE")
	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "BANK_ADDRESS", length = 16777215)
	public String getBankAddress() {
		return this.bankAddress;
	}

	public void setBankAddress(String bankAddress) {
		this.bankAddress = bankAddress;
	}

	@Column(name = "BANK_BRANCH")
	public String getBankBranch() {
		return this.bankBranch;
	}

	public void setBankBranch(String bankBranch) {
		this.bankBranch = bankBranch;
	}

	@Column(name = "BANK_NAME")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "IFSC_CODE")
	public String getIfscCode() {
		return this.ifscCode;
	}

	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}

	@Column(name = "MICR_CODE")
	public String getMicrCode() {
		return this.micrCode;
	}

	public void setMicrCode(String micrCode) {
		this.micrCode = micrCode;
	}

	@Column(name = "SWIFT_CODE")
	public String getSwiftCode() {
		return this.swiftCode;
	}

	public void setSwiftCode(String swiftCode) {
		this.swiftCode = swiftCode;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgBankDetail")
	public Set<QuoteHeader> getQuoteHeaders() {
		return this.quoteHeaders;
	}

	public void setQuoteHeaders(Set<QuoteHeader> quoteHeaders) {
		this.quoteHeaders = quoteHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgBankDetail")
	public Set<InvoiceHeader> getInvoiceHeaders() {
		return this.invoiceHeaders;
	}

	public void setInvoiceHeaders(Set<InvoiceHeader> invoiceHeaders) {
		this.invoiceHeaders = invoiceHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgBankDetail")
	public Set<QuoteHeader> getQuoteHeaders_1() {
		return this.quoteHeaders_1;
	}

	public void setQuoteHeaders_1(Set<QuoteHeader> quoteHeaders_1) {
		this.quoteHeaders_1 = quoteHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgBankDetail")
	public Set<InvoiceHeader> getInvoiceHeaders_1() {
		return this.invoiceHeaders_1;
	}

	public void setInvoiceHeaders_1(Set<InvoiceHeader> invoiceHeaders_1) {
		this.invoiceHeaders_1 = invoiceHeaders_1;
	}

}
