package com.connectivity.vikray.entity;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrgLocation generated by hbm2java
 */
@Entity
@Table(name = "ORG_LOCATION", catalog = "namcrm")
public class OrgLocation implements java.io.Serializable {

	private long id;
	private Organisation organisation;
	private String cstNum;
	private String gstNum;
	private String locationId;
	private String panNum;
	private String registrationNum;
	private String serviceTaxNum;
	private String vatTinNum;
	private long accountId;
	private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);
	private Set<QuoteHeader> quoteHeaders = new HashSet<QuoteHeader>(0);
	private Set<DeliveryChallan> deliveryChallans = new HashSet<DeliveryChallan>(0);
	private Set<QuoteHeader> quoteHeaders_1 = new HashSet<QuoteHeader>(0);
	private Set<PurchaseEntry> purchaseEntries = new HashSet<PurchaseEntry>(0);
	private Set<OrganisationAddress> organisationAddresses = new HashSet<OrganisationAddress>(0);
	private Set<UserDetails> userDetailses_1 = new HashSet<UserDetails>(0);
	private Set<OrganisationAddress> organisationAddresses_1 = new HashSet<OrganisationAddress>(0);
	private Set<InvoiceHeader> invoiceHeaders = new HashSet<InvoiceHeader>(0);
	private Set<PurchaseEntry> purchaseEntries_1 = new HashSet<PurchaseEntry>(0);
	private Set<InvoiceHeader> invoiceHeaders_1 = new HashSet<InvoiceHeader>(0);
	private Set<OrgBankDetail> orgBankDetails = new HashSet<OrgBankDetail>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders = new HashSet<PurchaseOrderHeader>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders_1 = new HashSet<PurchaseOrderHeader>(0);
	private Set<OrgBankDetail> orgBankDetails_1 = new HashSet<OrgBankDetail>(0);
	private Set<DeliveryChallan> deliveryChallans_1 = new HashSet<DeliveryChallan>(0);

	public OrgLocation() {
	}

	public OrgLocation(long id, long accountId) {
		this.id = id;
		this.accountId = accountId;
	}

	public OrgLocation(long id, Organisation organisation, String cstNum, String gstNum, String locationId,
			String panNum, String registrationNum, String serviceTaxNum, String vatTinNum, long accountId,
			Set<UserDetails> userDetailses, Set<QuoteHeader> quoteHeaders, Set<DeliveryChallan> deliveryChallans,
			Set<QuoteHeader> quoteHeaders_1, Set<PurchaseEntry> purchaseEntries,
			Set<OrganisationAddress> organisationAddresses, Set<UserDetails> userDetailses_1,
			Set<OrganisationAddress> organisationAddresses_1, Set<InvoiceHeader> invoiceHeaders,
			Set<PurchaseEntry> purchaseEntries_1, Set<InvoiceHeader> invoiceHeaders_1,
			Set<OrgBankDetail> orgBankDetails, Set<PurchaseOrderHeader> purchaseOrderHeaders,
			Set<PurchaseOrderHeader> purchaseOrderHeaders_1, Set<OrgBankDetail> orgBankDetails_1,
			Set<DeliveryChallan> deliveryChallans_1) {
		this.id = id;
		this.organisation = organisation;
		this.cstNum = cstNum;
		this.gstNum = gstNum;
		this.locationId = locationId;
		this.panNum = panNum;
		this.registrationNum = registrationNum;
		this.serviceTaxNum = serviceTaxNum;
		this.vatTinNum = vatTinNum;
		this.accountId = accountId;
		this.userDetailses = userDetailses;
		this.quoteHeaders = quoteHeaders;
		this.deliveryChallans = deliveryChallans;
		this.quoteHeaders_1 = quoteHeaders_1;
		this.purchaseEntries = purchaseEntries;
		this.organisationAddresses = organisationAddresses;
		this.userDetailses_1 = userDetailses_1;
		this.organisationAddresses_1 = organisationAddresses_1;
		this.invoiceHeaders = invoiceHeaders;
		this.purchaseEntries_1 = purchaseEntries_1;
		this.invoiceHeaders_1 = invoiceHeaders_1;
		this.orgBankDetails = orgBankDetails;
		this.purchaseOrderHeaders = purchaseOrderHeaders;
		this.purchaseOrderHeaders_1 = purchaseOrderHeaders_1;
		this.orgBankDetails_1 = orgBankDetails_1;
		this.deliveryChallans_1 = deliveryChallans_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORGANISATION_FK")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@Column(name = "CST__NUM")
	public String getCstNum() {
		return this.cstNum;
	}

	public void setCstNum(String cstNum) {
		this.cstNum = cstNum;
	}

	@Column(name = "GST_NUM")
	public String getGstNum() {
		return this.gstNum;
	}

	public void setGstNum(String gstNum) {
		this.gstNum = gstNum;
	}

	@Column(name = "LOCATION_ID")
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	@Column(name = "PAN_NUM")
	public String getPanNum() {
		return this.panNum;
	}

	public void setPanNum(String panNum) {
		this.panNum = panNum;
	}

	@Column(name = "REGISTRATION_NUM")
	public String getRegistrationNum() {
		return this.registrationNum;
	}

	public void setRegistrationNum(String registrationNum) {
		this.registrationNum = registrationNum;
	}

	@Column(name = "SERVICE_TAX_NUM")
	public String getServiceTaxNum() {
		return this.serviceTaxNum;
	}

	public void setServiceTaxNum(String serviceTaxNum) {
		this.serviceTaxNum = serviceTaxNum;
	}

	@Column(name = "VAT_TIN_NUM")
	public String getVatTinNum() {
		return this.vatTinNum;
	}

	public void setVatTinNum(String vatTinNum) {
		this.vatTinNum = vatTinNum;
	}

	@Column(name = "ACCOUNT_ID", nullable = false)
	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<UserDetails> getUserDetailses() {
		return this.userDetailses;
	}

	public void setUserDetailses(Set<UserDetails> userDetailses) {
		this.userDetailses = userDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<QuoteHeader> getQuoteHeaders() {
		return this.quoteHeaders;
	}

	public void setQuoteHeaders(Set<QuoteHeader> quoteHeaders) {
		this.quoteHeaders = quoteHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<DeliveryChallan> getDeliveryChallans() {
		return this.deliveryChallans;
	}

	public void setDeliveryChallans(Set<DeliveryChallan> deliveryChallans) {
		this.deliveryChallans = deliveryChallans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<QuoteHeader> getQuoteHeaders_1() {
		return this.quoteHeaders_1;
	}

	public void setQuoteHeaders_1(Set<QuoteHeader> quoteHeaders_1) {
		this.quoteHeaders_1 = quoteHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<PurchaseEntry> getPurchaseEntries() {
		return this.purchaseEntries;
	}

	public void setPurchaseEntries(Set<PurchaseEntry> purchaseEntries) {
		this.purchaseEntries = purchaseEntries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<OrganisationAddress> getOrganisationAddresses() {
		return this.organisationAddresses;
	}

	public void setOrganisationAddresses(Set<OrganisationAddress> organisationAddresses) {
		this.organisationAddresses = organisationAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<UserDetails> getUserDetailses_1() {
		return this.userDetailses_1;
	}

	public void setUserDetailses_1(Set<UserDetails> userDetailses_1) {
		this.userDetailses_1 = userDetailses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<OrganisationAddress> getOrganisationAddresses_1() {
		return this.organisationAddresses_1;
	}

	public void setOrganisationAddresses_1(Set<OrganisationAddress> organisationAddresses_1) {
		this.organisationAddresses_1 = organisationAddresses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<InvoiceHeader> getInvoiceHeaders() {
		return this.invoiceHeaders;
	}

	public void setInvoiceHeaders(Set<InvoiceHeader> invoiceHeaders) {
		this.invoiceHeaders = invoiceHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<PurchaseEntry> getPurchaseEntries_1() {
		return this.purchaseEntries_1;
	}

	public void setPurchaseEntries_1(Set<PurchaseEntry> purchaseEntries_1) {
		this.purchaseEntries_1 = purchaseEntries_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<InvoiceHeader> getInvoiceHeaders_1() {
		return this.invoiceHeaders_1;
	}

	public void setInvoiceHeaders_1(Set<InvoiceHeader> invoiceHeaders_1) {
		this.invoiceHeaders_1 = invoiceHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<OrgBankDetail> getOrgBankDetails() {
		return this.orgBankDetails;
	}

	public void setOrgBankDetails(Set<OrgBankDetail> orgBankDetails) {
		this.orgBankDetails = orgBankDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders() {
		return this.purchaseOrderHeaders;
	}

	public void setPurchaseOrderHeaders(Set<PurchaseOrderHeader> purchaseOrderHeaders) {
		this.purchaseOrderHeaders = purchaseOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders_1() {
		return this.purchaseOrderHeaders_1;
	}

	public void setPurchaseOrderHeaders_1(Set<PurchaseOrderHeader> purchaseOrderHeaders_1) {
		this.purchaseOrderHeaders_1 = purchaseOrderHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<OrgBankDetail> getOrgBankDetails_1() {
		return this.orgBankDetails_1;
	}

	public void setOrgBankDetails_1(Set<OrgBankDetail> orgBankDetails_1) {
		this.orgBankDetails_1 = orgBankDetails_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<DeliveryChallan> getDeliveryChallans_1() {
		return this.deliveryChallans_1;
	}

	public void setDeliveryChallans_1(Set<DeliveryChallan> deliveryChallans_1) {
		this.deliveryChallans_1 = deliveryChallans_1;
	}

}
