package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrgLocation generated by hbm2java
 */
@Entity
@Table(name = "ORG_LOCATION", catalog = "namcrm")
public class OrgLocation implements java.io.Serializable {

	private long id;
	private Organisation organisation;
	private String cstNum;
	private String gstNum;
	private String locationId;
	private String panNum;
	private String registrationNum;
	private String serviceTaxNum;
	private String vatTinNum;
	private long accountId;
	private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);
	private Set<OrganisationAddress> organisationAddresses = new HashSet<OrganisationAddress>(0);
	private Set<QuoteHeader> quoteHeaders = new HashSet<QuoteHeader>(0);
	private Set<PurchaseEntry> purchaseEntries = new HashSet<PurchaseEntry>(0);
	private Set<OrganisationEmail> organisationEmails = new HashSet<OrganisationEmail>(0);
	private Set<InvoiceHeader> invoiceHeaders = new HashSet<InvoiceHeader>(0);
	private Set<OrgBankDetail> orgBankDetails = new HashSet<OrgBankDetail>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders = new HashSet<PurchaseOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallans = new HashSet<DeliveryChallan>(0);

	public OrgLocation() {
	}

	public OrgLocation(long id, long accountId) {
		this.id = id;
		this.accountId = accountId;
	}

	public OrgLocation(long id, Organisation organisation, String cstNum, String gstNum, String locationId,
			String panNum, String registrationNum, String serviceTaxNum, String vatTinNum, long accountId,
			Set<UserDetails> userDetailses, Set<OrganisationAddress> organisationAddresses,
			Set<QuoteHeader> quoteHeaders, Set<PurchaseEntry> purchaseEntries,
			Set<OrganisationEmail> organisationEmails, Set<InvoiceHeader> invoiceHeaders,
			Set<OrgBankDetail> orgBankDetails, Set<PurchaseOrderHeader> purchaseOrderHeaders,
			Set<DeliveryChallan> deliveryChallans) {
		this.id = id;
		this.organisation = organisation;
		this.cstNum = cstNum;
		this.gstNum = gstNum;
		this.locationId = locationId;
		this.panNum = panNum;
		this.registrationNum = registrationNum;
		this.serviceTaxNum = serviceTaxNum;
		this.vatTinNum = vatTinNum;
		this.accountId = accountId;
		this.userDetailses = userDetailses;
		this.organisationAddresses = organisationAddresses;
		this.quoteHeaders = quoteHeaders;
		this.purchaseEntries = purchaseEntries;
		this.organisationEmails = organisationEmails;
		this.invoiceHeaders = invoiceHeaders;
		this.orgBankDetails = orgBankDetails;
		this.purchaseOrderHeaders = purchaseOrderHeaders;
		this.deliveryChallans = deliveryChallans;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORGANISATION_FK")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@Column(name = "CST__NUM")
	public String getCstNum() {
		return this.cstNum;
	}

	public void setCstNum(String cstNum) {
		this.cstNum = cstNum;
	}

	@Column(name = "GST_NUM")
	public String getGstNum() {
		return this.gstNum;
	}

	public void setGstNum(String gstNum) {
		this.gstNum = gstNum;
	}

	@Column(name = "LOCATION_ID")
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	@Column(name = "PAN_NUM")
	public String getPanNum() {
		return this.panNum;
	}

	public void setPanNum(String panNum) {
		this.panNum = panNum;
	}

	@Column(name = "REGISTRATION_NUM")
	public String getRegistrationNum() {
		return this.registrationNum;
	}

	public void setRegistrationNum(String registrationNum) {
		this.registrationNum = registrationNum;
	}

	@Column(name = "SERVICE_TAX_NUM")
	public String getServiceTaxNum() {
		return this.serviceTaxNum;
	}

	public void setServiceTaxNum(String serviceTaxNum) {
		this.serviceTaxNum = serviceTaxNum;
	}

	@Column(name = "VAT_TIN_NUM")
	public String getVatTinNum() {
		return this.vatTinNum;
	}

	public void setVatTinNum(String vatTinNum) {
		this.vatTinNum = vatTinNum;
	}

	@Column(name = "ACCOUNT_ID", nullable = false)
	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<UserDetails> getUserDetailses() {
		return this.userDetailses;
	}

	public void setUserDetailses(Set<UserDetails> userDetailses) {
		this.userDetailses = userDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<OrganisationAddress> getOrganisationAddresses() {
		return this.organisationAddresses;
	}

	public void setOrganisationAddresses(Set<OrganisationAddress> organisationAddresses) {
		this.organisationAddresses = organisationAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<QuoteHeader> getQuoteHeaders() {
		return this.quoteHeaders;
	}

	public void setQuoteHeaders(Set<QuoteHeader> quoteHeaders) {
		this.quoteHeaders = quoteHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<PurchaseEntry> getPurchaseEntries() {
		return this.purchaseEntries;
	}

	public void setPurchaseEntries(Set<PurchaseEntry> purchaseEntries) {
		this.purchaseEntries = purchaseEntries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<OrganisationEmail> getOrganisationEmails() {
		return this.organisationEmails;
	}

	public void setOrganisationEmails(Set<OrganisationEmail> organisationEmails) {
		this.organisationEmails = organisationEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<InvoiceHeader> getInvoiceHeaders() {
		return this.invoiceHeaders;
	}

	public void setInvoiceHeaders(Set<InvoiceHeader> invoiceHeaders) {
		this.invoiceHeaders = invoiceHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<OrgBankDetail> getOrgBankDetails() {
		return this.orgBankDetails;
	}

	public void setOrgBankDetails(Set<OrgBankDetail> orgBankDetails) {
		this.orgBankDetails = orgBankDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders() {
		return this.purchaseOrderHeaders;
	}

	public void setPurchaseOrderHeaders(Set<PurchaseOrderHeader> purchaseOrderHeaders) {
		this.purchaseOrderHeaders = purchaseOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgLocation")
	public Set<DeliveryChallan> getDeliveryChallans() {
		return this.deliveryChallans;
	}

	public void setDeliveryChallans(Set<DeliveryChallan> deliveryChallans) {
		this.deliveryChallans = deliveryChallans;
	}

}
