package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrgRegion generated by hbm2java
 */
@Entity
@Table(name = "ORG_REGION", catalog = "namcrm")
public class OrgRegion implements java.io.Serializable {

	private long id;
	private String region;

	public OrgRegion() {
	}

	public OrgRegion(long id) {
		this.id = id;
	}

	public OrgRegion(long id, String region) {
		this.id = id;
		this.region = region;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "REGION")
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

}
