package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payable generated by hbm2java
 */
@Entity
@Table(name = "PAYABLE", catalog = "namcrm")
public class Payable implements java.io.Serializable {

	private long id;
	private AccountDetail accountDetail;
	private FinancialReport financialReport;
	private GrnHeader grnHeader;
	private boolean isPaid;
	private double pendingPayableAmt;
	private String remarks;
	private double totalPaid;
	private String vendInvNumber;
	private String vendorPoNumber;
	private double vendorInvAmount;
	private Date vendorInvDate;
	private String vendorName;
	private double paymentTermDays;
	private double totalTdsAmount;
	private String currency;
	private double totalBankCharges;
	private double sgstAmount;
	private double cgstAmount;
	private double igstAmount;
	private double totalFreight;
	private Set<PaybaleHistory> paybaleHistories = new HashSet<PaybaleHistory>(0);

	public Payable() {
	}

	public Payable(long id, boolean isPaid, double pendingPayableAmt, double totalPaid, double vendorInvAmount,
			double paymentTermDays, double totalTdsAmount, double totalBankCharges, double sgstAmount,
			double cgstAmount, double igstAmount, double totalFreight) {
		this.id = id;
		this.isPaid = isPaid;
		this.pendingPayableAmt = pendingPayableAmt;
		this.totalPaid = totalPaid;
		this.vendorInvAmount = vendorInvAmount;
		this.paymentTermDays = paymentTermDays;
		this.totalTdsAmount = totalTdsAmount;
		this.totalBankCharges = totalBankCharges;
		this.sgstAmount = sgstAmount;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.totalFreight = totalFreight;
	}

	public Payable(long id, AccountDetail accountDetail, FinancialReport financialReport, GrnHeader grnHeader,
			boolean isPaid, double pendingPayableAmt, String remarks, double totalPaid, String vendInvNumber,
			String vendorPoNumber, double vendorInvAmount, Date vendorInvDate, String vendorName,
			double paymentTermDays, double totalTdsAmount, String currency, double totalBankCharges, double sgstAmount,
			double cgstAmount, double igstAmount, double totalFreight, Set<PaybaleHistory> paybaleHistories) {
		this.id = id;
		this.accountDetail = accountDetail;
		this.financialReport = financialReport;
		this.grnHeader = grnHeader;
		this.isPaid = isPaid;
		this.pendingPayableAmt = pendingPayableAmt;
		this.remarks = remarks;
		this.totalPaid = totalPaid;
		this.vendInvNumber = vendInvNumber;
		this.vendorPoNumber = vendorPoNumber;
		this.vendorInvAmount = vendorInvAmount;
		this.vendorInvDate = vendorInvDate;
		this.vendorName = vendorName;
		this.paymentTermDays = paymentTermDays;
		this.totalTdsAmount = totalTdsAmount;
		this.currency = currency;
		this.totalBankCharges = totalBankCharges;
		this.sgstAmount = sgstAmount;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.totalFreight = totalFreight;
		this.paybaleHistories = paybaleHistories;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VENDOR_FK")
	public AccountDetail getAccountDetail() {
		return this.accountDetail;
	}

	public void setAccountDetail(AccountDetail accountDetail) {
		this.accountDetail = accountDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FINAANCIAL_FK")
	public FinancialReport getFinancialReport() {
		return this.financialReport;
	}

	public void setFinancialReport(FinancialReport financialReport) {
		this.financialReport = financialReport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRN_FK")
	public GrnHeader getGrnHeader() {
		return this.grnHeader;
	}

	public void setGrnHeader(GrnHeader grnHeader) {
		this.grnHeader = grnHeader;
	}

	@Column(name = "IS_PAID", nullable = false)
	public boolean isIsPaid() {
		return this.isPaid;
	}

	public void setIsPaid(boolean isPaid) {
		this.isPaid = isPaid;
	}

	@Column(name = "PENDING_PAYABLE_AMT", nullable = false, precision = 22, scale = 0)
	public double getPendingPayableAmt() {
		return this.pendingPayableAmt;
	}

	public void setPendingPayableAmt(double pendingPayableAmt) {
		this.pendingPayableAmt = pendingPayableAmt;
	}

	@Column(name = "REMARKS", length = 16777215)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "TOTAL_PAID", nullable = false, precision = 22, scale = 0)
	public double getTotalPaid() {
		return this.totalPaid;
	}

	public void setTotalPaid(double totalPaid) {
		this.totalPaid = totalPaid;
	}

	@Column(name = "VEND_INV_NUMBER")
	public String getVendInvNumber() {
		return this.vendInvNumber;
	}

	public void setVendInvNumber(String vendInvNumber) {
		this.vendInvNumber = vendInvNumber;
	}

	@Column(name = "VENDOR_PO_NUMBER")
	public String getVendorPoNumber() {
		return this.vendorPoNumber;
	}

	public void setVendorPoNumber(String vendorPoNumber) {
		this.vendorPoNumber = vendorPoNumber;
	}

	@Column(name = "VENDOR_INV_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getVendorInvAmount() {
		return this.vendorInvAmount;
	}

	public void setVendorInvAmount(double vendorInvAmount) {
		this.vendorInvAmount = vendorInvAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VENDOR_INV_DATE", length = 19)
	public Date getVendorInvDate() {
		return this.vendorInvDate;
	}

	public void setVendorInvDate(Date vendorInvDate) {
		this.vendorInvDate = vendorInvDate;
	}

	@Column(name = "VENDOR_NAME")
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "PAYMENT_TERM_DAYS", nullable = false, precision = 22, scale = 0)
	public double getPaymentTermDays() {
		return this.paymentTermDays;
	}

	public void setPaymentTermDays(double paymentTermDays) {
		this.paymentTermDays = paymentTermDays;
	}

	@Column(name = "TOTAL_TDS_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getTotalTdsAmount() {
		return this.totalTdsAmount;
	}

	public void setTotalTdsAmount(double totalTdsAmount) {
		this.totalTdsAmount = totalTdsAmount;
	}

	@Column(name = "CURRENCY")
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "TOTAL_BANK_CHARGES", nullable = false, precision = 22, scale = 0)
	public double getTotalBankCharges() {
		return this.totalBankCharges;
	}

	public void setTotalBankCharges(double totalBankCharges) {
		this.totalBankCharges = totalBankCharges;
	}

	@Column(name = "SGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getSgstAmount() {
		return this.sgstAmount;
	}

	public void setSgstAmount(double sgstAmount) {
		this.sgstAmount = sgstAmount;
	}

	@Column(name = "CGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getCgstAmount() {
		return this.cgstAmount;
	}

	public void setCgstAmount(double cgstAmount) {
		this.cgstAmount = cgstAmount;
	}

	@Column(name = "IGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getIgstAmount() {
		return this.igstAmount;
	}

	public void setIgstAmount(double igstAmount) {
		this.igstAmount = igstAmount;
	}

	@Column(name = "TOTAL_FREIGHT", nullable = false, precision = 22, scale = 0)
	public double getTotalFreight() {
		return this.totalFreight;
	}

	public void setTotalFreight(double totalFreight) {
		this.totalFreight = totalFreight;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payable")
	public Set<PaybaleHistory> getPaybaleHistories() {
		return this.paybaleHistories;
	}

	public void setPaybaleHistories(Set<PaybaleHistory> paybaleHistories) {
		this.paybaleHistories = paybaleHistories;
	}

}
