package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaybaleHistory generated by hbm2java
 */
@Entity
@Table(name = "PAYBALE_HISTORY", catalog = "namcrm")
public class PaybaleHistory implements java.io.Serializable {

	private long id;
	private Payable payable;
	private double paidAmount;
	private Date paidOn;
	private String remarks;
	private double tdsAmount;
	private String bankTrasactionNumber;
	private String frieghtDocumentDumber;
	private double frieghtInferedCharge;
	private double transactionCharge;

	public PaybaleHistory() {
	}

	public PaybaleHistory(long id, double paidAmount, double tdsAmount, double frieghtInferedCharge,
			double transactionCharge) {
		this.id = id;
		this.paidAmount = paidAmount;
		this.tdsAmount = tdsAmount;
		this.frieghtInferedCharge = frieghtInferedCharge;
		this.transactionCharge = transactionCharge;
	}

	public PaybaleHistory(long id, Payable payable, double paidAmount, Date paidOn, String remarks, double tdsAmount,
			String bankTrasactionNumber, String frieghtDocumentDumber, double frieghtInferedCharge,
			double transactionCharge) {
		this.id = id;
		this.payable = payable;
		this.paidAmount = paidAmount;
		this.paidOn = paidOn;
		this.remarks = remarks;
		this.tdsAmount = tdsAmount;
		this.bankTrasactionNumber = bankTrasactionNumber;
		this.frieghtDocumentDumber = frieghtDocumentDumber;
		this.frieghtInferedCharge = frieghtInferedCharge;
		this.transactionCharge = transactionCharge;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAYABLE_FK")
	public Payable getPayable() {
		return this.payable;
	}

	public void setPayable(Payable payable) {
		this.payable = payable;
	}

	@Column(name = "PAID_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(double paidAmount) {
		this.paidAmount = paidAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PAID_ON", length = 19)
	public Date getPaidOn() {
		return this.paidOn;
	}

	public void setPaidOn(Date paidOn) {
		this.paidOn = paidOn;
	}

	@Column(name = "REMARKS", length = 16777215)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "TDS_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getTdsAmount() {
		return this.tdsAmount;
	}

	public void setTdsAmount(double tdsAmount) {
		this.tdsAmount = tdsAmount;
	}

	@Column(name = "BANK_TRASACTION_NUMBER")
	public String getBankTrasactionNumber() {
		return this.bankTrasactionNumber;
	}

	public void setBankTrasactionNumber(String bankTrasactionNumber) {
		this.bankTrasactionNumber = bankTrasactionNumber;
	}

	@Column(name = "FRIEGHT_DOCUMENT_DUMBER")
	public String getFrieghtDocumentDumber() {
		return this.frieghtDocumentDumber;
	}

	public void setFrieghtDocumentDumber(String frieghtDocumentDumber) {
		this.frieghtDocumentDumber = frieghtDocumentDumber;
	}

	@Column(name = "FRIEGHT_INFERED_CHARGE", nullable = false, precision = 22, scale = 0)
	public double getFrieghtInferedCharge() {
		return this.frieghtInferedCharge;
	}

	public void setFrieghtInferedCharge(double frieghtInferedCharge) {
		this.frieghtInferedCharge = frieghtInferedCharge;
	}

	@Column(name = "TRANSACTION_CHARGE", nullable = false, precision = 22, scale = 0)
	public double getTransactionCharge() {
		return this.transactionCharge;
	}

	public void setTransactionCharge(double transactionCharge) {
		this.transactionCharge = transactionCharge;
	}

}
