package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonEmail generated by hbm2java
 */
@Entity
@Table(name = "PERSON_EMAIL", catalog = "namcrm")
public class PersonEmail implements java.io.Serializable {

	private long id;
	private PersonDetail personDetail;
	private String email;
	private boolean isDefault;
	private Integer peremailsIntegerIdx;

	public PersonEmail() {
	}

	public PersonEmail(long id, boolean isDefault) {
		this.id = id;
		this.isDefault = isDefault;
	}

	public PersonEmail(long id, PersonDetail personDetail, String email, boolean isDefault,
			Integer peremailsIntegerIdx) {
		this.id = id;
		this.personDetail = personDetail;
		this.email = email;
		this.isDefault = isDefault;
		this.peremailsIntegerIdx = peremailsIntegerIdx;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_FK")
	public PersonDetail getPersonDetail() {
		return this.personDetail;
	}

	public void setPersonDetail(PersonDetail personDetail) {
		this.personDetail = personDetail;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "IS_DEFAULT", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "PEREMAILS_INTEGER_IDX")
	public Integer getPeremailsIntegerIdx() {
		return this.peremailsIntegerIdx;
	}

	public void setPeremailsIntegerIdx(Integer peremailsIntegerIdx) {
		this.peremailsIntegerIdx = peremailsIntegerIdx;
	}

}
