package com.connectivity.vikray.entity;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonDetail generated by hbm2java
 */
@Entity
@Table(name = "PERSON_DETAIL", catalog = "namcrm")
public class PersonDetail implements java.io.Serializable {

	private long id;
	private AccountDetail accountDetail;
	private Domain domain;
	private RoleType roleType;
	private String firstName;
	private String guid;
	private String lastName;
	private String middleName;
	private String title;
	private Integer perdetailsIntegerIdx;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	private Set<InvoiceHeader> invoiceHeadersForPersonFk = new HashSet<InvoiceHeader>(0);
	private Set<GrnHeader> grnHeaders = new HashSet<GrnHeader>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders = new HashSet<PurchaseOrderHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForShippingContactFk = new HashSet<SalesOrderHeader>(0);
	private Set<QuoteHeader> quoteHeaders = new HashSet<QuoteHeader>(0);
	private Set<PurchaseEntry> purchaseEntries = new HashSet<PurchaseEntry>(0);
	private Set<BusinessDeal> businessDeals = new HashSet<BusinessDeal>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForFinanceContactFk = new HashSet<SalesOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForShippingContactFk = new HashSet<DeliveryChallan>(0);
	private Set<PurchaseEntry> purchaseEntries_1 = new HashSet<PurchaseEntry>(0);
	private Set<GrnHeader> grnHeaders_1 = new HashSet<GrnHeader>(0);
	private Set<InvoiceHeader> invoiceHeadersForFinanceContactFk = new HashSet<InvoiceHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForShippingContactFk_1 = new HashSet<SalesOrderHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForFinanceContactFk_1 = new HashSet<SalesOrderHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForPersonFk = new HashSet<SalesOrderHeader>(0);
	private Set<InvoiceHeader> invoiceHeadersForFinanceContactFk_1 = new HashSet<InvoiceHeader>(0);
	private Set<SalesOrderHeader> salesOrderHeadersForPersonFk_1 = new HashSet<SalesOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForShippingContactFk_1 = new HashSet<DeliveryChallan>(0);
	private Set<InvoiceHeader> invoiceHeadersForPersonFk_1 = new HashSet<InvoiceHeader>(0);
	private Set<BusinessDeal> businessDeals_1 = new HashSet<BusinessDeal>(0);
	private Set<DeliveryChallan> deliveryChallansForPersonFk = new HashSet<DeliveryChallan>(0);
	private Set<OrderItem> orderItems_1 = new HashSet<OrderItem>(0);
	private Set<QuoteHeader> quoteHeaders_1 = new HashSet<QuoteHeader>(0);
	private Set<DeliveryChallan> deliveryChallansForPersonFk_1 = new HashSet<DeliveryChallan>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders_1 = new HashSet<PurchaseOrderHeader>(0);

	public PersonDetail() {
	}

	public PersonDetail(long id) {
		this.id = id;
	}

	public PersonDetail(long id, AccountDetail accountDetail, Domain domain, RoleType roleType, String firstName,
			String guid, String lastName, String middleName, String title, Integer perdetailsIntegerIdx,
			Set<OrderItem> orderItems, Set<InvoiceHeader> invoiceHeadersForPersonFk, Set<GrnHeader> grnHeaders,
			Set<PurchaseOrderHeader> purchaseOrderHeaders, Set<SalesOrderHeader> salesOrderHeadersForShippingContactFk,
			Set<QuoteHeader> quoteHeaders, Set<PurchaseEntry> purchaseEntries, Set<BusinessDeal> businessDeals,
			Set<SalesOrderHeader> salesOrderHeadersForFinanceContactFk,
			Set<DeliveryChallan> deliveryChallansForShippingContactFk, Set<PurchaseEntry> purchaseEntries_1,
			Set<GrnHeader> grnHeaders_1, Set<InvoiceHeader> invoiceHeadersForFinanceContactFk,
			Set<SalesOrderHeader> salesOrderHeadersForShippingContactFk_1,
			Set<SalesOrderHeader> salesOrderHeadersForFinanceContactFk_1,
			Set<SalesOrderHeader> salesOrderHeadersForPersonFk, Set<InvoiceHeader> invoiceHeadersForFinanceContactFk_1,
			Set<SalesOrderHeader> salesOrderHeadersForPersonFk_1,
			Set<DeliveryChallan> deliveryChallansForShippingContactFk_1, Set<InvoiceHeader> invoiceHeadersForPersonFk_1,
			Set<BusinessDeal> businessDeals_1, Set<DeliveryChallan> deliveryChallansForPersonFk,
			Set<OrderItem> orderItems_1, Set<QuoteHeader> quoteHeaders_1,
			Set<DeliveryChallan> deliveryChallansForPersonFk_1, Set<PurchaseOrderHeader> purchaseOrderHeaders_1) {
		this.id = id;
		this.accountDetail = accountDetail;
		this.domain = domain;
		this.roleType = roleType;
		this.firstName = firstName;
		this.guid = guid;
		this.lastName = lastName;
		this.middleName = middleName;
		this.title = title;
		this.perdetailsIntegerIdx = perdetailsIntegerIdx;
		this.orderItems = orderItems;
		this.invoiceHeadersForPersonFk = invoiceHeadersForPersonFk;
		this.grnHeaders = grnHeaders;
		this.purchaseOrderHeaders = purchaseOrderHeaders;
		this.salesOrderHeadersForShippingContactFk = salesOrderHeadersForShippingContactFk;
		this.quoteHeaders = quoteHeaders;
		this.purchaseEntries = purchaseEntries;
		this.businessDeals = businessDeals;
		this.salesOrderHeadersForFinanceContactFk = salesOrderHeadersForFinanceContactFk;
		this.deliveryChallansForShippingContactFk = deliveryChallansForShippingContactFk;
		this.purchaseEntries_1 = purchaseEntries_1;
		this.grnHeaders_1 = grnHeaders_1;
		this.invoiceHeadersForFinanceContactFk = invoiceHeadersForFinanceContactFk;
		this.salesOrderHeadersForShippingContactFk_1 = salesOrderHeadersForShippingContactFk_1;
		this.salesOrderHeadersForFinanceContactFk_1 = salesOrderHeadersForFinanceContactFk_1;
		this.salesOrderHeadersForPersonFk = salesOrderHeadersForPersonFk;
		this.invoiceHeadersForFinanceContactFk_1 = invoiceHeadersForFinanceContactFk_1;
		this.salesOrderHeadersForPersonFk_1 = salesOrderHeadersForPersonFk_1;
		this.deliveryChallansForShippingContactFk_1 = deliveryChallansForShippingContactFk_1;
		this.invoiceHeadersForPersonFk_1 = invoiceHeadersForPersonFk_1;
		this.businessDeals_1 = businessDeals_1;
		this.deliveryChallansForPersonFk = deliveryChallansForPersonFk;
		this.orderItems_1 = orderItems_1;
		this.quoteHeaders_1 = quoteHeaders_1;
		this.deliveryChallansForPersonFk_1 = deliveryChallansForPersonFk_1;
		this.purchaseOrderHeaders_1 = purchaseOrderHeaders_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_FK")
	public AccountDetail getAccountDetail() {
		return this.accountDetail;
	}

	public void setAccountDetail(AccountDetail accountDetail) {
		this.accountDetail = accountDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN_FK")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_TYPE_FK")
	public RoleType getRoleType() {
		return this.roleType;
	}

	public void setRoleType(RoleType roleType) {
		this.roleType = roleType;
	}

	@Column(name = "FIRST_NAME")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "GUID")
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "LAST_NAME")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "MIDDLE_NAME")
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "PERDETAILS_INTEGER_IDX")
	public Integer getPerdetailsIntegerIdx() {
		return this.perdetailsIntegerIdx;
	}

	public void setPerdetailsIntegerIdx(Integer perdetailsIntegerIdx) {
		this.perdetailsIntegerIdx = perdetailsIntegerIdx;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByPersonFk")
	public Set<InvoiceHeader> getInvoiceHeadersForPersonFk() {
		return this.invoiceHeadersForPersonFk;
	}

	public void setInvoiceHeadersForPersonFk(Set<InvoiceHeader> invoiceHeadersForPersonFk) {
		this.invoiceHeadersForPersonFk = invoiceHeadersForPersonFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<GrnHeader> getGrnHeaders() {
		return this.grnHeaders;
	}

	public void setGrnHeaders(Set<GrnHeader> grnHeaders) {
		this.grnHeaders = grnHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders() {
		return this.purchaseOrderHeaders;
	}

	public void setPurchaseOrderHeaders(Set<PurchaseOrderHeader> purchaseOrderHeaders) {
		this.purchaseOrderHeaders = purchaseOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByShippingContactFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForShippingContactFk() {
		return this.salesOrderHeadersForShippingContactFk;
	}

	public void setSalesOrderHeadersForShippingContactFk(Set<SalesOrderHeader> salesOrderHeadersForShippingContactFk) {
		this.salesOrderHeadersForShippingContactFk = salesOrderHeadersForShippingContactFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<QuoteHeader> getQuoteHeaders() {
		return this.quoteHeaders;
	}

	public void setQuoteHeaders(Set<QuoteHeader> quoteHeaders) {
		this.quoteHeaders = quoteHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<PurchaseEntry> getPurchaseEntries() {
		return this.purchaseEntries;
	}

	public void setPurchaseEntries(Set<PurchaseEntry> purchaseEntries) {
		this.purchaseEntries = purchaseEntries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<BusinessDeal> getBusinessDeals() {
		return this.businessDeals;
	}

	public void setBusinessDeals(Set<BusinessDeal> businessDeals) {
		this.businessDeals = businessDeals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByFinanceContactFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForFinanceContactFk() {
		return this.salesOrderHeadersForFinanceContactFk;
	}

	public void setSalesOrderHeadersForFinanceContactFk(Set<SalesOrderHeader> salesOrderHeadersForFinanceContactFk) {
		this.salesOrderHeadersForFinanceContactFk = salesOrderHeadersForFinanceContactFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByShippingContactFk")
	public Set<DeliveryChallan> getDeliveryChallansForShippingContactFk() {
		return this.deliveryChallansForShippingContactFk;
	}

	public void setDeliveryChallansForShippingContactFk(Set<DeliveryChallan> deliveryChallansForShippingContactFk) {
		this.deliveryChallansForShippingContactFk = deliveryChallansForShippingContactFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<PurchaseEntry> getPurchaseEntries_1() {
		return this.purchaseEntries_1;
	}

	public void setPurchaseEntries_1(Set<PurchaseEntry> purchaseEntries_1) {
		this.purchaseEntries_1 = purchaseEntries_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<GrnHeader> getGrnHeaders_1() {
		return this.grnHeaders_1;
	}

	public void setGrnHeaders_1(Set<GrnHeader> grnHeaders_1) {
		this.grnHeaders_1 = grnHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByFinanceContactFk")
	public Set<InvoiceHeader> getInvoiceHeadersForFinanceContactFk() {
		return this.invoiceHeadersForFinanceContactFk;
	}

	public void setInvoiceHeadersForFinanceContactFk(Set<InvoiceHeader> invoiceHeadersForFinanceContactFk) {
		this.invoiceHeadersForFinanceContactFk = invoiceHeadersForFinanceContactFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByShippingContactFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForShippingContactFk_1() {
		return this.salesOrderHeadersForShippingContactFk_1;
	}

	public void setSalesOrderHeadersForShippingContactFk_1(
			Set<SalesOrderHeader> salesOrderHeadersForShippingContactFk_1) {
		this.salesOrderHeadersForShippingContactFk_1 = salesOrderHeadersForShippingContactFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByFinanceContactFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForFinanceContactFk_1() {
		return this.salesOrderHeadersForFinanceContactFk_1;
	}

	public void setSalesOrderHeadersForFinanceContactFk_1(
			Set<SalesOrderHeader> salesOrderHeadersForFinanceContactFk_1) {
		this.salesOrderHeadersForFinanceContactFk_1 = salesOrderHeadersForFinanceContactFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByPersonFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForPersonFk() {
		return this.salesOrderHeadersForPersonFk;
	}

	public void setSalesOrderHeadersForPersonFk(Set<SalesOrderHeader> salesOrderHeadersForPersonFk) {
		this.salesOrderHeadersForPersonFk = salesOrderHeadersForPersonFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByFinanceContactFk")
	public Set<InvoiceHeader> getInvoiceHeadersForFinanceContactFk_1() {
		return this.invoiceHeadersForFinanceContactFk_1;
	}

	public void setInvoiceHeadersForFinanceContactFk_1(Set<InvoiceHeader> invoiceHeadersForFinanceContactFk_1) {
		this.invoiceHeadersForFinanceContactFk_1 = invoiceHeadersForFinanceContactFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByPersonFk")
	public Set<SalesOrderHeader> getSalesOrderHeadersForPersonFk_1() {
		return this.salesOrderHeadersForPersonFk_1;
	}

	public void setSalesOrderHeadersForPersonFk_1(Set<SalesOrderHeader> salesOrderHeadersForPersonFk_1) {
		this.salesOrderHeadersForPersonFk_1 = salesOrderHeadersForPersonFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByShippingContactFk")
	public Set<DeliveryChallan> getDeliveryChallansForShippingContactFk_1() {
		return this.deliveryChallansForShippingContactFk_1;
	}

	public void setDeliveryChallansForShippingContactFk_1(Set<DeliveryChallan> deliveryChallansForShippingContactFk_1) {
		this.deliveryChallansForShippingContactFk_1 = deliveryChallansForShippingContactFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByPersonFk")
	public Set<InvoiceHeader> getInvoiceHeadersForPersonFk_1() {
		return this.invoiceHeadersForPersonFk_1;
	}

	public void setInvoiceHeadersForPersonFk_1(Set<InvoiceHeader> invoiceHeadersForPersonFk_1) {
		this.invoiceHeadersForPersonFk_1 = invoiceHeadersForPersonFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<BusinessDeal> getBusinessDeals_1() {
		return this.businessDeals_1;
	}

	public void setBusinessDeals_1(Set<BusinessDeal> businessDeals_1) {
		this.businessDeals_1 = businessDeals_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByPersonFk")
	public Set<DeliveryChallan> getDeliveryChallansForPersonFk() {
		return this.deliveryChallansForPersonFk;
	}

	public void setDeliveryChallansForPersonFk(Set<DeliveryChallan> deliveryChallansForPersonFk) {
		this.deliveryChallansForPersonFk = deliveryChallansForPersonFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<OrderItem> getOrderItems_1() {
		return this.orderItems_1;
	}

	public void setOrderItems_1(Set<OrderItem> orderItems_1) {
		this.orderItems_1 = orderItems_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<QuoteHeader> getQuoteHeaders_1() {
		return this.quoteHeaders_1;
	}

	public void setQuoteHeaders_1(Set<QuoteHeader> quoteHeaders_1) {
		this.quoteHeaders_1 = quoteHeaders_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetailByPersonFk")
	public Set<DeliveryChallan> getDeliveryChallansForPersonFk_1() {
		return this.deliveryChallansForPersonFk_1;
	}

	public void setDeliveryChallansForPersonFk_1(Set<DeliveryChallan> deliveryChallansForPersonFk_1) {
		this.deliveryChallansForPersonFk_1 = deliveryChallansForPersonFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personDetail")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders_1() {
		return this.purchaseOrderHeaders_1;
	}

	public void setPurchaseOrderHeaders_1(Set<PurchaseOrderHeader> purchaseOrderHeaders_1) {
		this.purchaseOrderHeaders_1 = purchaseOrderHeaders_1;
	}

}
