package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonAddress generated by hbm2java
 */
@Entity
@Table(name = "PERSON_ADDRESS", catalog = "namcrm")
public class PersonAddress implements java.io.Serializable {

	private long id;
	private PersonDetail personDetail;
	private String addressLine1;
	private String addressLine2;
	private String addressType;
	private String city;
	private String country;
	private boolean isDefault;
	private String state;
	private String zipcode;
	private Integer peraddressIntegerIdx;

	public PersonAddress() {
	}

	public PersonAddress(long id, boolean isDefault) {
		this.id = id;
		this.isDefault = isDefault;
	}

	public PersonAddress(long id, PersonDetail personDetail, String addressLine1, String addressLine2,
			String addressType, String city, String country, boolean isDefault, String state, String zipcode,
			Integer peraddressIntegerIdx) {
		this.id = id;
		this.personDetail = personDetail;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressType = addressType;
		this.city = city;
		this.country = country;
		this.isDefault = isDefault;
		this.state = state;
		this.zipcode = zipcode;
		this.peraddressIntegerIdx = peraddressIntegerIdx;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_FK")
	public PersonDetail getPersonDetail() {
		return this.personDetail;
	}

	public void setPersonDetail(PersonDetail personDetail) {
		this.personDetail = personDetail;
	}

	@Column(name = "ADDRESS_LINE1")
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE2")
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "ADDRESS_TYPE")
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "CITY")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "COUNTRY")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "IS_DEFAULT", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "STATE")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIPCODE")
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "PERADDRESS_INTEGER_IDX")
	public Integer getPeraddressIntegerIdx() {
		return this.peraddressIntegerIdx;
	}

	public void setPeraddressIntegerIdx(Integer peraddressIntegerIdx) {
		this.peraddressIntegerIdx = peraddressIntegerIdx;
	}

}
