package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonTelephone generated by hbm2java
 */
@Entity
@Table(name = "PERSON_TELEPHONE", catalog = "namcrm")
public class PersonTelephone implements java.io.Serializable {

	private long id;
	private PersonDetail personDetail;
	private boolean isDefault;
	private String number;
	private String phoneType;
	private Integer pertelephonesIntegerIdx;

	public PersonTelephone() {
	}

	public PersonTelephone(long id, boolean isDefault) {
		this.id = id;
		this.isDefault = isDefault;
	}

	public PersonTelephone(long id, PersonDetail personDetail, boolean isDefault, String number, String phoneType,
			Integer pertelephonesIntegerIdx) {
		this.id = id;
		this.personDetail = personDetail;
		this.isDefault = isDefault;
		this.number = number;
		this.phoneType = phoneType;
		this.pertelephonesIntegerIdx = pertelephonesIntegerIdx;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_FK")
	public PersonDetail getPersonDetail() {
		return this.personDetail;
	}

	public void setPersonDetail(PersonDetail personDetail) {
		this.personDetail = personDetail;
	}

	@Column(name = "IS_DEFAULT", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "NUMBER")
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "PHONE_TYPE")
	public String getPhoneType() {
		return this.phoneType;
	}

	public void setPhoneType(String phoneType) {
		this.phoneType = phoneType;
	}

	@Column(name = "PERTELEPHONES_INTEGER_IDX")
	public Integer getPertelephonesIntegerIdx() {
		return this.pertelephonesIntegerIdx;
	}

	public void setPertelephonesIntegerIdx(Integer pertelephonesIntegerIdx) {
		this.pertelephonesIntegerIdx = pertelephonesIntegerIdx;
	}

}
