package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProcessStageMortality generated by hbm2java
 */
@Entity
@Table(name = "PROCESS_STAGE_MORTALITY", catalog = "namcrm")
public class ProcessStageMortality implements java.io.Serializable {

	private long id;
	private double aveDays;
	private long domainFk;
	private String statusName;

	public ProcessStageMortality() {
	}

	public ProcessStageMortality(long id, double aveDays, long domainFk) {
		this.id = id;
		this.aveDays = aveDays;
		this.domainFk = domainFk;
	}

	public ProcessStageMortality(long id, double aveDays, long domainFk, String statusName) {
		this.id = id;
		this.aveDays = aveDays;
		this.domainFk = domainFk;
		this.statusName = statusName;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "AVE_DAYS", nullable = false, precision = 22, scale = 0)
	public double getAveDays() {
		return this.aveDays;
	}

	public void setAveDays(double aveDays) {
		this.aveDays = aveDays;
	}

	@Column(name = "DOMAIN_FK", nullable = false)
	public long getDomainFk() {
		return this.domainFk;
	}

	public void setDomainFk(long domainFk) {
		this.domainFk = domainFk;
	}

	@Column(name = "STATUS_NAME")
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

}
