package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT", catalog = "namcrm", uniqueConstraints = @UniqueConstraint(columnNames = { "DOMAIN_FK",
		"PRODUCT_NAME" }))
public class Product implements java.io.Serializable {

	private long id;
	private Domain domain;
	private ProductCategory productCategoryByProductCategoryFk;
	private ProductCategory productCategoryByParentcategoryIdOid;
	private UserDetails userDetailsByCreatedByUserFk;
	private UserDetails userDetailsByLastModifiedByUserFk;
	private Date createdDate;
	private String guid;
	private String itemDescription;
	private Date lastModifiedDate;
	private String productName;
	private double taxPercentage;
	private String taxType;
	private double unitPrice;
	private String slNo;
	private double totalPrice;
	private String uom;
	private String hsn;
	private double gst;
	private boolean isDisabled;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	private Set<InventoryItem> inventoryItems = new HashSet<InventoryItem>(0);

	public Product() {
	}

	public Product(long id, double taxPercentage, double unitPrice, double totalPrice, double gst, boolean isDisabled) {
		this.id = id;
		this.taxPercentage = taxPercentage;
		this.unitPrice = unitPrice;
		this.totalPrice = totalPrice;
		this.gst = gst;
		this.isDisabled = isDisabled;
	}

	public Product(long id, Domain domain, ProductCategory productCategoryByProductCategoryFk,
			ProductCategory productCategoryByParentcategoryIdOid, UserDetails userDetailsByCreatedByUserFk,
			UserDetails userDetailsByLastModifiedByUserFk, Date createdDate, String guid, String itemDescription,
			Date lastModifiedDate, String productName, double taxPercentage, String taxType, double unitPrice,
			String slNo, double totalPrice, String uom, String hsn, double gst, boolean isDisabled,
			Set<OrderItem> orderItems, Set<InventoryItem> inventoryItems) {
		this.id = id;
		this.domain = domain;
		this.productCategoryByProductCategoryFk = productCategoryByProductCategoryFk;
		this.productCategoryByParentcategoryIdOid = productCategoryByParentcategoryIdOid;
		this.userDetailsByCreatedByUserFk = userDetailsByCreatedByUserFk;
		this.userDetailsByLastModifiedByUserFk = userDetailsByLastModifiedByUserFk;
		this.createdDate = createdDate;
		this.guid = guid;
		this.itemDescription = itemDescription;
		this.lastModifiedDate = lastModifiedDate;
		this.productName = productName;
		this.taxPercentage = taxPercentage;
		this.taxType = taxType;
		this.unitPrice = unitPrice;
		this.slNo = slNo;
		this.totalPrice = totalPrice;
		this.uom = uom;
		this.hsn = hsn;
		this.gst = gst;
		this.isDisabled = isDisabled;
		this.orderItems = orderItems;
		this.inventoryItems = inventoryItems;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN_FK")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_CATEGORY_FK")
	public ProductCategory getProductCategoryByProductCategoryFk() {
		return this.productCategoryByProductCategoryFk;
	}

	public void setProductCategoryByProductCategoryFk(ProductCategory productCategoryByProductCategoryFk) {
		this.productCategoryByProductCategoryFk = productCategoryByProductCategoryFk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENTCATEGORY_ID_OID")
	public ProductCategory getProductCategoryByParentcategoryIdOid() {
		return this.productCategoryByParentcategoryIdOid;
	}

	public void setProductCategoryByParentcategoryIdOid(ProductCategory productCategoryByParentcategoryIdOid) {
		this.productCategoryByParentcategoryIdOid = productCategoryByParentcategoryIdOid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY_USER_FK")
	public UserDetails getUserDetailsByCreatedByUserFk() {
		return this.userDetailsByCreatedByUserFk;
	}

	public void setUserDetailsByCreatedByUserFk(UserDetails userDetailsByCreatedByUserFk) {
		this.userDetailsByCreatedByUserFk = userDetailsByCreatedByUserFk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LAST_MODIFIED_BY_USER_FK")
	public UserDetails getUserDetailsByLastModifiedByUserFk() {
		return this.userDetailsByLastModifiedByUserFk;
	}

	public void setUserDetailsByLastModifiedByUserFk(UserDetails userDetailsByLastModifiedByUserFk) {
		this.userDetailsByLastModifiedByUserFk = userDetailsByLastModifiedByUserFk;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "GUID")
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "ITEM_DESCRIPTION", length = 16777215)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "PRODUCT_NAME")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "TAX_PERCENTAGE", nullable = false, precision = 22, scale = 0)
	public double getTaxPercentage() {
		return this.taxPercentage;
	}

	public void setTaxPercentage(double taxPercentage) {
		this.taxPercentage = taxPercentage;
	}

	@Column(name = "TAX_TYPE")
	public String getTaxType() {
		return this.taxType;
	}

	public void setTaxType(String taxType) {
		this.taxType = taxType;
	}

	@Column(name = "UNIT_PRICE", nullable = false, precision = 22, scale = 0)
	public double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(double unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "SL_NO")
	public String getSlNo() {
		return this.slNo;
	}

	public void setSlNo(String slNo) {
		this.slNo = slNo;
	}

	@Column(name = "TOTAL_PRICE", nullable = false, precision = 22, scale = 0)
	public double getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(double totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "UOM")
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	@Column(name = "HSN")
	public String getHsn() {
		return this.hsn;
	}

	public void setHsn(String hsn) {
		this.hsn = hsn;
	}

	@Column(name = "GST", nullable = false, precision = 22, scale = 0)
	public double getGst() {
		return this.gst;
	}

	public void setGst(double gst) {
		this.gst = gst;
	}

	@Column(name = "IS_DISABLED", nullable = false)
	public boolean isIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<InventoryItem> getInventoryItems() {
		return this.inventoryItems;
	}

	public void setInventoryItems(Set<InventoryItem> inventoryItems) {
		this.inventoryItems = inventoryItems;
	}

}
