package com.connectivity.vikray.entity;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_CATEGORY", catalog = "namcrm")
public class ProductCategory implements java.io.Serializable {

	private long id;
	private Domain domain;
	private ProductCategory productCategoryByParentCategoryFk;
	private ProductCategory productCategoryByParentProductFk;
	private String description;
	private String productCategoryType;
	private String type;
	private Set<Product> productsForProductCategoryFk = new HashSet<Product>(0);
	private Set<ProductCategory> productCategoriesForParentCategoryFk = new HashSet<ProductCategory>(0);
	private Set<Product> productsForProductCategoryFk_1 = new HashSet<Product>(0);
	private Set<Product> productsForParentcategoryIdOid = new HashSet<Product>(0);
	private Set<ProductCategory> productCategoriesForParentProductFk = new HashSet<ProductCategory>(0);
	private Set<ProductCategory> productCategoriesForParentCategoryFk_1 = new HashSet<ProductCategory>(0);
	private Set<Product> productsForParentcategoryIdOid_1 = new HashSet<Product>(0);
	private Set<ProductCategory> productCategoriesForParentProductFk_1 = new HashSet<ProductCategory>(0);

	public ProductCategory() {
	}

	public ProductCategory(long id) {
		this.id = id;
	}

	public ProductCategory(long id, Domain domain, ProductCategory productCategoryByParentCategoryFk,
			ProductCategory productCategoryByParentProductFk, String description, String productCategoryType,
			String type, Set<Product> productsForProductCategoryFk,
			Set<ProductCategory> productCategoriesForParentCategoryFk, Set<Product> productsForProductCategoryFk_1,
			Set<Product> productsForParentcategoryIdOid, Set<ProductCategory> productCategoriesForParentProductFk,
			Set<ProductCategory> productCategoriesForParentCategoryFk_1, Set<Product> productsForParentcategoryIdOid_1,
			Set<ProductCategory> productCategoriesForParentProductFk_1) {
		this.id = id;
		this.domain = domain;
		this.productCategoryByParentCategoryFk = productCategoryByParentCategoryFk;
		this.productCategoryByParentProductFk = productCategoryByParentProductFk;
		this.description = description;
		this.productCategoryType = productCategoryType;
		this.type = type;
		this.productsForProductCategoryFk = productsForProductCategoryFk;
		this.productCategoriesForParentCategoryFk = productCategoriesForParentCategoryFk;
		this.productsForProductCategoryFk_1 = productsForProductCategoryFk_1;
		this.productsForParentcategoryIdOid = productsForParentcategoryIdOid;
		this.productCategoriesForParentProductFk = productCategoriesForParentProductFk;
		this.productCategoriesForParentCategoryFk_1 = productCategoriesForParentCategoryFk_1;
		this.productsForParentcategoryIdOid_1 = productsForParentcategoryIdOid_1;
		this.productCategoriesForParentProductFk_1 = productCategoriesForParentProductFk_1;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN_FK")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_CATEGORY_FK")
	public ProductCategory getProductCategoryByParentCategoryFk() {
		return this.productCategoryByParentCategoryFk;
	}

	public void setProductCategoryByParentCategoryFk(ProductCategory productCategoryByParentCategoryFk) {
		this.productCategoryByParentCategoryFk = productCategoryByParentCategoryFk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_PRODUCT_FK")
	public ProductCategory getProductCategoryByParentProductFk() {
		return this.productCategoryByParentProductFk;
	}

	public void setProductCategoryByParentProductFk(ProductCategory productCategoryByParentProductFk) {
		this.productCategoryByParentProductFk = productCategoryByParentProductFk;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PRODUCT_CATEGORY_TYPE")
	public String getProductCategoryType() {
		return this.productCategoryType;
	}

	public void setProductCategoryType(String productCategoryType) {
		this.productCategoryType = productCategoryType;
	}

	@Column(name = "TYPE")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategoryByProductCategoryFk")
	public Set<Product> getProductsForProductCategoryFk() {
		return this.productsForProductCategoryFk;
	}

	public void setProductsForProductCategoryFk(Set<Product> productsForProductCategoryFk) {
		this.productsForProductCategoryFk = productsForProductCategoryFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategoryByParentCategoryFk")
	public Set<ProductCategory> getProductCategoriesForParentCategoryFk() {
		return this.productCategoriesForParentCategoryFk;
	}

	public void setProductCategoriesForParentCategoryFk(Set<ProductCategory> productCategoriesForParentCategoryFk) {
		this.productCategoriesForParentCategoryFk = productCategoriesForParentCategoryFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategoryByProductCategoryFk")
	public Set<Product> getProductsForProductCategoryFk_1() {
		return this.productsForProductCategoryFk_1;
	}

	public void setProductsForProductCategoryFk_1(Set<Product> productsForProductCategoryFk_1) {
		this.productsForProductCategoryFk_1 = productsForProductCategoryFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategoryByParentcategoryIdOid")
	public Set<Product> getProductsForParentcategoryIdOid() {
		return this.productsForParentcategoryIdOid;
	}

	public void setProductsForParentcategoryIdOid(Set<Product> productsForParentcategoryIdOid) {
		this.productsForParentcategoryIdOid = productsForParentcategoryIdOid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategoryByParentProductFk")
	public Set<ProductCategory> getProductCategoriesForParentProductFk() {
		return this.productCategoriesForParentProductFk;
	}

	public void setProductCategoriesForParentProductFk(Set<ProductCategory> productCategoriesForParentProductFk) {
		this.productCategoriesForParentProductFk = productCategoriesForParentProductFk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategoryByParentCategoryFk")
	public Set<ProductCategory> getProductCategoriesForParentCategoryFk_1() {
		return this.productCategoriesForParentCategoryFk_1;
	}

	public void setProductCategoriesForParentCategoryFk_1(Set<ProductCategory> productCategoriesForParentCategoryFk_1) {
		this.productCategoriesForParentCategoryFk_1 = productCategoriesForParentCategoryFk_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategoryByParentcategoryIdOid")
	public Set<Product> getProductsForParentcategoryIdOid_1() {
		return this.productsForParentcategoryIdOid_1;
	}

	public void setProductsForParentcategoryIdOid_1(Set<Product> productsForParentcategoryIdOid_1) {
		this.productsForParentcategoryIdOid_1 = productsForParentcategoryIdOid_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategoryByParentProductFk")
	public Set<ProductCategory> getProductCategoriesForParentProductFk_1() {
		return this.productCategoriesForParentProductFk_1;
	}

	public void setProductCategoriesForParentProductFk_1(Set<ProductCategory> productCategoriesForParentProductFk_1) {
		this.productCategoriesForParentProductFk_1 = productCategoriesForParentProductFk_1;
	}

}
