package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuoteHeader generated by hbm2java
 */
@Entity
@Table(name = "QUOTE_HEADER", catalog = "namcrm")
public class QuoteHeader implements java.io.Serializable {

	private long id;
	private AccountDetail accountDetail;
	private BusinessDeal businessDeal;
	private CrmType crmTypeByCrmTypeFk;
	private CrmType crmTypeByFreightTypeCrmFk;
	private Currency currency;
	private Domain domain;
	private Organisation organisation;
	private OrgBankDetail orgBankDetail;
	private OrgLocation orgLocation;
	private PersonDetail personDetail;
	private StatusItem statusItem;
	private UserDetails userDetailsByLastModifiedUserFk;
	private UserDetails userDetailsByCreatedByUserFk;
	private String accountPhone;
	private Date createdDate;
	private int deliveryTermsDays;
	private String docSequence;
	private String guid;
	private String installation;
	private boolean isRevised;
	private Date lastModifiedDate;
	private String location;
	private int paymentTermsDays;
	private String personEmail;
	private String personPhone;
	private String quoteMainHeadDetails;
	private String quoteName;
	private String rejectReason;
	private String remarks;
	private Date rentalFrom;
	private Date rentalTo;
	private int rentalDuration;
	private Date validFrom;
	private Date validTo;
	private int validityTermsDays;
	private String warranty;
	private double freightChargePercent;
	private double quotedAmount;
	private int rentalUot;
	private boolean needVerification;
	private double advanceAmount;
	private String paymentTermPeriod;
	private String paymentType;
	private String docPath;
	private Date serviceStartDate;
	private Date serviceEndDate;
	private Set<SalesOrderHeader> salesOrderHeaders = new HashSet<SalesOrderHeader>(0);
	private Set<DeliveryChallan> deliveryChallans = new HashSet<DeliveryChallan>(0);
	private Set<PurchaseOrderHeader> purchaseOrderHeaders = new HashSet<PurchaseOrderHeader>(0);
	private Set<BusinessDeal> businessDeals = new HashSet<BusinessDeal>(0);
	private Set<QuoteItem> quoteItems = new HashSet<QuoteItem>(0);

	public QuoteHeader() {
	}

	public QuoteHeader(long id, int deliveryTermsDays, boolean isRevised, int paymentTermsDays, int rentalDuration,
			int validityTermsDays, double freightChargePercent, double quotedAmount, int rentalUot,
			boolean needVerification, double advanceAmount) {
		this.id = id;
		this.deliveryTermsDays = deliveryTermsDays;
		this.isRevised = isRevised;
		this.paymentTermsDays = paymentTermsDays;
		this.rentalDuration = rentalDuration;
		this.validityTermsDays = validityTermsDays;
		this.freightChargePercent = freightChargePercent;
		this.quotedAmount = quotedAmount;
		this.rentalUot = rentalUot;
		this.needVerification = needVerification;
		this.advanceAmount = advanceAmount;
	}

	public QuoteHeader(long id, AccountDetail accountDetail, BusinessDeal businessDeal, CrmType crmTypeByCrmTypeFk,
			CrmType crmTypeByFreightTypeCrmFk, Currency currency, Domain domain, Organisation organisation,
			OrgBankDetail orgBankDetail, OrgLocation orgLocation, PersonDetail personDetail, StatusItem statusItem,
			UserDetails userDetailsByLastModifiedUserFk, UserDetails userDetailsByCreatedByUserFk, String accountPhone,
			Date createdDate, int deliveryTermsDays, String docSequence, String guid, String installation,
			boolean isRevised, Date lastModifiedDate, String location, int paymentTermsDays, String personEmail,
			String personPhone, String quoteMainHeadDetails, String quoteName, String rejectReason, String remarks,
			Date rentalFrom, Date rentalTo, int rentalDuration, Date validFrom, Date validTo, int validityTermsDays,
			String warranty, double freightChargePercent, double quotedAmount, int rentalUot, boolean needVerification,
			double advanceAmount, String paymentTermPeriod, String paymentType, String docPath, Date serviceStartDate,
			Date serviceEndDate, Set<SalesOrderHeader> salesOrderHeaders, Set<DeliveryChallan> deliveryChallans,
			Set<PurchaseOrderHeader> purchaseOrderHeaders, Set<BusinessDeal> businessDeals, Set<QuoteItem> quoteItems) {
		this.id = id;
		this.accountDetail = accountDetail;
		this.businessDeal = businessDeal;
		this.crmTypeByCrmTypeFk = crmTypeByCrmTypeFk;
		this.crmTypeByFreightTypeCrmFk = crmTypeByFreightTypeCrmFk;
		this.currency = currency;
		this.domain = domain;
		this.organisation = organisation;
		this.orgBankDetail = orgBankDetail;
		this.orgLocation = orgLocation;
		this.personDetail = personDetail;
		this.statusItem = statusItem;
		this.userDetailsByLastModifiedUserFk = userDetailsByLastModifiedUserFk;
		this.userDetailsByCreatedByUserFk = userDetailsByCreatedByUserFk;
		this.accountPhone = accountPhone;
		this.createdDate = createdDate;
		this.deliveryTermsDays = deliveryTermsDays;
		this.docSequence = docSequence;
		this.guid = guid;
		this.installation = installation;
		this.isRevised = isRevised;
		this.lastModifiedDate = lastModifiedDate;
		this.location = location;
		this.paymentTermsDays = paymentTermsDays;
		this.personEmail = personEmail;
		this.personPhone = personPhone;
		this.quoteMainHeadDetails = quoteMainHeadDetails;
		this.quoteName = quoteName;
		this.rejectReason = rejectReason;
		this.remarks = remarks;
		this.rentalFrom = rentalFrom;
		this.rentalTo = rentalTo;
		this.rentalDuration = rentalDuration;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.validityTermsDays = validityTermsDays;
		this.warranty = warranty;
		this.freightChargePercent = freightChargePercent;
		this.quotedAmount = quotedAmount;
		this.rentalUot = rentalUot;
		this.needVerification = needVerification;
		this.advanceAmount = advanceAmount;
		this.paymentTermPeriod = paymentTermPeriod;
		this.paymentType = paymentType;
		this.docPath = docPath;
		this.serviceStartDate = serviceStartDate;
		this.serviceEndDate = serviceEndDate;
		this.salesOrderHeaders = salesOrderHeaders;
		this.deliveryChallans = deliveryChallans;
		this.purchaseOrderHeaders = purchaseOrderHeaders;
		this.businessDeals = businessDeals;
		this.quoteItems = quoteItems;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_FK")
	public AccountDetail getAccountDetail() {
		return this.accountDetail;
	}

	public void setAccountDetail(AccountDetail accountDetail) {
		this.accountDetail = accountDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEAL_ID")
	public BusinessDeal getBusinessDeal() {
		return this.businessDeal;
	}

	public void setBusinessDeal(BusinessDeal businessDeal) {
		this.businessDeal = businessDeal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRM_TYPE_FK")
	public CrmType getCrmTypeByCrmTypeFk() {
		return this.crmTypeByCrmTypeFk;
	}

	public void setCrmTypeByCrmTypeFk(CrmType crmTypeByCrmTypeFk) {
		this.crmTypeByCrmTypeFk = crmTypeByCrmTypeFk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FREIGHT_TYPE_CRM_FK")
	public CrmType getCrmTypeByFreightTypeCrmFk() {
		return this.crmTypeByFreightTypeCrmFk;
	}

	public void setCrmTypeByFreightTypeCrmFk(CrmType crmTypeByFreightTypeCrmFk) {
		this.crmTypeByFreightTypeCrmFk = crmTypeByFreightTypeCrmFk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENCY_FK")
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN_FK")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORG_FK")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORGBANK_FK")
	public OrgBankDetail getOrgBankDetail() {
		return this.orgBankDetail;
	}

	public void setOrgBankDetail(OrgBankDetail orgBankDetail) {
		this.orgBankDetail = orgBankDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORG_LOCATION_FK")
	public OrgLocation getOrgLocation() {
		return this.orgLocation;
	}

	public void setOrgLocation(OrgLocation orgLocation) {
		this.orgLocation = orgLocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_FK")
	public PersonDetail getPersonDetail() {
		return this.personDetail;
	}

	public void setPersonDetail(PersonDetail personDetail) {
		this.personDetail = personDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS_ITEM_FK")
	public StatusItem getStatusItem() {
		return this.statusItem;
	}

	public void setStatusItem(StatusItem statusItem) {
		this.statusItem = statusItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LAST_MODIFIED_USER_FK")
	public UserDetails getUserDetailsByLastModifiedUserFk() {
		return this.userDetailsByLastModifiedUserFk;
	}

	public void setUserDetailsByLastModifiedUserFk(UserDetails userDetailsByLastModifiedUserFk) {
		this.userDetailsByLastModifiedUserFk = userDetailsByLastModifiedUserFk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY_USER_FK")
	public UserDetails getUserDetailsByCreatedByUserFk() {
		return this.userDetailsByCreatedByUserFk;
	}

	public void setUserDetailsByCreatedByUserFk(UserDetails userDetailsByCreatedByUserFk) {
		this.userDetailsByCreatedByUserFk = userDetailsByCreatedByUserFk;
	}

	@Column(name = "ACCOUNT_PHONE")
	public String getAccountPhone() {
		return this.accountPhone;
	}

	public void setAccountPhone(String accountPhone) {
		this.accountPhone = accountPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "DELIVERY_TERMS_DAYS", nullable = false)
	public int getDeliveryTermsDays() {
		return this.deliveryTermsDays;
	}

	public void setDeliveryTermsDays(int deliveryTermsDays) {
		this.deliveryTermsDays = deliveryTermsDays;
	}

	@Column(name = "DOC_SEQUENCE")
	public String getDocSequence() {
		return this.docSequence;
	}

	public void setDocSequence(String docSequence) {
		this.docSequence = docSequence;
	}

	@Column(name = "GUID")
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "INSTALLATION")
	public String getInstallation() {
		return this.installation;
	}

	public void setInstallation(String installation) {
		this.installation = installation;
	}

	@Column(name = "IS_REVISED", nullable = false)
	public boolean isIsRevised() {
		return this.isRevised;
	}

	public void setIsRevised(boolean isRevised) {
		this.isRevised = isRevised;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "LOCATION")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "PAYMENT_TERMS_DAYS", nullable = false)
	public int getPaymentTermsDays() {
		return this.paymentTermsDays;
	}

	public void setPaymentTermsDays(int paymentTermsDays) {
		this.paymentTermsDays = paymentTermsDays;
	}

	@Column(name = "PERSON_EMAIL")
	public String getPersonEmail() {
		return this.personEmail;
	}

	public void setPersonEmail(String personEmail) {
		this.personEmail = personEmail;
	}

	@Column(name = "PERSON_PHONE")
	public String getPersonPhone() {
		return this.personPhone;
	}

	public void setPersonPhone(String personPhone) {
		this.personPhone = personPhone;
	}

	@Column(name = "QUOTE_MAIN_HEAD_DETAILS", length = 16777215)
	public String getQuoteMainHeadDetails() {
		return this.quoteMainHeadDetails;
	}

	public void setQuoteMainHeadDetails(String quoteMainHeadDetails) {
		this.quoteMainHeadDetails = quoteMainHeadDetails;
	}

	@Column(name = "QUOTE_NAME")
	public String getQuoteName() {
		return this.quoteName;
	}

	public void setQuoteName(String quoteName) {
		this.quoteName = quoteName;
	}

	@Column(name = "REJECT_REASON", length = 16777215)
	public String getRejectReason() {
		return this.rejectReason;
	}

	public void setRejectReason(String rejectReason) {
		this.rejectReason = rejectReason;
	}

	@Column(name = "REMARKS", length = 16777215)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RENTAL_FROM", length = 19)
	public Date getRentalFrom() {
		return this.rentalFrom;
	}

	public void setRentalFrom(Date rentalFrom) {
		this.rentalFrom = rentalFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RENTAL_TO", length = 19)
	public Date getRentalTo() {
		return this.rentalTo;
	}

	public void setRentalTo(Date rentalTo) {
		this.rentalTo = rentalTo;
	}

	@Column(name = "RENTAL_DURATION", nullable = false)
	public int getRentalDuration() {
		return this.rentalDuration;
	}

	public void setRentalDuration(int rentalDuration) {
		this.rentalDuration = rentalDuration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VALID_FROM", length = 19)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VALID_TO", length = 19)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	@Column(name = "VALIDITY_TERMS_DAYS", nullable = false)
	public int getValidityTermsDays() {
		return this.validityTermsDays;
	}

	public void setValidityTermsDays(int validityTermsDays) {
		this.validityTermsDays = validityTermsDays;
	}

	@Column(name = "WARRANTY")
	public String getWarranty() {
		return this.warranty;
	}

	public void setWarranty(String warranty) {
		this.warranty = warranty;
	}

	@Column(name = "FREIGHT_CHARGE_PERCENT", nullable = false, precision = 22, scale = 0)
	public double getFreightChargePercent() {
		return this.freightChargePercent;
	}

	public void setFreightChargePercent(double freightChargePercent) {
		this.freightChargePercent = freightChargePercent;
	}

	@Column(name = "QUOTED_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getQuotedAmount() {
		return this.quotedAmount;
	}

	public void setQuotedAmount(double quotedAmount) {
		this.quotedAmount = quotedAmount;
	}

	@Column(name = "RENTAL_UOT", nullable = false)
	public int getRentalUot() {
		return this.rentalUot;
	}

	public void setRentalUot(int rentalUot) {
		this.rentalUot = rentalUot;
	}

	@Column(name = "NEED_VERIFICATION", nullable = false)
	public boolean isNeedVerification() {
		return this.needVerification;
	}

	public void setNeedVerification(boolean needVerification) {
		this.needVerification = needVerification;
	}

	@Column(name = "ADVANCE_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getAdvanceAmount() {
		return this.advanceAmount;
	}

	public void setAdvanceAmount(double advanceAmount) {
		this.advanceAmount = advanceAmount;
	}

	@Column(name = "PAYMENT_TERM_PERIOD")
	public String getPaymentTermPeriod() {
		return this.paymentTermPeriod;
	}

	public void setPaymentTermPeriod(String paymentTermPeriod) {
		this.paymentTermPeriod = paymentTermPeriod;
	}

	@Column(name = "PAYMENT_TYPE")
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "DOC_PATH")
	public String getDocPath() {
		return this.docPath;
	}

	public void setDocPath(String docPath) {
		this.docPath = docPath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SERVICE_START_DATE", length = 19)
	public Date getServiceStartDate() {
		return this.serviceStartDate;
	}

	public void setServiceStartDate(Date serviceStartDate) {
		this.serviceStartDate = serviceStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SERVICE_END_DATE", length = 19)
	public Date getServiceEndDate() {
		return this.serviceEndDate;
	}

	public void setServiceEndDate(Date serviceEndDate) {
		this.serviceEndDate = serviceEndDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quoteHeader")
	public Set<SalesOrderHeader> getSalesOrderHeaders() {
		return this.salesOrderHeaders;
	}

	public void setSalesOrderHeaders(Set<SalesOrderHeader> salesOrderHeaders) {
		this.salesOrderHeaders = salesOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quoteHeader")
	public Set<DeliveryChallan> getDeliveryChallans() {
		return this.deliveryChallans;
	}

	public void setDeliveryChallans(Set<DeliveryChallan> deliveryChallans) {
		this.deliveryChallans = deliveryChallans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quoteHeader")
	public Set<PurchaseOrderHeader> getPurchaseOrderHeaders() {
		return this.purchaseOrderHeaders;
	}

	public void setPurchaseOrderHeaders(Set<PurchaseOrderHeader> purchaseOrderHeaders) {
		this.purchaseOrderHeaders = purchaseOrderHeaders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quoteHeader")
	public Set<BusinessDeal> getBusinessDeals() {
		return this.businessDeals;
	}

	public void setBusinessDeals(Set<BusinessDeal> businessDeals) {
		this.businessDeals = businessDeals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quoteHeader")
	public Set<QuoteItem> getQuoteItems() {
		return this.quoteItems;
	}

	public void setQuoteItems(Set<QuoteItem> quoteItems) {
		this.quoteItems = quoteItems;
	}

}
