package com.connectivity.vikray.entity;
// Generated 6 Dec, 2018 11:37:25 AM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recievable generated by hbm2java
 */
@Entity
@Table(name = "RECIEVABLE", catalog = "namcrm")
public class Recievable implements java.io.Serializable {

	private long id;
	private AccountDetail accountDetail;
	private FinancialReport financialReport;
	private InvoiceHeader invoiceHeader;
	private double paymentTermDays;
	private String customerPoNumber;
	private double customerInvAmount;
	private Date customerInvDate;
	private String customerInvNumber;
	private String customerName;
	private boolean isRecieved;
	private double pendingRecievableAmt;
	private String remarks;
	private double totalRecieved;
	private double totalTdsAmount;
	private String currency;
	private double totalBankCharges;
	private double sgstAmount;
	private double cgstAmount;
	private double igstAmount;
	private double totalForeignGainLoss;

	public Recievable() {
	}

	public Recievable(long id, double paymentTermDays, double customerInvAmount, boolean isRecieved,
			double pendingRecievableAmt, double totalRecieved, double totalTdsAmount, double totalBankCharges,
			double sgstAmount, double cgstAmount, double igstAmount, double totalForeignGainLoss) {
		this.id = id;
		this.paymentTermDays = paymentTermDays;
		this.customerInvAmount = customerInvAmount;
		this.isRecieved = isRecieved;
		this.pendingRecievableAmt = pendingRecievableAmt;
		this.totalRecieved = totalRecieved;
		this.totalTdsAmount = totalTdsAmount;
		this.totalBankCharges = totalBankCharges;
		this.sgstAmount = sgstAmount;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.totalForeignGainLoss = totalForeignGainLoss;
	}

	public Recievable(long id, AccountDetail accountDetail, FinancialReport financialReport,
			InvoiceHeader invoiceHeader, double paymentTermDays, String customerPoNumber, double customerInvAmount,
			Date customerInvDate, String customerInvNumber, String customerName, boolean isRecieved,
			double pendingRecievableAmt, String remarks, double totalRecieved, double totalTdsAmount, String currency,
			double totalBankCharges, double sgstAmount, double cgstAmount, double igstAmount,
			double totalForeignGainLoss) {
		this.id = id;
		this.accountDetail = accountDetail;
		this.financialReport = financialReport;
		this.invoiceHeader = invoiceHeader;
		this.paymentTermDays = paymentTermDays;
		this.customerPoNumber = customerPoNumber;
		this.customerInvAmount = customerInvAmount;
		this.customerInvDate = customerInvDate;
		this.customerInvNumber = customerInvNumber;
		this.customerName = customerName;
		this.isRecieved = isRecieved;
		this.pendingRecievableAmt = pendingRecievableAmt;
		this.remarks = remarks;
		this.totalRecieved = totalRecieved;
		this.totalTdsAmount = totalTdsAmount;
		this.currency = currency;
		this.totalBankCharges = totalBankCharges;
		this.sgstAmount = sgstAmount;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.totalForeignGainLoss = totalForeignGainLoss;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_FK")
	public AccountDetail getAccountDetail() {
		return this.accountDetail;
	}

	public void setAccountDetail(AccountDetail accountDetail) {
		this.accountDetail = accountDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FINAANCIAL_FK")
	public FinancialReport getFinancialReport() {
		return this.financialReport;
	}

	public void setFinancialReport(FinancialReport financialReport) {
		this.financialReport = financialReport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVOICE_FK")
	public InvoiceHeader getInvoiceHeader() {
		return this.invoiceHeader;
	}

	public void setInvoiceHeader(InvoiceHeader invoiceHeader) {
		this.invoiceHeader = invoiceHeader;
	}

	@Column(name = "PAYMENT_TERM_DAYS", nullable = false, precision = 22, scale = 0)
	public double getPaymentTermDays() {
		return this.paymentTermDays;
	}

	public void setPaymentTermDays(double paymentTermDays) {
		this.paymentTermDays = paymentTermDays;
	}

	@Column(name = "CUSTOMER_PO_NUMBER")
	public String getCustomerPoNumber() {
		return this.customerPoNumber;
	}

	public void setCustomerPoNumber(String customerPoNumber) {
		this.customerPoNumber = customerPoNumber;
	}

	@Column(name = "CUSTOMER_INV_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getCustomerInvAmount() {
		return this.customerInvAmount;
	}

	public void setCustomerInvAmount(double customerInvAmount) {
		this.customerInvAmount = customerInvAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CUSTOMER_INV_DATE", length = 19)
	public Date getCustomerInvDate() {
		return this.customerInvDate;
	}

	public void setCustomerInvDate(Date customerInvDate) {
		this.customerInvDate = customerInvDate;
	}

	@Column(name = "CUSTOMER_INV_NUMBER")
	public String getCustomerInvNumber() {
		return this.customerInvNumber;
	}

	public void setCustomerInvNumber(String customerInvNumber) {
		this.customerInvNumber = customerInvNumber;
	}

	@Column(name = "CUSTOMER_NAME")
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "IS_RECIEVED", nullable = false)
	public boolean isIsRecieved() {
		return this.isRecieved;
	}

	public void setIsRecieved(boolean isRecieved) {
		this.isRecieved = isRecieved;
	}

	@Column(name = "PENDING_RECIEVABLE_AMT", nullable = false, precision = 22, scale = 0)
	public double getPendingRecievableAmt() {
		return this.pendingRecievableAmt;
	}

	public void setPendingRecievableAmt(double pendingRecievableAmt) {
		this.pendingRecievableAmt = pendingRecievableAmt;
	}

	@Column(name = "REMARKS", length = 16777215)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "TOTAL_RECIEVED", nullable = false, precision = 22, scale = 0)
	public double getTotalRecieved() {
		return this.totalRecieved;
	}

	public void setTotalRecieved(double totalRecieved) {
		this.totalRecieved = totalRecieved;
	}

	@Column(name = "TOTAL_TDS_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getTotalTdsAmount() {
		return this.totalTdsAmount;
	}

	public void setTotalTdsAmount(double totalTdsAmount) {
		this.totalTdsAmount = totalTdsAmount;
	}

	@Column(name = "CURRENCY")
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "TOTAL_BANK_CHARGES", nullable = false, precision = 22, scale = 0)
	public double getTotalBankCharges() {
		return this.totalBankCharges;
	}

	public void setTotalBankCharges(double totalBankCharges) {
		this.totalBankCharges = totalBankCharges;
	}

	@Column(name = "SGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getSgstAmount() {
		return this.sgstAmount;
	}

	public void setSgstAmount(double sgstAmount) {
		this.sgstAmount = sgstAmount;
	}

	@Column(name = "CGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getCgstAmount() {
		return this.cgstAmount;
	}

	public void setCgstAmount(double cgstAmount) {
		this.cgstAmount = cgstAmount;
	}

	@Column(name = "IGST_AMOUNT", nullable = false, precision = 22, scale = 0)
	public double getIgstAmount() {
		return this.igstAmount;
	}

	public void setIgstAmount(double igstAmount) {
		this.igstAmount = igstAmount;
	}

	@Column(name = "TOTAL_FOREIGN_GAIN_LOSS", nullable = false, precision = 22, scale = 0)
	public double getTotalForeignGainLoss() {
		return this.totalForeignGainLoss;
	}

	public void setTotalForeignGainLoss(double totalForeignGainLoss) {
		this.totalForeignGainLoss = totalForeignGainLoss;
	}

}
