package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Research generated by hbm2java
 */
@Entity
@Table(name = "RESEARCH", catalog = "namcrm")
public class Research implements java.io.Serializable {

	private long id;
	private BusinessDeal businessDeal;
	private ResearchKey researchKey;
	private String researchValue;

	public Research() {
	}

	public Research(long id) {
		this.id = id;
	}

	public Research(long id, BusinessDeal businessDeal, ResearchKey researchKey, String researchValue) {
		this.id = id;
		this.businessDeal = businessDeal;
		this.researchKey = researchKey;
		this.researchValue = researchValue;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEAL_FK")
	public BusinessDeal getBusinessDeal() {
		return this.businessDeal;
	}

	public void setBusinessDeal(BusinessDeal businessDeal) {
		this.businessDeal = businessDeal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESEARCH_KEY_FK")
	public ResearchKey getResearchKey() {
		return this.researchKey;
	}

	public void setResearchKey(ResearchKey researchKey) {
		this.researchKey = researchKey;
	}

	@Column(name = "RESEARCH_VALUE", length = 16777215)
	public String getResearchValue() {
		return this.researchValue;
	}

	public void setResearchValue(String researchValue) {
		this.researchValue = researchValue;
	}

}
