package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResearchKey generated by hbm2java
 */
@Entity
@Table(name = "RESEARCH_KEY", catalog = "namcrm")
public class ResearchKey implements java.io.Serializable {

	private long id;
	private boolean isNumber;
	private String keyName;
	private Set<Research> researches = new HashSet<Research>(0);

	public ResearchKey() {
	}

	public ResearchKey(long id, boolean isNumber) {
		this.id = id;
		this.isNumber = isNumber;
	}

	public ResearchKey(long id, boolean isNumber, String keyName, Set<Research> researches) {
		this.id = id;
		this.isNumber = isNumber;
		this.keyName = keyName;
		this.researches = researches;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "IS_NUMBER", nullable = false)
	public boolean isIsNumber() {
		return this.isNumber;
	}

	public void setIsNumber(boolean isNumber) {
		this.isNumber = isNumber;
	}

	@Column(name = "KEY_NAME")
	public String getKeyName() {
		return this.keyName;
	}

	public void setKeyName(String keyName) {
		this.keyName = keyName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "researchKey")
	public Set<Research> getResearches() {
		return this.researches;
	}

	public void setResearches(Set<Research> researches) {
		this.researches = researches;
	}

}
