package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SalesPerformance generated by hbm2java
 */
@Entity
@Table(name = "SALES_PERFORMANCE", catalog = "namcrm")
public class SalesPerformance implements java.io.Serializable {

	private long id;
	private Domain domain;
	private UserDetails userDetails;
	private double achieved;
	private double gap;
	private int leads;
	private int month;
	private int proposals;
	private double target;
	private int wins;
	private int year;
	private int quarter;
	private boolean isTeam;
	private double achievedpercent;
	private double gappercent;
	private double incentive;

	public SalesPerformance() {
	}

	public SalesPerformance(long id, double achieved, double gap, int leads, int month, int proposals, double target,
			int wins, int year, int quarter, boolean isTeam, double achievedpercent, double gappercent,
			double incentive) {
		this.id = id;
		this.achieved = achieved;
		this.gap = gap;
		this.leads = leads;
		this.month = month;
		this.proposals = proposals;
		this.target = target;
		this.wins = wins;
		this.year = year;
		this.quarter = quarter;
		this.isTeam = isTeam;
		this.achievedpercent = achievedpercent;
		this.gappercent = gappercent;
		this.incentive = incentive;
	}

	public SalesPerformance(long id, Domain domain, UserDetails userDetails, double achieved, double gap, int leads,
			int month, int proposals, double target, int wins, int year, int quarter, boolean isTeam,
			double achievedpercent, double gappercent, double incentive) {
		this.id = id;
		this.domain = domain;
		this.userDetails = userDetails;
		this.achieved = achieved;
		this.gap = gap;
		this.leads = leads;
		this.month = month;
		this.proposals = proposals;
		this.target = target;
		this.wins = wins;
		this.year = year;
		this.quarter = quarter;
		this.isTeam = isTeam;
		this.achievedpercent = achievedpercent;
		this.gappercent = gappercent;
		this.incentive = incentive;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN_FK")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_FK")
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "ACHIEVED", nullable = false, precision = 22, scale = 0)
	public double getAchieved() {
		return this.achieved;
	}

	public void setAchieved(double achieved) {
		this.achieved = achieved;
	}

	@Column(name = "GAP", nullable = false, precision = 22, scale = 0)
	public double getGap() {
		return this.gap;
	}

	public void setGap(double gap) {
		this.gap = gap;
	}

	@Column(name = "LEADS", nullable = false)
	public int getLeads() {
		return this.leads;
	}

	public void setLeads(int leads) {
		this.leads = leads;
	}

	@Column(name = "MONTH", nullable = false)
	public int getMonth() {
		return this.month;
	}

	public void setMonth(int month) {
		this.month = month;
	}

	@Column(name = "PROPOSALS", nullable = false)
	public int getProposals() {
		return this.proposals;
	}

	public void setProposals(int proposals) {
		this.proposals = proposals;
	}

	@Column(name = "TARGET", nullable = false, precision = 22, scale = 0)
	public double getTarget() {
		return this.target;
	}

	public void setTarget(double target) {
		this.target = target;
	}

	@Column(name = "WINS", nullable = false)
	public int getWins() {
		return this.wins;
	}

	public void setWins(int wins) {
		this.wins = wins;
	}

	@Column(name = "YEAR", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "QUARTER", nullable = false)
	public int getQuarter() {
		return this.quarter;
	}

	public void setQuarter(int quarter) {
		this.quarter = quarter;
	}

	@Column(name = "IS_TEAM", nullable = false)
	public boolean isIsTeam() {
		return this.isTeam;
	}

	public void setIsTeam(boolean isTeam) {
		this.isTeam = isTeam;
	}

	@Column(name = "ACHIEVEDPERCENT", nullable = false, precision = 22, scale = 0)
	public double getAchievedpercent() {
		return this.achievedpercent;
	}

	public void setAchievedpercent(double achievedpercent) {
		this.achievedpercent = achievedpercent;
	}

	@Column(name = "GAPPERCENT", nullable = false, precision = 22, scale = 0)
	public double getGappercent() {
		return this.gappercent;
	}

	public void setGappercent(double gappercent) {
		this.gappercent = gappercent;
	}

	@Column(name = "INCENTIVE", nullable = false, precision = 22, scale = 0)
	public double getIncentive() {
		return this.incentive;
	}

	public void setIncentive(double incentive) {
		this.incentive = incentive;
	}

}
