package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SaleCommit generated by hbm2java
 */
@Entity
@Table(name = "SALE_COMMIT", catalog = "namcrm")
public class SaleCommit implements java.io.Serializable {

	private long id;
	private BusinessDeal businessDeal;
	private int weekOfYear;
	private int year;
	private Integer salecommitsIntegerIdx;

	public SaleCommit() {
	}

	public SaleCommit(long id, int weekOfYear, int year) {
		this.id = id;
		this.weekOfYear = weekOfYear;
		this.year = year;
	}

	public SaleCommit(long id, BusinessDeal businessDeal, int weekOfYear, int year, Integer salecommitsIntegerIdx) {
		this.id = id;
		this.businessDeal = businessDeal;
		this.weekOfYear = weekOfYear;
		this.year = year;
		this.salecommitsIntegerIdx = salecommitsIntegerIdx;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEAL_FK")
	public BusinessDeal getBusinessDeal() {
		return this.businessDeal;
	}

	public void setBusinessDeal(BusinessDeal businessDeal) {
		this.businessDeal = businessDeal;
	}

	@Column(name = "WEEK_OF_YEAR", nullable = false)
	public int getWeekOfYear() {
		return this.weekOfYear;
	}

	public void setWeekOfYear(int weekOfYear) {
		this.weekOfYear = weekOfYear;
	}

	@Column(name = "YEAR", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "SALECOMMITS_INTEGER_IDX")
	public Integer getSalecommitsIntegerIdx() {
		return this.salecommitsIntegerIdx;
	}

	public void setSalecommitsIntegerIdx(Integer salecommitsIntegerIdx) {
		this.salecommitsIntegerIdx = salecommitsIntegerIdx;
	}

}
