package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SequenceTable generated by hbm2java
 */
@Entity
@Table(name = "SEQUENCE_TABLE", catalog = "namcrm")
public class SequenceTable implements java.io.Serializable {

	private String sequenceName;
	private long nextVal;

	public SequenceTable() {
	}

	public SequenceTable(String sequenceName, long nextVal) {
		this.sequenceName = sequenceName;
		this.nextVal = nextVal;
	}

	@Id

	@Column(name = "SEQUENCE_NAME", unique = true, nullable = false)
	public String getSequenceName() {
		return this.sequenceName;
	}

	public void setSequenceName(String sequenceName) {
		this.sequenceName = sequenceName;
	}

	@Column(name = "NEXT_VAL", nullable = false)
	public long getNextVal() {
		return this.nextVal;
	}

	public void setNextVal(long nextVal) {
		this.nextVal = nextVal;
	}

}
