package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaskCcUser generated by hbm2java
 */
@Entity
@Table(name = "TASK_CC_USER", catalog = "namcrm")
public class TaskCcUser implements java.io.Serializable {

	private long id;
	private Task task;
	private UserDetails userDetails;

	public TaskCcUser() {
	}

	public TaskCcUser(long id) {
		this.id = id;
	}

	public TaskCcUser(long id, Task task, UserDetails userDetails) {
		this.id = id;
		this.task = task;
		this.userDetails = userDetails;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TASK_FK")
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_FK")
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

}
