package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaskStatus generated by hbm2java
 */
@Entity
@Table(name = "TASK_STATUS", catalog = "namcrm")
public class TaskStatus implements java.io.Serializable {

	private long id;
	private String constByName;
	private String label;
	private Set<Task> tasks = new HashSet<Task>(0);

	public TaskStatus() {
	}

	public TaskStatus(long id) {
		this.id = id;
	}

	public TaskStatus(long id, String constByName, String label, Set<Task> tasks) {
		this.id = id;
		this.constByName = constByName;
		this.label = label;
		this.tasks = tasks;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CONST_BY_NAME")
	public String getConstByName() {
		return this.constByName;
	}

	public void setConstByName(String constByName) {
		this.constByName = constByName;
	}

	@Column(name = "LABEL")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taskStatus")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
