package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "TASK", catalog = "vikrayPmo")
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(value = { "createDate", "modifyDate" }, allowGetters = true)
public class Task implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long id;
	private String comments;
	private String replies;
	// private BusinessDeal businessDeal;
	private String buisnessDeal;
	private Domain domain;
	private TaskPriority taskPriority;
	private TaskStatus taskStatus;
	private UserDetails userDetailsByAssigneeUserFk;
	private UserDetails userDetailsByCreatorUserFk;
	private UserDetails createdBy;
	private UserDetails updatedBy;
	private Date dueDate;
	private String guid;
	private Date lastUpdatedOn;
	private String taskName;
	private String taskUrl;
	private Date verifiedOn;

	// New fields added for vikray-PMO by Pawan @18-01-2019
	private Phase phaseFk;
	private String description;
	private String instruction;
	// private AccountAddress accountAddressFk;
	private String accountAddress;
	private Set<Documents> documents = new HashSet<Documents>(0);
	private Set<TaskComment> taskComments = new HashSet<TaskComment>(0);
	private Set<TaskCcUser> taskCcUsers = new HashSet<TaskCcUser>(0);

	@Column(name = "create_date", nullable = false, updatable = false)
	@Temporal(TemporalType.TIMESTAMP)
	@CreatedDate
	private Date createDate;

	@Column(name = "modify_date", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	@LastModifiedDate
	private Date modifyDate;

	public Task() {
	}

	public Task(long id) {
		this.id = id;
	}

	public Task(long id, String comments, String replies, String buisnessDeal, Domain domain, TaskPriority taskPriority,
			TaskStatus taskStatus, UserDetails userDetailsByAssigneeUserFk, UserDetails userDetailsByCreatorUserFk,
			UserDetails createdBy, UserDetails updatedBy, Date dueDate, String guid, Date lastUpdatedOn,
			String taskName, String taskUrl, Date verifiedOn, Phase phaseFk, String description, String instruction,
			String accountAddress, Set<Documents> documents, Set<TaskComment> taskComments, Set<TaskCcUser> taskCcUsers,
			Date createDate, Date modifyDate) {
		super();
		this.id = id;
		this.comments = comments;
		this.replies = replies;
		this.buisnessDeal = buisnessDeal;
		this.domain = domain;
		this.taskPriority = taskPriority;
		this.taskStatus = taskStatus;
		this.userDetailsByAssigneeUserFk = userDetailsByAssigneeUserFk;
		this.userDetailsByCreatorUserFk = userDetailsByCreatorUserFk;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.dueDate = dueDate;
		this.guid = guid;
		this.lastUpdatedOn = lastUpdatedOn;
		this.taskName = taskName;
		this.taskUrl = taskUrl;
		this.verifiedOn = verifiedOn;
		this.phaseFk = phaseFk;
		this.description = description;
		this.instruction = instruction;
		this.accountAddress = accountAddress;
		this.documents = documents;
		this.taskComments = taskComments;
		this.taskCcUsers = taskCcUsers;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	public String getInstruction() {
		return instruction;
	}

	/*
	 * public void setAccountAddressFk(AccountAddress accountAddressFk) {
	 * this.accountAddressFk = accountAddressFk; }
	 * 
	 * @ManyToOne(fetch = FetchType.LAZY)
	 * 
	 * @JoinColumn(name = "ADDRESS_FK") public AccountAddress getAccountAddressFk()
	 * { return accountAddressFk; }
	 */

	public String getAccountAddress() {
		return accountAddress;
	}

	public void setAccountAddress(String accountAddress) {
		this.accountAddress = accountAddress;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getComments() {
		return comments;
	}

	public void setReplies(String replies) {
		this.replies = replies;
	}

	public String getReplies() {
		return replies;
	}

	/*
	 * @ManyToOne(fetch = FetchType.LAZY)
	 * 
	 * @JoinColumn(name = "DEAL_FK") public BusinessDeal getBusinessDeal() { return
	 * this.businessDeal; }
	 * 
	 * public void setBusinessDeal(BusinessDeal businessDeal) { this.businessDeal =
	 * businessDeal; }
	 */

	public void setBuisnessDeal(String buisnessDeal) {
		this.buisnessDeal = buisnessDeal;
	}

	public String getBuisnessDeal() {
		return buisnessDeal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN_FK")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TASK_PRIORITY_FK")
	public TaskPriority getTaskPriority() {
		return this.taskPriority;
	}

	public void setTaskPriority(TaskPriority taskPriority) {
		this.taskPriority = taskPriority;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TASK_STATUS_FK")
	public TaskStatus getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(TaskStatus taskStatus) {
		this.taskStatus = taskStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASSIGNEE_USER_FK")
	public UserDetails getUserDetailsByAssigneeUserFk() {
		return this.userDetailsByAssigneeUserFk;
	}

	public void setUserDetailsByAssigneeUserFk(UserDetails userDetailsByAssigneeUserFk) {
		this.userDetailsByAssigneeUserFk = userDetailsByAssigneeUserFk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR_USER_FK")
	public UserDetails getUserDetailsByCreatorUserFk() {
		return this.userDetailsByCreatorUserFk;
	}

	public void setUserDetailsByCreatorUserFk(UserDetails userDetailsByCreatorUserFk) {
		this.userDetailsByCreatorUserFk = userDetailsByCreatorUserFk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BYFK")
	public UserDetails getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(UserDetails createdBy) {
		this.createdBy = createdBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BYFK")
	public UserDetails getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(UserDetails updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DUE_DATE", length = 19)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "GUID")
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_ON", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "TASK_NAME")
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "TASK_URL")
	public String getTaskUrl() {
		return this.taskUrl;
	}

	public void setTaskUrl(String taskUrl) {
		this.taskUrl = taskUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VERIFIED_ON", length = 19)
	public Date getVerifiedOn() {
		return this.verifiedOn;
	}

	public void setVerifiedOn(Date verifiedOn) {
		this.verifiedOn = verifiedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<TaskComment> getTaskComments() {
		return this.taskComments;
	}

	public void setTaskComments(Set<TaskComment> taskComments) {
		this.taskComments = taskComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<TaskCcUser> getTaskCcUsers() {
		return this.taskCcUsers;
	}

	public void setTaskCcUsers(Set<TaskCcUser> taskCcUsers) {
		this.taskCcUsers = taskCcUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taskFk")
	public Set<Documents> getDocuments() {
		return documents;
	}

	public void setDocuments(Set<Documents> documents) {
		this.documents = documents;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Phase_FK")
	public Phase getPhaseFk() {
		return phaseFk;
	}

	public void setPhaseFk(Phase phaseFk) {
		this.phaseFk = phaseFk;
	}

}
