package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TaxType generated by hbm2java
 */
@Entity
@Table(name = "TAX_TYPE", catalog = "namcrm")
public class TaxType implements java.io.Serializable {

	private Long taxTypeId;
	private long id;
	private String taxDescription;
	private String taxType;

	public TaxType() {
	}

	public TaxType(long id) {
		this.id = id;
	}

	public TaxType(long id, String taxDescription, String taxType) {
		this.id = id;
		this.taxDescription = taxDescription;
		this.taxType = taxType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TAX_TYPE_ID", unique = true, nullable = false)
	public Long getTaxTypeId() {
		return this.taxTypeId;
	}

	public void setTaxTypeId(Long taxTypeId) {
		this.taxTypeId = taxTypeId;
	}

	@Column(name = "ID", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "TAX_DESCRIPTION")
	public String getTaxDescription() {
		return this.taxDescription;
	}

	public void setTaxDescription(String taxDescription) {
		this.taxDescription = taxDescription;
	}

	@Column(name = "TAX_TYPE")
	public String getTaxType() {
		return this.taxType;
	}

	public void setTaxType(String taxType) {
		this.taxType = taxType;
	}

}
