package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLE", catalog = "namcrm")
public class UserRole implements java.io.Serializable {

	private long id;
	private long roleKey;
	private String roleName;

	public UserRole() {
	}

	public UserRole(long id, long roleKey) {
		this.id = id;
		this.roleKey = roleKey;
	}

	public UserRole(long id, long roleKey, String roleName) {
		this.id = id;
		this.roleKey = roleKey;
		this.roleName = roleName;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ROLE_KEY", nullable = false)
	public long getRoleKey() {
		return this.roleKey;
	}

	public void setRoleKey(long roleKey) {
		this.roleKey = roleKey;
	}

	@Column(name = "ROLE_NAME")
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}
