package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VikrayAnalytics generated by hbm2java
 */
@Entity
@Table(name = "VIKRAY_ANALYTICS", catalog = "namcrm")
public class VikrayAnalytics implements java.io.Serializable {

	private long id;
	private Date dataTime;
	private long domainId;
	private String serviceCalled;
	private String userName;

	public VikrayAnalytics() {
	}

	public VikrayAnalytics(long id, long domainId) {
		this.id = id;
		this.domainId = domainId;
	}

	public VikrayAnalytics(long id, Date dataTime, long domainId, String serviceCalled, String userName) {
		this.id = id;
		this.dataTime = dataTime;
		this.domainId = domainId;
		this.serviceCalled = serviceCalled;
		this.userName = userName;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_TIME", length = 19)
	public Date getDataTime() {
		return this.dataTime;
	}

	public void setDataTime(Date dataTime) {
		this.dataTime = dataTime;
	}

	@Column(name = "DOMAIN_ID", nullable = false)
	public long getDomainId() {
		return this.domainId;
	}

	public void setDomainId(long domainId) {
		this.domainId = domainId;
	}

	@Column(name = "SERVICE_CALLED")
	public String getServiceCalled() {
		return this.serviceCalled;
	}

	public void setServiceCalled(String serviceCalled) {
		this.serviceCalled = serviceCalled;
	}

	@Column(name = "USER_NAME")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
