package com.connectivity.vikray.entity;
// Generated 27 Dec, 2018 3:06:26 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WeeklySalesCommits generated by hbm2java
 */
@Entity
@Table(name = "WEEKLY_SALES_COMMITS", catalog = "namcrm")
public class WeeklySalesCommits implements java.io.Serializable {

	private long id;
	private Domain domain;
	private UserDetails userDetails;
	private double achieved;
	private String amName;
	private double gap;
	private double gapPercent;
	private double lastWeekCommit;
	private double thisweekcommit;
	private double upside;
	private double week;
	private double teamAchieved;
	private double thisWeekUpside;

	public WeeklySalesCommits() {
	}

	public WeeklySalesCommits(long id, double achieved, double gap, double gapPercent, double lastWeekCommit,
			double thisweekcommit, double upside, double week, double teamAchieved, double thisWeekUpside) {
		this.id = id;
		this.achieved = achieved;
		this.gap = gap;
		this.gapPercent = gapPercent;
		this.lastWeekCommit = lastWeekCommit;
		this.thisweekcommit = thisweekcommit;
		this.upside = upside;
		this.week = week;
		this.teamAchieved = teamAchieved;
		this.thisWeekUpside = thisWeekUpside;
	}

	public WeeklySalesCommits(long id, Domain domain, UserDetails userDetails, double achieved, String amName,
			double gap, double gapPercent, double lastWeekCommit, double thisweekcommit, double upside, double week,
			double teamAchieved, double thisWeekUpside) {
		this.id = id;
		this.domain = domain;
		this.userDetails = userDetails;
		this.achieved = achieved;
		this.amName = amName;
		this.gap = gap;
		this.gapPercent = gapPercent;
		this.lastWeekCommit = lastWeekCommit;
		this.thisweekcommit = thisweekcommit;
		this.upside = upside;
		this.week = week;
		this.teamAchieved = teamAchieved;
		this.thisWeekUpside = thisWeekUpside;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOMAIN")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER")
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "ACHIEVED", nullable = false, precision = 22, scale = 0)
	public double getAchieved() {
		return this.achieved;
	}

	public void setAchieved(double achieved) {
		this.achieved = achieved;
	}

	@Column(name = "AM_NAME")
	public String getAmName() {
		return this.amName;
	}

	public void setAmName(String amName) {
		this.amName = amName;
	}

	@Column(name = "GAP", nullable = false, precision = 22, scale = 0)
	public double getGap() {
		return this.gap;
	}

	public void setGap(double gap) {
		this.gap = gap;
	}

	@Column(name = "GAP_PERCENT", nullable = false, precision = 22, scale = 0)
	public double getGapPercent() {
		return this.gapPercent;
	}

	public void setGapPercent(double gapPercent) {
		this.gapPercent = gapPercent;
	}

	@Column(name = "LAST_WEEK_COMMIT", nullable = false, precision = 22, scale = 0)
	public double getLastWeekCommit() {
		return this.lastWeekCommit;
	}

	public void setLastWeekCommit(double lastWeekCommit) {
		this.lastWeekCommit = lastWeekCommit;
	}

	@Column(name = "THISWEEKCOMMIT", nullable = false, precision = 22, scale = 0)
	public double getThisweekcommit() {
		return this.thisweekcommit;
	}

	public void setThisweekcommit(double thisweekcommit) {
		this.thisweekcommit = thisweekcommit;
	}

	@Column(name = "UPSIDE", nullable = false, precision = 22, scale = 0)
	public double getUpside() {
		return this.upside;
	}

	public void setUpside(double upside) {
		this.upside = upside;
	}

	@Column(name = "WEEK", nullable = false, precision = 22, scale = 0)
	public double getWeek() {
		return this.week;
	}

	public void setWeek(double week) {
		this.week = week;
	}

	@Column(name = "TEAM_ACHIEVED", nullable = false, precision = 22, scale = 0)
	public double getTeamAchieved() {
		return this.teamAchieved;
	}

	public void setTeamAchieved(double teamAchieved) {
		this.teamAchieved = teamAchieved;
	}

	@Column(name = "THIS_WEEK_UPSIDE", nullable = false, precision = 22, scale = 0)
	public double getThisWeekUpside() {
		return this.thisWeekUpside;
	}

	public void setThisWeekUpside(double thisWeekUpside) {
		this.thisWeekUpside = thisWeekUpside;
	}

}
